### ISSUE TITLE
fbox.to error, can't search for anything

### ISSUE THREAD

**Issue by crxssed7** [mbebe/blomqvist#1000]
Logs: 
```
2023-10-17 20:45:28.795 T:2205937856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.fboxto/main.py", line 929, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/pi/.kodi/addons/plugin.video.fboxto/main.py", line 922, in router
                                                ListMovies(url,'1')
                                              File "/home/pi/.kodi/addons/plugin.video.fboxto/main.py", line 169, in ListMovies
                                                links, serials, pagin = getMovies(exlink,page)
                                              File "/home/pi/.kodi/addons/plugin.video.fboxto/main.py", line 217, in getMovies
                                                result = parseDOM(html, 'div', attrs={'class': "filmlist md"}) [0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2023-10-17 20:45:28.927 T:2131239104   ERROR: GetDirectory - Error getting plugin://plugin.video.fboxto/?image=DefaultAddonsSearch.png&mode=search&movie=True&moviescount=0&page=1&title=%5bCOLOR%20lightblue%5dSearch%5b%2fCOLOR%5d&url
2023-10-17 20:45:28.934 T:2972687488   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fboxto/?image=DefaultAddonsSearch.png&mode=search&movie=True&moviescount=0&page=1&title=%5bCOLOR%20lightblue%5dSearch%5b%2fCOLOR%5d&url) failed
```

**Comment by mbebe** [comment]
new version is available in repo.

**Comment by crxssed7** [comment]
Still doesn't work for me unfortunately. Had a look around the code and found that it's using the fmovies url for the search:
`url = 'https://fmoviesz.to/filter?keyword='+query.replace(' ','+')`

Unfortunately fmovies is blocked in my region so this throws an error when trying to make a request.

Changing the domain to fbox.to fixes the issue.

**Comment by mbebe** [comment]
Ok, update is available in repo. version 1.2

**Comment by crxssed7** [comment]
Can confirm the addon works now.
