### ISSUE TITLE
Canal+ problem

### ISSUE THREAD

**Issue by mkaflowski** [mbebe/blomqvist#1006]
Nie działa mi wtyczka na świeżej instalacji. Dostaję błąd:

> 2023-10-24 16:25:54.154 T:4440199   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'KeyError'>
>                                                    Error Contents: 'available'
>                                                    Traceback (most recent call last):
>                                                      File "/Users/mkaflowski/Library/Application Support/Kodi/addons/plugin.video.canalplusvod/main.py", line 1405, in <module>
>                                                        PLAYvod2(exlink)
>                                                      File "/Users/mkaflowski/Library/Application Support/Kodi/addons/plugin.video.canalplusvod/main.py", line 373, in PLAYvod2
>                                                        for stream_datas in value_datas_jsonparser["available"]:
>                                                                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
>                                                    KeyError: 'available'
>                                                    -->End of Python script error report<--

                                                   
Czy wszyscy tak mają?

**Comment by mtr81** [comment]
Problem znany od 10 miesięcy. Zmieniono schemat logowania w serwisie i w chwili obecnej we wtyczce w prosty sposób się nie zalogujesz. Literatura: https://github.com/mbebe/blomqvist/issues/886  Na szybko proponuję przekopiować do nowego urządzenia plik settings.xml znajdujący się w katalogu /userdata/addon_data/plugin.video.canalplusvod urządzenia, na którym byłeś zalogowany.

**Comment by mkaflowski** [comment]
U mnie to samo

**Comment by salustre** [comment]
@kedarz @mkaflowski  jest literówka w nazwie pliku, ściągnijcie sobie stąd 👇🏻
https://github.com/mbebe/blomqvist/tree/master/zips
następnie zainstalujcie ręcznie

**Comment by salustre** [comment]
> Problem znany od 10 miesięcy. Zmieniono schemat logowania w serwisie i w chwili obecnej we wtyczce w prosty sposób się nie zalogujesz. Literatura: https://github.com/mbebe/blomqvist/issues/886  Na szybko proponuję przekopiować do nowego urządzenia plik settings.xml znajdujący się w katalogu /userdata/addon_data/plugin.video.canalplusvod urządzenia, na którym byłeś zalogowany.

Cześć, w ten sposób funkcjonowałem od kilku miesięcy niestety, niedawno wywaliło mnie na wszystkich urządzeniach, pewnie credki straciły ważność.

Wielka prośba by w kilku żołnierskich słowach napisać które ciastka (po zalogowaniu via browser) wydobyć i do których zmiennych dopisać we wtyczce.

Problem jest znany od 10 miesięcy, jak dotąd nie ma na niego prostego rozwiązania, więc taka procedurka z pewnością pomoże wielu osobom.

Pozdrawiam

**Comment by mtr81** [comment]
Proszę korzystać z oficjalnej apki.

**Comment by salustre** [comment]
Żebym był dobrze zrozumiany, nie mam do nikogo pretensji, tylko grzecznie proszę, jeżeli istnieje na obecną chwilę workaround by korzystać z wtyczki, to by ktoś się nim podzielił.

Pozdrawiam

**Comment by mtr81** [comment]
Pisanie wtyczek i szukanie rozwiązań, żeby je naprawić wymaga sporo nakładu pracy i czasu. I jeśli obserwuję, że dostawca usług po upublicznieniu wtyczek/ poprawek wprowadza kolejne ograniczenia (a tak właśnie w przypadku Canal+), to tego nie robię. Proszę to zrozumieć. Mogę się jedynie podzielić efektami pracy z osobami, które wnoszą jakikolwiek wkład w rozwój Kodi, pluginów i innych związanych z tym programem narzędzi.

**Comment by salustre** [comment]
Rozumiem i nie naciskam kolejne release wtyczki, ani na debuggowanie wszystkich problemów z nią związanych, szczególnie przy tak upierdliwym działaniu ze strony canal+ bardziej pytam o znane już od pewnego czasu obejście, jak skorzystać z bieżącej wersji wtyczki wykorzystując cookie,  de facto gdzie umieścić we wtyczce dane, które sobie sam wyciągnę. Mam nadzieję, że to nie problem i moją prośbą w żaden sposób nie chcę umniejszać roli osób, które rozwijają kodi i wtyczki do niego.

Pozdrawiam

**Comment by mtr81** [comment]
Podpowiem, że z obecnej wersji wtyczki i tak nie skorzystasz, bo w ciągu roku zaszły tam inne zmiany -np. związane z odtwarzaniem VOD na niektórych systemach. Obsługa SSL też nie została kompleksowo poprawiona.

**Comment by salustre** [comment]
Odnośnie VOD zauważyłem te problemy, ale jeśli nadal da się oglądać "TV na żywo" (z tego głównie korzystam), to mi wystarczy. Zależy mi na przywróceniu funkcjonalności jaką miałem tydzień temu 😉

 Z tego co widziełem cookie mają dość długą, ale jednak ograniczoną ważność i najzwyczajniej w świecie wygasły. Workaround w postaci skopiowania konfigu z "zalogowanej wtyczki" działał, lecz teraz muszę się znów zalogować nowym ciachem.

Problem mam jedynie z rozpoznaniem w którym miejscu w konfigu wtyczki mam wykorzystać dane przechwycone z sesji w przeglądarce.
