### ISSUE TITLE
Tvparapobres not working

### ISSUE THREAD

**Issue by jferreira93-web** [mbebe/blomqvist#1010]
Hi.

Can't open any movie or show on tvparapobres.

When i try to Open any folder like "filmes" for example it display the movies without poster and when i try to open any movie and go to the links it gives an error. 

I hope you can fix it, thank you.

**Comment by jferreira93-web** [comment]
Log file if it helps...


2023-10-31 10:45:33.561 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/cHFgqAG4ELvMFZfZJGuPItZsuqE-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.576 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/aeflPackBJaNnE4z5aYMJcSwLz2-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.583 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/5NHohEZfL9QBdnM0bZo5XgCjKi4-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.644 T:31106   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/kEUndhFRAxO3PE186oQ7zfnT9JN-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.717 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/qVbNDmPrbnfgINfEoAMx41N7IfH-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.722 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/nNcxpjCtcawf8wQmTwnA0u1jukC-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.740 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/dvLogoBfPPGi26pgIOaPeYFfulN-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.822 T:31106   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/7GpMbVpbBSCH7eDDRKUQDMtvYX4-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.871 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/wcTFLsUEbb5xTxcVVIOkDXI1J2s-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.881 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/sMcsZ7BlOf2LDhTlfPlWb3w6lJM-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:33.896 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/so8ascE5Ee0IRIoOYL5QshFMUbQ-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:36.039 T:31117   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/cHFgqAG4ELvMFZfZJGuPItZsuqE-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:36.707 T:32534 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-10-31 10:45:36.876 T:32534   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.SSLError'>
                                                   Error Contents: HTTPSConnectionPool(host='tvparapobres.com', port=443): Max retries exceeded with url: /filmes/uma-aventura-no-jurassico/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 714, in urlopen
                                                       httplib_response = self._make_request(
                                                                          ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 403, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1053, in _validate_conn
                                                       conn.connect()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 419, in connect
                                                       self.sock = ssl_wrap_socket(
                                                                   ^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ssl.py", line 1075, in _create
                                                       self.do_handshake()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 798, in urlopen
                                                       retries = retries.increment(
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tvparapobres.com', port=443): Max retries exceeded with url: /filmes/uma-aventura-no-jurassico/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tvparapobres/main.py", line 453, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tvparapobres/main.py", line 430, in router
                                                       ListLinks(exlink, rys)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tvparapobres/main.py", line 245, in ListLinks
                                                       response = sess.get(url, headers=headers).text
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 602, in get
                                                       return self.request("GET", url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 517, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='tvparapobres.com', port=443): Max retries exceeded with url: /filmes/uma-aventura-no-jurassico/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
                                                   -->End of Python script error report<--
                                                   
2023-10-31 10:45:37.100 T:32533   error <general>: GetDirectory - Error getting plugin://plugin.video.tvparapobres/?image=https%3a%2f%2ftvparapobres.com%2fwp-content%2fuploads%2f2023%2f10%2fcHFgqAG4ELvMFZfZJGuPItZsuqE-185x278.jpg&mode=listlinks&page=1&title=Uma%20Aventura%20no%20Jur%c3%a1ssico&url=https%3a%2f%2ftvparapobres.com%2ffilmes%2fuma-aventura-no-jurassico%2f%7cUma%20Aventura%20no%20Jur%c3%a1ssico
2023-10-31 10:45:37.108 T:30771   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tvparapobres/?image=https%3a%2f%2ftvparapobres.com%2fwp-content%2fuploads%2f2023%2f10%2fcHFgqAG4ELvMFZfZJGuPItZsuqE-185x278.jpg&mode=listlinks&page=1&title=Uma%20Aventura%20no%20Jur%c3%a1ssico&url=https%3a%2f%2ftvparapobres.com%2ffilmes%2fuma-aventura-no-jurassico%2f%7cUma%20Aventura%20no%20Jur%c3%a1ssico) failed
2023-10-31 10:45:37.341 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/5NHohEZfL9QBdnM0bZo5XgCjKi4-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.350 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/cHFgqAG4ELvMFZfZJGuPItZsuqE-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.355 T:31106   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/aeflPackBJaNnE4z5aYMJcSwLz2-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.464 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/kEUndhFRAxO3PE186oQ7zfnT9JN-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.494 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/nNcxpjCtcawf8wQmTwnA0u1jukC-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.494 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/qVbNDmPrbnfgINfEoAMx41N7IfH-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.508 T:31106   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/dvLogoBfPPGi26pgIOaPeYFfulN-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.644 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/7GpMbVpbBSCH7eDDRKUQDMtvYX4-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.655 T:31106   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/so8ascE5Ee0IRIoOYL5QshFMUbQ-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.669 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/wcTFLsUEbb5xTxcVVIOkDXI1J2s-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:37.672 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/sMcsZ7BlOf2LDhTlfPlWb3w6lJM-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.570 T:31117   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/bamgEHSfZRMtFHkicCe9jgRad5P-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.582 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/rkPf3AH4DPJC1T26T8CwAjBHHvc-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.585 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/kWn5Ky57rwSi4utp5geFefLwK6M-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.587 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/5FU5m9zhA3eOfWVO4DZhpn6iwLR-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.698 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/4h4ayaBjFIMD3cO2lmyuRd9FFD7-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.708 T:31117   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/10/vuWC8NXGjooaJFZTxpxotZ0AMlR-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.723 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/csiyO6q8rR74pfgJDjwINzhoick-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.726 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/9C4lCayKoFB6hwVvgalz6rtcyOn-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.838 T:31117   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/yjzb9ojVSEw9vg5kp22ijPKXyMF-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.841 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/AbbXspMOwdvwWZgVN0nabZq03Ec-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.863 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/vk5RC1h4h5t50Opic3yo4hH8qAq-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.866 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/6AafgfifXkFS4g2xGJZIwsPQK6P-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.970 T:31117   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/rdWcoJMn7ZwXpTTChNy1OIqwit3-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.973 T:31122   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/3pwnrZayEXdJhRpWa18Woxkynn7-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.999 T:31202   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/tf5d4OWsKoftpyO1Xp07khxE5nn-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:38.999 T:31116   error <general>: CCurlFile::Stat - <https://tvparapobres.com/wp-content/uploads/2023/09/iS461mrNLZVBmPFwGdkn8CyHOio-185x278.jpg> Failed: SSL peer certificate or SSH remote key was not OK(60)
2023-10-31 10:45:53.012 T:30771    info <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.loguploader/resources/skins/default/1080i/script-loguploader-view.xml, load type: LOAD_ON_GUI_INIT
2023-10-31 10:46:50.259 T:30771    info <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.loguploader/resources/skins/default/1080i/script-loguploader-view.xml, load type: LOAD_ON_GUI_INIT
2023-10-31 10:47:28.238 T:30779    info <general>: CActiveAESink::OpenSink - initialize sink
2023-10-31 10:47:28.238 T:30779    info <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2023-10-31 10:47:28.241 T:30779    info <general>: Minimum size we need for stream: 11344 Bytes

**Comment by jferreira93-web** [comment]
Well it's working now, i guess it was the site's sorry to bother.
