### ISSUE TITLE
Fbox's domain change broke the addon

### ISSUE THREAD

**Issue by pitsi** [mbebe/blomqvist#1026]
As mentioned in the title and seen in the log below, which is from listing the movies section, the addon no longer works because of that
```
2024-01-05 11:20:24.322 T:140458713614080   ERROR: GetDirectory - Error getting plugin://plugin.video.fboxto/?image=DefaultMovies.png&mode=listmovies&movie=True&moviescount=0&page=1&title=List%20movies&url=https%3a%2f%2fwww3.fbox.to%2ffilter%3fkeyword%3d%26type%5b%5d%3dmovie
2024-01-05 11:20:24.361 T:140460299708544   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fboxto/?image=DefaultMovies.png&mode=listmovies&movie=True&moviescount=0&page=1&title=List%20movies&url=https%3a%2f%2fwww3.fbox.to%2ffilter%3fkeyword%3d%26type%5b%5d%3dmovie) failed
```
Search works though, because it defaults to the new domain, but it is the only thing that works.

The old domain is mentioned in 10 lines inside main.py, although 4 of them are commented out. I will try changing them later today when I will have some time and test it.

p.s. I also have fbox in my browser's boomarks, since like a year ago or so, and it has the new domain.

**Comment by pitsi** [comment]
Time to confirm. Changing all (non commented out) instances of `www3.fbox.to` to `fbox.to` makes the addon usable again.

**Comment by pitsi** [comment]
Does anyone have the addon installed to see if it works again, for any reason? I can not UNpatch mine or reinstall and check it.

**Comment by pitsi** [comment]
Patching the `klucze` variable with the one from fmovies makes the addon work again :)

**Comment by pitsi** [comment]
One week since the last update on fmovies and I still can't port the changes to fbox, so I guess it will remain broken :(

**Comment by pitsi** [comment]
Fbox changed its domain again, to `fboxz.to` this time. Patching the python file with the new name and the klucze variable does not help. This error comes up for movies
```
2024-06-14 16:34:29.867 T:140331311863552   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fboxz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-06-14 16:34:34.223 T:140331311863552   ERROR: Previous line repeats 2 times.
2024-06-14 16:34:34.223 T:140331311863552   ERROR: GetDirectory - Error getting plugin://plugin.video.fboxto/?image=https%3a%2f%2fstatic.fboxz.to%2fi%2f3%2f35%2f352e9aec44217a8b6394be18859821fb%40280.jpg&mode=getLinks&movie=True&moviescount=0&page=1&title=Run%20All%20Night&url=https%3a%2f%2ffboxz.to%2fmovie%2frun-all-night-dkw%7cdkw
2024-06-14 16:34:34.228 T:140332946217088   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fboxto/?image=https%3a%2f%2fstatic.fboxz.to%2fi%2f3%2f35%2f352e9aec44217a8b6394be18859821fb%40280.jpg&mode=getLinks&movie=True&moviescount=0&page=1&title=Run%20All%20Night&url=https%3a%2f%2ffboxz.to%2fmovie%2frun-all-night-dkw%7cdkw) failed
```
And this one comes up for any series
```
2024-06-14 16:34:46.069 T:140331311863552   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fboxz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-06-14 16:34:49.576 T:140331320256256   ERROR: Previous line repeats 2 times.
2024-06-14 16:34:49.576 T:140331320256256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fboxto/main.py", line 1427, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fboxto/main.py", line 1379, in router
                                                ListSeasons(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fboxto/main.py", line 1054, in ListSeasons
                                                links= getSerial(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fboxto/main.py", line 1096, in getSerial
                                                jsondata = response.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 915, in json
                                                raise RequestsJSONDecodeError(e.message)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
2024-06-14 16:34:49.759 T:140331311863552   ERROR: GetDirectory - Error getting plugin://plugin.video.fboxto/?image=https%3a%2f%2fstatic.fboxz.to%2fi%2f2%2f2e%2f2ed91db3c61a9317d9fc39e843ed4674%40280.jpg&mode=getseasons&movie=True&moviescount=0&page=1&title=The%20Boys&url=https%3a%2f%2ffboxz.to%2ftv%2fthe-boys-lx4rz%7clx4rz
2024-06-14 16:34:49.763 T:140332946217088   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fboxto/?image=https%3a%2f%2fstatic.fboxz.to%2fi%2f2%2f2e%2f2ed91db3c61a9317d9fc39e843ed4674%40280.jpg&mode=getseasons&movie=True&moviescount=0&page=1&title=The%20Boys&url=https%3a%2f%2ffboxz.to%2ftv%2fthe-boys-lx4rz%7clx4rz) failed
```
This is possibly my last comment here. I removed the addon a few days ago and I reinstalled it in order to patch it with the new domain, but it remains broken.

**Comment by pitsi** [comment]
Now that fmovies is dead and buried, can you please fix fbox? I think it will require less work than creating a new one from scratch which would scrape another popular site.

**Comment by pitsi** [comment]
Fbox shut down yesterday, so there is no reason to keep the issue open.
https://old.reddit.com/r/Piracy/comments/1f1x8fn/fboxzto_is_officially_gone/
