### ISSUE TITLE
Wtyczka Vectra nie dziala

### ISSUE THREAD

**Issue by isillo** [mbebe/blomqvist#1040]
Witam. Jak w temacie. O ile logowanie jeszcze dziala tak juz potem nie dziala.

**Comment by mbebe** [comment]
zaktualizowane

**Comment by zuzia-dev** [comment]
@mbebe działa (na szybko sprawdziłam pod Debianem z Kodi Omega), dzięki. Oby następne zmiany po ich stronie nie nastąpiły zbyt szybko.

**Comment by zuzia-dev** [comment]
@mbebe, dziś już nie działa logowanie, ani dodawanie nowego urządzenia.
```
Error Type: <class 'KeyError'>
Error Contents: 'token'
Traceback (most recent call last):
File "/home/zuzia/.kodi/addons/plugin.video.vectrapl/main.py", line 108, in <module>
  router(sys.argv[2][1:])
File "/home/zuzia/.kodi/addons/plugin.video.vectrapl/main.py", line 106, in router
  Vectra.home()
File "/home/zuzia/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 75, in home
  dod, logged = self.logowanie()
                ^^^^^^^^^^^^^^^^
File "/home/zuzia/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 171, in logowanie
                ^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zuzia/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 148, in create_app_check
  token = r.json()['token']
                ~~~~~~~~^^^^^^^^^
  KeyError: 'token'
  -->End of Python script error report<--
                                                   
error <general>: GetDirectory - Error getting plugin://plugin.video.vectrapl/
error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vectrapl/) failed
```
