### ISSUE TITLE
Fmovies 

### ISSUE THREAD

**Issue by Shoninzo** [mbebe/blomqvist#1044]
I'm getting an error message trying to use fmovies

**Comment by pitsi** [comment]
And the log output no one asked for. This is what comes up when selecting a movie, along with "links are not available" error notification
```
2024-03-01 08:22:04.226 T:140118352111360   ERROR: GetDirectory - Error getting plugin://plugin.video.fmoviesto/?image=https%3a%2f%2fstatic.fmoviesz.to%2fs280%2f7%2f75%2f75033136a7467bd11b89fd5d5069e2c6.jpg&mode=getLinks&movie=True&moviescount=0&page=1&title=Poor%20Things&url=https%3a%2f%2ffmoviesz.to%2fmovie%2fpoor-things-2w940%7c2w940
2024-03-01 08:22:04.236 T:140118514100352   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fmoviesto/?image=https%3a%2f%2fstatic.fmoviesz.to%2fs280%2f7%2f75%2f75033136a7467bd11b89fd5d5069e2c6.jpg&mode=getLinks&movie=True&moviescount=0&page=1&title=Poor%20Things&url=https%3a%2f%2ffmoviesz.to%2fmovie%2fpoor-things-2w940%7c2w940) failed
```
and this is what comes up when selecting a series
```
2024-03-01 08:24:26.756 T:140117003192064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1562, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1514, in router
                                                ListSeasons(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1025, in ListSeasons
                                                links= getSerial(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1069, in getSerial
                                                jsondata = response.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 915, in json
                                                raise RequestsJSONDecodeError(e.message)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
2024-03-01 08:24:26.947 T:140116994799360   ERROR: GetDirectory - Error getting plugin://plugin.video.fmoviesto/?image=https%3a%2f%2fstatic.fmoviesz.to%2fs280%2f3%2f36%2f367857f3848a90b28542b9eb231abd6d.jpg&mode=getseasons&movie=True&moviescount=0&page=1&title=Halo%20%5bCOLOR%20gold%5d(serie)%5b%2fCOLOR%5d&url=https%3a%2f%2ffmoviesz.to%2ftv%2fhalo-nk4mm%7cnk4mm
2024-03-01 08:24:26.953 T:140118514100352   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fmoviesto/?image=https%3a%2f%2fstatic.fmoviesz.to%2fs280%2f3%2f36%2f367857f3848a90b28542b9eb231abd6d.jpg&mode=getseasons&movie=True&moviescount=0&page=1&title=Halo%20%5bCOLOR%20gold%5d(serie)%5b%2fCOLOR%5d&url=https%3a%2f%2ffmoviesz.to%2ftv%2fhalo-nk4mm%7cnk4mm) failed
```
And the same errors show up in fbox as well. Needless to say that the sites do have links and they all work, it's only scrapping that is broken.

**Comment by pitsi** [comment]
As it seems, all the breakage happened because rabbitstream (used by fmovies and all mirrors, e.g. fbox, as well as similar sites, e.g. flixhq) changed their encryption. That is also the reason gomovies broke down.

**Comment by mbebe** [comment]
fmovies fixed and updated.
