### ISSUE TITLE
Fmovies

### ISSUE THREAD

**Issue by NotTsuu** [mbebe/blomqvist#1050]
Fmovies seems to not be working again.

Any help?

**Comment by pitsi** [comment]
And the missing logs. Vidplay and filemoon fail with this
``
2024-03-15 07:22:14.268 T:140536926938880   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-03-15 07:22:26.002 T:140537088927872   ERROR: Previous line repeats 4 times.
2024-03-15 07:22:26.002 T:140537088927872   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2863341%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Fdune-part-two-91jy0&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2Fa%2Faf%2Faf4e45a2889e30c5d82d76eacd2662b9.jpg&title=Dune%3A+Part+Two+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```
```
2024-03-15 07:23:21.397 T:140536926938880   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-03-15 07:23:21.721 T:140537088927872   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2863342%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Fdune-part-two-91jy0&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2Fa%2Faf%2Faf4e45a2889e30c5d82d76eacd2662b9.jpg&title=Dune%3A+Part+Two+-+%5BI%5D%5BCOLOR+khaki%5DFilemoon%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```
but mycloud still works. Happens on both movies and series alike, although filemoon sometimes pops the error message the series. But even when it does, the log output is the same.

**Comment by mbebe** [comment]
Can't see any problems with mycloud or vidplay.

**Comment by NotTsuu** [comment]
> Can't see any problems with mycloud or vidplay. Filemoon fixed in new version - 1.31
For the last few days I've been using it Vidplay hasn't been giving me streams but I'll check again today and see if it has been fixed.

**Comment by NotTsuu** [comment]
> Can't see any problems with mycloud or vidplay. Filemoon fixed in new version - 1.31

The last few days I have been using Vidplay, they haven't been providing me streams for some reason. But I haven't tried it today so I'll see if it has been fixed in the new version

**Comment by NotTsuu** [comment]
> > Can't see any problems with mycloud or vidplay. Filemoon fixed in new version - 1.31
> 
> The last few days I have been using Vidplay, they haven't been providing me streams for some reason. But I haven't tried it today so I'll see if it has been fixed in the new version

Just tried and it's not fixed. It keeps saying "Fmovies.to error. Check log for more information"

**Comment by pitsi** [comment]
What did I miss? Did they work again? I was sleeping :P 

24 hours after posting the logs above and although filemoon plays fine, vidplay and mycloud fail with the usual decryption error
```
2024-03-16 07:05:26.997 T:140503069112064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'int' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1598, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1450, in router
                                                PlayLink(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 731, in PlayLink
                                                stream_url = decodeVidstream(link2)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 873, in decodeVidstream
                                                srcs = (json.loads(ff)).get('result',None).get('sources',None)
                                            AttributeError: 'int' object has no attribute 'get'
                                            -->End of Python script error report<--
```
```
2024-03-16 07:07:11.169 T:140501952960256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'int' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1598, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1450, in router
                                                PlayLink(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 731, in PlayLink
                                                stream_url = decodeVidstream(link2)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 873, in decodeVidstream
                                                srcs = (json.loads(ff)).get('result',None).get('sources',None)
                                            AttributeError: 'int' object has no attribute 'get'
                                            -->End of Python script error report<--
```

**Comment by NotTsuu** [comment]
> What did I miss? Did they work again? I was sleeping :P
> 
> 24 hours after posting the logs above and although filemoon plays fine, vidplay and mycloud fail with the usual decryption error
> 
> ```
> 2024-03-16 07:05:26.997 T:140503069112064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'int' object has no attribute 'get'
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1598, in <module>
>                                                 router(sys.argv[2][1:])
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1450, in router
>                                                 PlayLink(exlink)
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 731, in PlayLink
>                                                 stream_url = decodeVidstream(link2)
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 873, in decodeVidstream
>                                                 srcs = (json.loads(ff)).get('result',None).get('sources',None)
>                                             AttributeError: 'int' object has no attribute 'get'
>                                             -->End of Python script error report<--
> ```
> 
> ```
> 2024-03-16 07:07:11.169 T:140501952960256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'int' object has no attribute 'get'
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1598, in <module>
>                                                 router(sys.argv[2][1:])
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1450, in router
>                                                 PlayLink(exlink)
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 731, in PlayLink
>                                                 stream_url = decodeVidstream(link2)
>                                               File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 873, in decodeVidstream
>                                                 srcs = (json.loads(ff)).get('result',None).get('sources',None)
>                                             AttributeError: 'int' object has no attribute 'get'
>                                             -->End of Python script error report<--
> ```

Vidplay and mycloud are still not working. Just gotta wait again I guess lol

**Comment by pitsi** [comment]
I just noticed that fmovies got the update to 1.31. How long was I sleeping? :D 
Out of curiosity, I downgraded it to 1.30 to see if mycloud would work. Sadly, it does not and it pops up the same error about decryption, so maybe yesterday was a... transition day for fmovies and nothing worked because nothing was in its final place.

**Comment by pitsi** [comment]
I think I fixed it! Changing the lines for the klucze variable and the 2 keys it gets to this makes vidplay and mycloud work again. Please test them.
```
        klucze = requests.get('https://keys4.fun/', verify=False).json()
        k1 = klucze["vidplay"]["keys"][0]
        k2 = klucze["vidplay"]["keys"][1]
```

**Comment by mbebe** [comment]
Keys are updated, should be good.

**Comment by NotTsuu** [comment]
Thanks to the both of you,! It finally works again! :)

**Comment by NotTsuu** [comment]
I'm getting the error again lol. It was working at first but now it has glitched

**Comment by pitsi** [comment]
Same issue today, but only for vidplay. Let's hope it's temporary, because mycloud works fine.
```
2024-03-28 16:52:42.517 T:139695182530304   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-03-28 16:52:42.852 T:139696715757696   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2879348%7Chttps%3A%2F%2Ffmoviesz.to%2Ftv%2Finvincible-8xj3q%2F2-7&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2F0%2F05%2F055769f88d7351340069b51e0cf8538d.jpg&title=Episode+7+%28S02E07%29+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```

**Comment by pitsi** [comment]
12+ hours later and the vidplay issue is still there...

**Comment by NotTsuu** [comment]
> 12+ hours later and the vidplay issue is still present...

MyCloud is now not working alongside vidplay. 

Man I just want to watch the walking dead haha.

Mycloud only stopped working when I updated it so don't update for now.

**Comment by pitsi** [comment]
I can't confirm that, mycloud works fine on my end. I tested it again just now.
And truth be told, filemon is the most stable of the three, since ever.

**Comment by NotTsuu** [comment]
> I can't confirm that, mycloud works fine on my end. I tested it again just now. And truth be told, filemon is the most stable of the three, since ever.

Filemoon never shows up for me when I'm watching the walking dead

**Comment by pitsi** [comment]
Then maybe filemoon is not available (for that episode) from the page itself Just open a browser and check it.

**Comment by NotTsuu** [comment]
> Then maybe filemoon is not available (for that episode) from the page itself. Just open a browser and check it.

Alrighy

**Comment by pitsi** [comment]
I don't know ehy you closed the issue, but ~3 days later and vidplay is still broken on my end.
```
2024-03-31 12:36:09.972 T:140146042566400   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-03-31 12:36:17.621 T:140147638061184   ERROR: Previous line repeats 4 times.
2024-03-31 12:36:17.622 T:140147638061184   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2863341%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Fdune-part-two-91jy0&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2Fa%2Faf%2Faf4e45a2889e30c5d82d76eacd2662b9.jpg&title=Dune%3A+Part+Two+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```

**Comment by NotTsuu** [comment]
> I don't know why you closed the issue, but ~3 days later and vidplay is still broken on my end.
> 
> ```
> 2024-03-31 12:36:09.972 T:140146042566400   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>                                               InsecureRequestWarning,
> 2024-03-31 12:36:17.621 T:140147638061184   ERROR: Previous line repeats 4 times.
> 2024-03-31 12:36:17.622 T:140147638061184   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2863341%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Fdune-part-two-91jy0&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2Fa%2Faf%2Faf4e45a2889e30c5d82d76eacd2662b9.jpg&title=Dune%3A+Part+Two+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
> ```

I'm pretty sure he updated it today but still doesn't work

**Comment by pitsi** [comment]
Please do not open new issues about vidplay alone. I was about to comment there :P

**Comment by mbebe** [comment]
fmovies fixed. Please update.

**Comment by pitsi** [comment]
I can confirm vidplay works now! Wel done :)

**Comment by NotTsuu** [comment]
> I can confirm vidplay works now! Wel done :)

Not working for me again! Omg this is pretty overwhelming haha

**Comment by pitsi** [comment]
If the issue is not fixed, why do you close it?

I am a bit sick since Monday so I did not have time to open github and post logs etc, but here is one that does not help at all
```
2024-04-10 06:45:48.858 T:140175585388288   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-04-10 06:45:57.062 T:140177195706496   ERROR: Previous line repeats 5 times.
2024-04-10 06:45:57.062 T:140177195706496 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2024-04-10 06:45:57.417 T:140175602173696   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'c8365730d4.nl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-04-10 06:45:57.808 T:140177195706496   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2889621%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Fkung-fu-panda-4-nwk5j&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2F1%2F12%2Fb9771929bae760333af803096fdd9276.jpg&title=Kung+Fu+Panda+4+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
2024-04-10 06:46:00.518 T:140175585388288   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-04-10 06:46:02.389 T:140177195706496   ERROR: Previous line repeats 1 times.
2024-04-10 06:46:02.389 T:140177195706496 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2024-04-10 06:46:02.714 T:140175585388288   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mcloud.bz'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2024-04-10 06:46:03.066 T:140177195706496   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2889620%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Fkung-fu-panda-4-nwk5j&movie=True&image=https%3A%2F%2Fstatic.fmoviesz.to%2Fi%2F1%2F12%2Fb9771929bae760333af803096fdd9276.jpg&title=Kung+Fu+Panda+4+-+%5BI%5D%5BCOLOR+khaki%5DMyCloud%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```
