### ISSUE TITLE
playing movies on lookmovie addon not working

### ISSUE THREAD

**Issue by unity-one** [mbebe/blomqvist#1084]
when trying to play any movie from 'Movies' section plugin returns 'LookMovie error'.

playing titles from 'TV Shows' section works now without captcha verification.

**Comment by pitsi** [comment]
I started using lookmovie last week, because it has a season of a series I watch which no other addon has.
Anyway, here is the (important part of the) log when selecting a movie, on which the addon really fails.
```
2024-11-04 12:08:13.565 T:866     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: unsupported operand type(s) for +: 'NoneType' and 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.lookmovietomb/main.py", line 752, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.lookmovietomb/main.py", line 655, in router
                                                       ListLinks(exlink, rys)
                                                     File "/storage/.kodi/addons/plugin.video.lookmovietomb/main.py", line 591, in ListLinks
                                                       add_item(vid_source+'|'+urlk, '[B]'+title + '[/B]', ima, 'playvid',fanart=FANART, folder=False, IsPlayable=True, infoLabels={'plot':plot,'year':year})
                                                   TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
                                                   -->End of Python script error report<--

```

**Comment by pitsi** [comment]
Good news everyone! A friend of mine saw the issue and suggested a fix.

Changing line 590 of main.py from this
`vid_source = list((html.get('streams', None)).values())[2]`
to this
`vid_source = [x for x in list((html.get('streams', None)).values()) if x][0]`
restores the addon's functionality for movies!

If anyone can do a pull request for it, it will be good for everyone.

**Comment by amerr97** [comment]
This is the best addon, and if we could somehow bypass the image verification process it would become new fmovies

**Comment by amerr97** [comment]
> Good news everyone! A friend of mine saw the issue and suggested a fix.
> 
> Changing line 590 of main.py from this `vid_source = list((html.get('streams', None)).values())[2]` to this `vid_source = [x for x in list((html.get('streams', None)).values()) if x][0]` restores the addon's functionality for movies!
> 
> If anyone can do a pull request for it, it will be good for everyone.

Hmm.. when I replace the 590 line of code, i can't get the addon to install - invalid structure

**Comment by pitsi** [comment]
No idea sorry. Maybe it needs indentation, because python is very picky about that. Make sure it is as many characters "in" as the previous one. Here it lines up with `html = blablabla` above and `add_item` below.

**Comment by amerr97** [comment]
> No idea sorry. Maybe it needs indentation, because python is very picky about that. Make sure it is as many characters "in" as the previous one. Here it lines up with `html = blablabla` above and `add_item` below.

I've been testing a little on windows, when I change the main.py of the addon in data roaming (pre installed) then the movies work ok.  If I  zip the folder, and try to install -it's not working.

**Comment by amerr97** [comment]
I have managed to make it installable from zip. I have made a pull request for it to be updated. 
You can find the updated .zip for installation on my github-mbebe-zips-lookmovie- 0.7 version.

https://github.com/amerr97/blomqvist/tree/master/zips/plugin.video.lookmovietomb



@pitsi thank you

**Comment by pitsi** [comment]
The credits must go to my friend who actually fixed it, not to me who posted a log and then tested the fix. I did 10% of the work and he did the remaining 90%.

Having said that, I wish someone like @amerr97 had shown the same interest with pull requests etc when I was testing and fixing fbox by myself.

**Comment by unity-one** [comment]
just updated the plugin using the provided .zip file and it works now. thank you so much guys...

**Comment by def903** [comment]
I put the 0.7 version zip file on a thumb drive and used the 'Install from Zip' function in Kodi.  After almost giving up hope of Lookmovie ever working again any time soon, it fixed the problem for me, too. It was very easy to do. Thanks.

**Comment by defivlad** [comment]
can anyone guide me on how to install this update?

Im running Xenon Build on KODI and using this add on. I managed to download the 0.7 zip file from @amerr97 and when i try to install from zip. Kodi just crashes. 

I assume I am doing it wrong.

**Comment by def903** [comment]
I'm not an expert. I use Xenon build, too. The solution described still works for me. I have not had any problem with Kodi and LookMovie since I installed the fix.

**Comment by amerr97** [comment]
Maybe since someone approved the pull request you can try to auto update the addon. 
We should add year 2025 to the next update, and fix the descriptions. 
But for now the addon works perfectly

**Comment by defivlad** [comment]
Ok so I have tested several things:

I installed KODI + XENON + MBEBE on my windows PC and then ran the  0.7 zip file and it installed the update, got the add-on updated popup and movies work great now! 

So I went back to the firestick and tried again and again KODI crashes after I try to install the zip.

So I fully deleted KODI+XENON off teh firestick and re-installed fresh. Then added the addon from mbebe again.
First I tried to play a movie and got the normal error.
So then tried the same file 0.7 zip file  that worked on my PC and again it crashes KODI.

Could it be it that it doesn't install from firestick @amerr97 ?

Thanks everyone for helping out.

**Comment by amerr97** [comment]
> Ok so I have tested several things:
> 
> I installed KODI + XENON + MBEBE on my windows PC and then ran the 0.7 zip file and it installed the update, got the add-on updated popup and movies work great now!
> 
> So I went back to the firestick and tried again and again KODI crashes after I try to install the zip.
> 
> So I fully deleted KODI+XENON off teh firestick and re-installed fresh. Then added the addon from mbebe again. First I tried to play a movie and got the normal error. So then tried the same file 0.7 zip file that worked on my PC and again it crashes KODI.
> 
> Could it be it that it doesn't install from firestick [@amerr97](https://github.com/amerr97) ?
> 
> Thanks everyone for helping out.

Try installing the membebe one that gets the normal error.
Then find the main.py of lookmovie addon on your firestick ( installed one) and then copy our fixed  version code from main.py into your preinstalled main.py code and save it.

I hope you understood.

**Comment by defivlad** [comment]
yeah that would be easy if I could see the firestick as a device on the PC via USB..i will play around with this solution thanks

**Comment by defivlad** [comment]
Thanks for all the help. I finally managed to get it to update and now it works great.

**Comment by amerr97** [comment]
Its broken again

Index Error

`2025-04-12 23:00:23.872 T:31481    info <general>: Skipped 2 duplicate messages..
2025-04-12 23:00:23.872 T:31481   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.lookmovietomb/main.py", line 752, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.lookmovietomb/main.py", line 653, in router
                                                       ListSerial(exlink,rys)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.lookmovietomb/main.py", line 348, in ListSerial
                                                       dt = dt[0].replace('\\"',"'").replace('\n','').replace('   ', '')
                                                            ~~^^^
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--`

I assume the website indexing structure changed since they implemented pay to watch in HD

**Comment by kolekan** [comment]
In main.py find and replace all instances of
`>Thread Defence`
to
`g-recaptcha`

**Comment by defivlad** [comment]
so if opened up the zip file of @amerr97 latest zip and edited the main.py and rezipped as a new version it would update kodi from the zip and work?

**Comment by amerr97** [comment]
> so if opened up the zip file of [@amerr97](https://github.com/amerr97) latest zip and edited the main.py and rezipped as a new version it would update kodi from the zip and work?

We have to update the file with @kolekan suggestion to fix the addon. it wasnt working the other day

**Comment by defivlad** [comment]
yeah what i did now is I extracted the zip you made and edited the main.py

I will see if it will let me update from zip using Kodi now when I try .

**Comment by defivlad** [comment]
Ok it worked with the @kolekan suggestions. Thank you.

Basically download the latest zip made by @amerr97 
Extract the zip
Modify main.py
Zip again and call it 0.8
Go to Kodi and install from zip again.

Works!

**Comment by amerr97** [comment]
I will post a updated zip tomorrow for other users.

**Comment by amerr97** [comment]
Guys thanks to @kolekan i'm posting a link for 0.8 fix 
+ I have added year 2024, and 2025 in filter list 
just download and install/ update

https://github.com/amerr97/blomqvist/tree/master/zips/plugin.video.lookmovietomb

**Comment by pitsi** [comment]
Is the patched version of lookmovie the only addon "from" this repo that still works? It has been a year with literally zero updates on any of the addons, so I want to remove the repo completely.

**Comment by defivlad** [comment]
I just loaded the addon on a new Kodi setup and it worked without any patches.

-------- Original Message --------

**Comment by pitsi** [comment]
What version did you use and from where?

**Comment by defivlad** [comment]
Literally a new xenon free build. addon was included and working. Looks like v0.8

-------- Original Message --------

**Comment by amerr97** [comment]
I just hope our friend mbebe is just busy, and doing good.

**Comment by pitsi** [comment]
@defivlad 
So a newer (patched) version and from another repo...

@amerr97 
I hope so too :)

**Comment by bl4ckpr0xy** [comment]
Whenever I try to use the search bar, nothing returns.. doesn't matter what I search, the results are always empty. What's up?

**Comment by pitsi** [comment]
Asking the obvious, although I have not used the addon for months: which version do you have installed and where did you install it from?

**Comment by amerr97** [comment]
> Whenever I try to use the search bar, nothing returns.. doesn't matter what I search, the results are always empty. What's up?

For me its working fine. Download my version then update from zip

**Comment by pitsi** [comment]
@amerr97 
Do you accept bug reports for your fork of the addon? And if yes, where can I open them.
Thank you in advance.

**Comment by amerr97** [comment]
> [@amerr97](https://github.com/amerr97) Do you accept bug reports for your fork of the addon? And if yes, where can I open them. Thank you in advance.

Well, i tired to make a build so we could all autoupdate untill mbebe comes back, but i dont understand the kodi principle to make it work 🤷. Maybe its better to keep it here since we have more reach. Other users were the brain to keeping this addon working...  

I dont mind if you post bugs, if we can all make it better why not. I wish we could somehow swap the Captcha metod, the image box selecing is not practical when the tv is far away.  All ideas are more wellcomed
