### ISSUE TITLE
Sportowa

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#185]
sport365 nie otwiera żadnych linków tak było wczoraj, chyba, że tylko u mnie.
Pozdrawiam

**Comment by leonzawodowiec12** [comment]
U mnie to samo

**Comment by Smerd5** [comment]
Ja mam ten sam problem juz od kilku tygodni

**Comment by Contralege** [comment]
W dalszym ciągu nie działa sportowa tv sport365

**Comment by Smerd5** [comment]
Za jakakolwiek  informacje bedziemy bardzo wdzieczni, czy da sie cos naprawic czy tez nie, a tak to nadzieje jest ciagle w rekach mbebe.?

**Comment by kashkash18** [comment]
Na chwilę obecną zainstaluj to repozytorium a z niego wtyczkę 1x2
[repository.Maniac.zip](https://github.com/mbebe/blomqvist/files/3962296/repository.Maniac.zip)

**Comment by Smerd5** [comment]
Bardzo dziekuje za informacje.

**Comment by kisiel999** [comment]
Taki jest log błędu u mnie, jak próbuję otworzyć stream we wtyczce Sport365:
2019-12-14 12:26:57.877 T:1036   ERROR: NEWADDON Unknown Video Info Key "url"
2019-12-14 12:27:08.372 T:7528   ERROR: Previous line repeats 110 times.
2019-12-14 12:27:08.372 T:7528  NOTICE: RET IS: {u'k7': u'HyLpEJioQ5wf3Pdbj4SbIW5a8uRLbfFj', u'i7': u'\x00'}
2019-12-14 12:27:08.621 T:7528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Invalid Initial Value (IV), must be a multiple of 8 bytes
                                            Traceback (most recent call last):
                                              File "C:\Users\hahaha\AppData\Roaming\Kodi\addons\plugin.video.sport365.live\main.py", line 449, in <module>
                                                get_streams_play(params)
                                              File "C:\Users\hahaha\AppData\Roaming\Kodi\addons\plugin.video.sport365.live\main.py", line 70, in get_streams_play
                                                frames = mod.getStreams(ex_link)
                                              File "C:\Users\hahaha\AppData\Roaming\Kodi\addons\plugin.video.sport365.live\sport365.py", line 117, in getStreams
                                                decrypter = pyDes.triple_des(str(key), pyDes.CBC, str(info))
                                              File "C:\Users\hahaha\AppData\Roaming\Kodi\addons\plugin.video.sport365.live\resources\lib\pyDes.py", line 709, in __init__
                                                _baseDes.__init__(self, mode, IV, pad, padmode)
                                              File "C:\Users\hahaha\AppData\Roaming\Kodi\addons\plugin.video.sport365.live\resources\lib\pyDes.py", line 118, in __init__
                                                raise ValueError("Invalid Initial Value (IV), must be a multiple of " + str(self.block_size) + " bytes")
                                            ValueError: Invalid Initial Value (IV), must be a multiple of 8 bytes
                                            -->End of Python script error report<--
2019-12-14 12:27:08.671 T:1832   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.live%2fen%2flinks%2f5df4a8040d8aa245106146%2f1&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d12%3a00%3a%20%5bCOLOR%20blue%5dFC%20Academica%20Clinceni%20-%20FC%20Botosani%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20%2f%20Romania%20-%20Liga%201&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d12%3a00%3a%20%5bCOLOR%20blue%5dFC%20Academica%20Clinceni%20-%20FC%20Botosani%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20%2f%20Romania%20-%20Liga%201%27%7d
2019-12-14 12:27:08.680 T:5564   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.live%2fen%2flinks%2f5df4a8040d8aa245106146%2f1&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d12%3a00%3a%20%5bCOLOR%20blue%5dFC%20Academica%20Clinceni%20-%20FC%20Botosani%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20%2f%20Romania%20-%20Liga%201&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d12%3a00%3a%20%5bCOLOR%20blue%5dFC%20Academica%20Clinceni%20-%20FC%20Botosani%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20%2f%20Romania%20-%20Liga%201%27%7d) failed

**Comment by kashkash18** [comment]
@kisiel999  A czy to wtyczka od Mbebe plugin.video.sport365.live ??

**Comment by kisiel999** [comment]
Tak, od Mbebe. 1x2 ściągałem, ale tam mam innego buga.

**Comment by mbebe** [comment]
Tak? A gdzie u mnie jest wtyczka plugin.video.sport365.live?

**Comment by Smerd5** [comment]
Tak to prawda nie ma u Ciebie wtyczki sport365,ale ta wtyczka jest czescia wtyczki sportowa tv, wiec moze grzecznosciowo dalo by sie cos z nia zrobic tak w upominku swiatecznym dla wszystkich fanow dobrego sportu,bo 365 zawsze bylo zrodlem najlepszych transmisji sportowych w tv z calego swiata w tym z olski rowniez. W imieniu wszystkich bardzo dziekuje.

**Comment by kashkash18** [comment]
By cos z tym zrobić to trzeba mieć te wtyczkę a w repo mbebe jej nie ma. Ogólnie Sport365 uzbroił się w zabezpieczenia które ciągle się zmieniają. S365 nie działa w Sportowej , 1x2 i u Bugatisho. Najszybciej rądza sobie z tym twórcy wtyczki 1x2 i tam bym czekał na aktualizacje. Ale też wątpię by pojawiła się przed świętami.
