### ISSUE TITLE
[REQUEST] Ścieżka do wyszukiwania w poszczególnych wtyczkach

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#190]
Tytułem wstępu.
Skórka Arctic Zephyr 2 ma wyszukiwanie globalne, z możliwością wykorzystywania własnych wtyczek - czyli np. wyszukiwania jednocześnie zadanej frazy w kilku wtyczkach (np w Netflix, Fanfilm, i innych).
Więcej tu:
https://forum.kodi.tv/showthread.php?pid=2849712#pid2849712

Dla FanFilm sprawa jest prosta:
plugin://plugin.video.fanfilm/?action=movieSearchterm&amp;name=

Wtyczki od mbebe nie są do końca do z tym kompatybilne, żeby nie powiedzieć - wcale.
Dla wtyczki cda.pl zrobiłem poprawkę - plik main.py - linia 532
```
elif mode[0] =='SzukajNowe':
    d = args.get('d', None) #pobranie argumentu d - czyli tekstu do wyszukiwania
    if d is None: #gdy nie był podany wywołaj klawiaturę
        d = xbmcgui.Dialog().input('Szukaj, podaj tytu\xc5\x82', type=xbmcgui.INPUT_ALPHANUM)
    if d[0]:
        HistoryAdd(d[0])
        ex_link='https://www.cda.pl/video/show/'+d[0].replace(' ','_')
        cdaSearch(ex_link)
```

Wywołanie następuje wtedy komendą:
plugin://plugin.video.cdapl/?mode=SzukajNowe&d=

Podobnie można to zrobić we wtyczce cdax, alltube,
Natomiast we wtyczce vodgo.pl i 3filmy - gdzie parametry są inaczej przekazywane mam problem... nie potrafię przekazać treści do wyszukiwania itp itd... po prostu nie ogarniam :)
@mbebe - poradzisz?
A może niezawodny @xulek

BTW - a może dla wtyczek działających po prostu systematycznie dodać się tę możliwość? Ułatwiłoby to korzystanie w tej i innych skórkach z tak fajnej funkcji...

**Comment by xulek** [comment]
Jak na razie z tego co widzę to w vodgo.pl jest babol w wyszukiwaniu 

`		params = (
			('query', 'dom z'),
		)`

Zabite na stałe w kodzie

**Comment by mbebe** [comment]
```
def ListSearch():
	params = dict(parse_qsl(sys.argv[2][1:]))
	d=params.get('d', None)

	if d is None:
		d = xbmcgui.Dialog().input(u'Szukaj...', type=xbmcgui.INPUT_ALPHANUM)
	if d:
		kukz = addon.getSetting('kukiz')
		headers = {
			'user-agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0',
			'Cookie':kukz,

		}
		
		params = (
			('query', d),
		)
		
		html = sess.get('https://vodgo.pl/search', headers=headers, params=params).text
		links = parseDOM(html, 'div', attrs={'class':'col-12 row mt-1'})
		if links:
			for link in links:
				if '>zablokowany<' in link:
					continue
				href=parseDOM(link,'a',ret='href')[0]

				img=parseDOM(link,'img',ret='src')[0]
				href = 'https://vodgo.pl'+href
				img = 'https://vodgo.pl'+img
				tytpl = parseDOM(link, 'div', attrs={'class':''})[0]
				tytang = parseDOM(link, 'div', attrs={'class':'text-muted'})[0]
				tyt = tytpl+' / '+tytang
				fold=False
				mud='play3Filmy'
				if '/serial/' in href:
					fold=True
					mud='listSerial'
					tyt = tyt + '  [COLOR violet][B](serial)[/COLOR][/B]'
					href = PLchar(href)
				else:
					
					tyt = tyt + '  [COLOR violet][B](film)[/COLOR][/B]'
					href = PLchar(href)+'|'+PLchar(tyt)
				add_item(name=PLchar(tyt), url=href, mode=mud, image=img, folder=fold, infoLabels=False)
			xbmcplugin.endOfDirectory(addon_handle)	
		else:
			xbmcgui.Dialog().notification('[B]Błąd[/B]', 'Nic nie znaleziono.',xbmcgui.NOTIFICATION_INFO, 6000)```

po tych poprawkach sciezka do wyszukania:

plugin://plugin.video.vodgopl/?mode=listSearch&d=

**Comment by notoco** [comment]
khm... a w updacie się to pojawi? może nie od razu dziś wieczorem we wszystkich... :) ale tak po kolei jakby się pokazywało by było super...  3filmy, vodgo, cda, cdax, alltube, segos (które i tak ledwo co działa - ale to z winy strony) i potem po kolei uwzględniając te które jeszcze działają...
To nie tylko do tej skórki może być przydatne - ale w dodatkach w stylu openmeta także...
BTW - blisko byłem....
BTW2 - naprawdę polecam skórkę Arctic Zephyr 2 - duże możliwości konfiguracji, świetny wygląd, ascetyczny mnimalizm...

**Comment by notoco** [comment]
Potwierdzam - działa na vodgo.pl, 3 filmy - na innych nie sprawdzałem - w sumie alltube, cdax, i te 2 mi wystarczą...

**Comment by notoco** [comment]
BTW - coś mi się pomieszało - w cdax nie zrobiłem tego... wczoraj w nocy próbowałem w kilku wtyczkach i coś mi się... pomieszało chyba...

**Comment by notoco** [comment]
Ok - dyskusja z samym sobą :)
dla cdax:
```
	def search(mode,ex_link):
		from history import SearchHistory
		mymode=mode.split(':')[-1] if ':' in mode else ''
		if mymode == '':
			addDir('[COLOR lightgreen]Nowe Szukanie[/COLOR]',ex_link='',mode='search:new')
			history = SearchHistory().HistoryLoad()
			if not history == ['']:
				for entry in history:
					contextmenu = []
					contextmenu.append(('Usun', 'XBMC.Container.Refresh(%s)'% build_url({'mode': 'search:delOne', 'ex_link' : entry})),)
					contextmenu.append(('Usun całą historię', 'XBMC.Container.Update(%s)' % build_url({'mode': 'search:delAll'})),)
					addDir(name=entry, ex_link=entry.replace(' ','+'), mode='search:new', fanart=None, contextmenu=contextmenu)
			xbmcplugin.endOfDirectory(addon_handle)
		elif mymode =='new':
			if not ex_link:
				params = dict(urlparse.parse_qsl(sys.argv[2].replace('?','')))
				search_entry = params.get('d', None)

				if search_entry is None:
					search_entry = dialog.input('Szukaj, Podaj tytuł filmu', type=xbmcgui.INPUT_ALPHANUM)
				if search_entry: SearchHistory().HistoryAdd(search_entry)
				else: quit()
			else:
				search_entry = ex_link
			if search_entry:
				from cdaxDef import cdaxOnline2
				out,outCDAX,pageCDX = cdaxOnline2().getContentCDAXsearch('https://cda-tv.pl/?s='+search_entry.replace(' ','+'))
				pageCNTmode='__page__:contentsearch'
				if pageCDX[1]:
					addLinkItem(name='[COLOR blue]<< poprzednia strona <<[/COLOR]', url=pageCDX[1], mode=pageCNTmode, IsPlayable=False)
				for f in out: addLinkItem(name=f.get('title'), url=f.get('href'), mode='playOpenKatalog', iconimage=f.get('img'), infoLabels=f, IsPlayable=True)
				for f in outCDAX: addDir(f.get('title'),f.get('href'), page=1, mode='seriale_seasons',iconImage=f.get('img'), infoLabels=f)
				if pageCDX[0]:
					addLinkItem(name='[COLOR blue]>> następna strona >>[/COLOR]', url=pageCDX[0], mode=pageCNTmode, IsPlayable=False)
			xbmcplugin.endOfDirectory(addon_handle)
		elif mymode =='delOne':
			SearchHistory().HistoryDel(ex_link)
			xbmc.executebuiltin('XBMC.Container.Refresh(%s)'%  build_url({'mode': 'search'}))
		elif mymode =='delAll':
			SearchHistory().HistoryClear()
			xbmc.executebuiltin('XBMC.Container.Refresh(%s)'%  build_url({'mode': 'search'}))
		#xbmcplugin.setContent(addon_handle, 'movies')
```

**Comment by notoco** [comment]
z alltube jest błąd - wywala jakby niewłaściwą zawartość i skórka sobie nie radzi...

**Comment by notoco** [comment]
[plugin.video.cdaxpl.zip](https://github.com/mbebe/blomqvist/files/3812808/plugin.video.cdaxpl.zip)
plugin://plugin.video.cdaxpl/?mode=search:new&d=
[plugin.video.otubepl.zip](https://github.com/mbebe/blomqvist/files/3812809/plugin.video.otubepl.zip)
plugin://plugin.video.vodgopl/?mode=listSearch&d=
[plugin.video.vodgopl.zip](https://github.com/mbebe/blomqvist/files/3812810/plugin.video.vodgopl.zip)
plugin://plugin.video.vodgopl/?mode=listSearch&d=
[plugin.video.3filmy.zip](https://github.com/mbebe/blomqvist/files/3812811/plugin.video.3filmy.zip)
plugin://plugin.video.3filmy/?mode=listSearch&d=
Poprawione wersje 4 dodatków z których korzystam.
Cda zbiera jednak za dużo śmieci, alltube nie udało mi się zrobić.. Niby wyszukuje, ale nie pokazuje na widgecie.
Co zyskałem - jeden raz wpisuję tytuł filmu, i przeszukuje mi 6 wtyczek jednocześnie - Netflix, FanFilm, cdax,otube,3filmy,vodgo. Ładnie wyświetla na ekranie...
I zrzuty (2 - bo łącznie są 4 widgety - a skórka pokazuje tylko 2 na ekranie, potem trzeba przewinąć)
![screenshot001](https://user-images.githubusercontent.com/36659110/68274123-89664080-0068-11ea-9386-47e2aa434604.png)
![screenshot002](https://user-images.githubusercontent.com/36659110/68274124-89664080-0068-11ea-9969-8d20bbb3119d.png)

BTW - przy Fanfilm trzeba w opcjach wyłączyć okno ładowania w opcjach, bo samo się nie zamyka

**Comment by notoco** [comment]
To jakby kogoś interesowało - poprawka dla wtyczki HBO z repo kwp.
```
def SEARCH():
	keyb=params.get('d', None)
	if keyb is None:
		keyb = xbmc.Keyboard(search_string, 'Wyszukiwanie filmów, seriali ...')
		keyb.doModal()
		searchText = ''
		searchText = urllib.quote_plus(keyb.getText())
	else:
		searchText = ''
		searchText = urllib.quote_plus(keyb)
	if searchText == "":
		addDir('Wróć - nie ma wyników pasujących do wyszukiwania','','','',md+'DefaultFolderBack.png')
	else:
		#Zapis ostatniego zapytania
		__settings__.setSetting('lastsearch', searchText)
		#Wyszukaj
		req = urllib2.Request('https://plapi.hbogo.eu/v7/Search/Json/POL/ANMO/'+searchText.decode('utf-8', 'ignore').encode('utf-8', 'ignore')+'/0/0/0/0/0/3', None, loggedin_headers)
		opener = urllib2.build_opener()
		f = opener.open(req)
		jsonrsp = json.loads(f.read())        

		try:
			if jsonrsp['ErrorMessage']:
				xbmcgui.Dialog().ok('Błąd', jsonrsp['ErrorMessage'])
		except:
			pass

		br=0
		for index in range(0, len(jsonrsp['Container'][0]['Contents']['Items'])):
			allowplay = jsonrsp['Container'][0]['Contents']['Items'][index].get( 'AllowPlay', None )
			if (jsonrsp['Container'][0]['Contents']['Items'][index]['ContentType'] == 1 or jsonrsp['Container'][0]['Contents']['Items'][index]['ContentType'] == 7): #1,7=MOVIE/EXTRAS, 2=SERIES(serial), 3=SERIES(episode)
				#Film
				addLink(jsonrsp['Container'][0]['Contents']['Items'][index]['ObjectUrl'],'',jsonrsp['Container'][0]['Contents']['Items'][index]['AgeRating'],jsonrsp['Container'][0]['Contents']['Items'][index]['ImdbRate'],jsonrsp['Container'][0]['Contents']['Items'][index]['BackgroundUrl'],[jsonrsp['Container'][0]['Contents']['Items'][index]['Cast'].split(', ')][0],jsonrsp['Container'][0]['Contents']['Items'][index]['Director'],jsonrsp['Container'][0]['Contents']['Items'][index]['Writer'],jsonrsp['Container'][0]['Contents']['Items'][index]['Duration'],jsonrsp['Container'][0]['Contents']['Items'][index]['Genre'],jsonrsp['Container'][0]['Contents']['Items'][index]['Name'].encode('utf-8', 'ignore'),jsonrsp['Container'][0]['Contents']['Items'][index]['OriginalName'],jsonrsp['Container'][0]['Contents']['Items'][index]['ProductionYear'],5,'',True)
			elif jsonrsp['Container'][0]['Contents']['Items'][index]['ContentType'] == 3:
				#Odcinek
				addLink(jsonrsp['Container'][0]['Contents']['Items'][index]['ObjectUrl'],'',jsonrsp['Container'][0]['Contents']['Items'][index]['AgeRating'],jsonrsp['Container'][0]['Contents']['Items'][index]['ImdbRate'],jsonrsp['Container'][0]['Contents']['Items'][index]['BackgroundUrl'],[jsonrsp['Container'][0]['Contents']['Items'][index]['Cast'].split(', ')][0],jsonrsp['Container'][0]['Contents']['Items'][index]['Director'],jsonrsp['Container'][0]['Contents']['Items'][index]['Writer'],jsonrsp['Container'][0]['Contents']['Items'][index]['Duration'],jsonrsp['Container'][0]['Contents']['Items'][index]['Genre'],jsonrsp['Container'][0]['Contents']['Items'][index]['SeriesName'].encode('utf-8', 'ignore')+' '+jsonrsp['Container'][0]['Contents']['Items'][index]['Name'].encode('utf-8', 'ignore'),jsonrsp['Container'][0]['Contents']['Items'][index]['OriginalName'],jsonrsp['Container'][0]['Contents']['Items'][index]['ProductionYear'],5,'',True)
			else:
				#Seria
				addDir(jsonrsp['Container'][0]['Contents']['Items'][index]['Name'].encode('utf-8', 'ignore'),jsonrsp['Container'][0]['Contents']['Items'][index]['ObjectUrl'],'',2,jsonrsp['Container'][0]['Contents']['Items'][index]['BackgroundUrl'])
			br=br+1
		if br==0:
			addDir('Wróć - nie ma wyników pasujących do wyszukiwania','','','',md+'DefaultFolderBack.png')
```

**Comment by notoco** [comment]
Dla niektórych wtyczek udało mi się znaleźć ścieżkę bez poprawek skryptu (w sumie tam, gdzie działa historia wyszukiwania jest to możliwe)
Alltube (w wyszukiwaniu brak grafik, daje tylko tekst)
plugin://plugin.video.alltube.tv/?page=1&amp;mode=searchItems&amp;ex_link=
cda-hd:
plugin://plugin.video.cdahd/?page=1&amp;mode=ListFS&amp;ex_link=

**Comment by oliwer12345** [comment]
Moze ktos to wyjasni w prosty sposob dla laika takiego jak ja jak to zrobic no boxsie kodi

**Comment by notoco** [comment]
Ale przecież masz wszystko wyjaśnione
1. masz nazwę skórki i link do poradnika na forum po angielsku (skórka i tak jest po angielsku)
2. masz podane odpowiednie linki
3. jak już kompletnie nie ogarniesz - to zerknij tutaj: https://forum.kodiwpigulce.pl/showthread.php?tid=2231&pid=16699#pid16699 - ale to praktycznie to samo co tutaj, jedynie bez zbędnej dyskusji

**Comment by oliwer12345** [comment]
DZIEKUJE BEDE PROBOWAL

**Comment by timtumturutumtum** [comment]
@notoco - skin ciekawy, dzięki za opis jak dodać wyszukiwarki, spisuje się to całkiem dobrze:)
pytanie - wiesz może jak zmusić to cudo do  wyświtalania ikon lub miniatur dodając w _**customize home menu -> 'filmy' -> widgets**_ "gatunki"? w estuary mod jest to świetnie rozwiązane.

**Comment by notoco** [comment]
Zerknę w weekend ale u mnie chyba to działa...

**Comment by notoco** [comment]
A już mam - na boxie tego nie mam bo tam używam własnego konfigu, ale na kompie używam do testów domyślnych skrótów - ustaw aspect na square lub small square

**Comment by timtumturutumtum** [comment]
@notoco - dzięki, jesteś wielki!
jeszcze tylko aktualna godzina i godzina zakończenia wyświtlając menu w trakcie oglądania IPTV/PVR i zmieniam estuary mod2 na AZ2 na stałe :)

Może wiesz jak to zrobić?

**Comment by notoco** [comment]
W oryginalnej skórce tego nie ma. Natomiast w mojej modyfikacji jest to na liście do zrobienia. Jak zrobię, to pojawi się u mnie, a gdzieś wrzucę info o modyfikacji.

**Comment by notoco** [comment]
W mojej modyfikacji już to jest. Potem podam co i jak. To zmiana w 2 miejscach

**Comment by timtumturutumtum** [comment]
Testowałem, na PC chodzi super, na boksie wywala sie kodi przy ładowaniu skórki i już nie wstaje,

2019-11-09 07 51 42.049 T 3905618816 ERROR Traceback (most recent call last): 2019-11-09 07 51 42.049 T 3905618816 ERROR File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 97, in buildMenu 2019-11-09 07 51 42.066 T 3905618816 ERROR self.writexml( profilelist, mainmenuID, groups, numLevels, buildMode, progress, options, minitems ) 2019-11-09 07 51 42.066 T 3905618816 ERROR File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 504, in writexml 2019-11-09 07 51 42.067 T 3905618816 ERROR submenudata = DATA._get_shortcuts( submenu, submenuDefaultID, True, profile[0] ) 2019-11-09 07 51 42.067 T 3905618816 ERROR File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 156, in _get_shortcuts 2019-11-09 07 51 42.087 T 3905618816 ERROR tree = xmltree.parse( path ) 2019-11-09 07 51 42.087 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse 2019-11-09 07 51 42.088 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse 2019-11-09 07 51 42.089 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed 2019-11-09 07 51 42.092 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror 2019-11-09 07 51 42.093 T 3905618816 ERROR ParseError: mismatched tag: line 82, column 2 2019-11-09 07 51 42.208 T 3905618816 ERROR GetDirectory - Error getting /storage/.kodi/media/Fonts/ 2019-11-09 07 51 42.208 T 3905618816 ERROR GetDirectory - Error getting special://home/media/Fonts/ 2019-11-09 07 51 42.311 T 3905618816 NOTICE Log level changed to "LOG_LEVEL_DEBUG_FREEMEM" 2019-11-09 07 51 42.312 T 3905618816 NOTICE Enabled debug logging due to GUI setting. Level 2. 2019-11-09 07 51 42.314 T 4087455760 DEBUG ------ Window Init () ------ 2019-11-09 07 51 42.321 T 3905618816 DEBUG CAddonSettings[script.skinshortcuts]: loading setting definitions 2019-11-09 07 51 42.321 T 3905618816 DEBUG CAddonSettings[script.skinshortcuts]: trying to load setting definitions from old format... 2019-11-09 07 51 42.322 T 3905618816 DEBUG CAddonSettings[script.skinshortcuts]: loading setting values 2019-11-09 07 51 42.327 T 3905618816 DEBUG script.skinshortcuts: Profile found: Master user ( special://masterprofile/ ) 2019-11-09 07 51 42.339 T 3481240448 DEBUG Thread Timer start, auto delete: false 2019-11-09 07 51 42.344 T 3905618816 DEBUG script.skinshortcuts: Includes file does not exist 2019-11-09 07 51 42.354 T 4087455760 DEBUG ------ Window Init (DialogExtendedProgressBar.xml) ------ 2019-11-09 07 51 42.420 T 3905618816 DEBUG script.skinshortcuts: Building menu for profile Master user 2019-11-09 07 51 42.433 T 3481240448 DEBUG Thread Timer 3481240448 terminating 2019-11-09 07 51 42.433 T 3224966016 DEBUG Thread Timer start, auto delete: false 2019-11-09 07 51 42.938 T 3224966016 DEBUG Thread Timer 3224966016 terminating 2019-11-09 07 51 44.344 T 3905618816 DEBUG script.skinshortcuts: Failed to write menu 2019-11-09 07 51 44.344 T 3905618816 ERROR Traceback (most recent call last): 2019-11-09 07 51 44.344 T 3905618816 ERROR File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 97, in buildMenu 2019-11-09 07 51 44.345 T 3905618816 ERROR self.writexml( profilelist, mainmenuID, groups, numLevels, buildMode, progress, options, minitems ) 2019-11-09 07 51 44.345 T 3905618816 ERROR File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 504, in writexml 2019-11-09 07 51 44.345 T 3905618816 ERROR submenudata = DATA._get_shortcuts( submenu, submenuDefaultID, True, profile[0] ) 2019-11-09 07 51 44.346 T 3905618816 ERROR File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 156, in _get_shortcuts 2019-11-09 07 51 44.346 T 3905618816 ERROR tree = xmltree.parse( path ) 2019-11-09 07 51 44.347 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse 2019-11-09 07 51 44.347 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse 2019-11-09 07 51 44.348 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed 2019-11-09 07 51 44.348 T 3905618816 ERROR File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror 2019-11-09 07 51 44.349 T 3905618816 ERROR ParseError: mismatched tag: line 82, column 2 2019-11-09 07 51 44.350 T 3905618816 NOTICE Disabled debug logging due to GUI setting. Level 0. 2019-11-09 07 51 44.350 T 3905618816 NOTICE Log level changed to "LOG_LEVEL_NORMAL" 2019-11-09 07 51 46.369 T 3224966016 WARNING Repository add-on repository.kodiwpigulce.pl uses plain HTTP for add-on downloads in path http://kodiwpigulce.pl/zip/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.372 T 3224966016 WARNING Repository add-on repository.polishteam uses plain HTTP for add-on downloads in path http://polishteam.ru/REPO/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.380 T 3224966016 WARNING Repository add-on repository.supremacy uses plain HTTP for add-on downloads in path http://supremacy.org.uk/zip/plugin/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.486 T 3224966016 WARNING Repository add-on repository.kodiwpigulce.pl uses plain HTTP for add-on downloads in path http://kodiwpigulce.pl/zip/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.489 T 3224966016 WARNING Repository add-on repository.polishteam uses plain HTTP for add-on downloads in path http://polishteam.ru/REPO/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.496 T 3224966016 WARNING Repository add-on repository.supremacy uses plain HTTP for add-on downloads in path http://supremacy.org.uk/zip/plugin/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.626 T 3224966016 WARNING Repository add-on repository.kodiwpigulce.pl uses plain HTTP for add-on downloads in path http://kodiwpigulce.pl/zip/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.628 T 3224966016 WARNING Repository add-on repository.polishteam uses plain HTTP for add-on downloads in path http://polishteam.ru/REPO/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.634 T 3224966016 WARNING Repository add-on repository.supremacy uses plain HTTP for add-on downloads in path http://supremacy.org.uk/zip/plugin/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.685 T 3224966016 WARNING Repository add-on repository.kodiwpigulce.pl uses plain HTTP for add-on downloads in path http://kodiwpigulce.pl/zip/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.687 T 3224966016 WARNING Repository add-on repository.polishteam uses plain HTTP for add-on downloads in path http://polishteam.ru/REPO/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.693 T 3224966016 WARNING Repository add-on repository.supremacy uses plain HTTP for add-on downloads in path http://supremacy.org.uk/zip/plugin/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.736 T 3224966016 WARNING Repository add-on repository.kodiwpigulce.pl uses plain HTTP for add-on downloads in path http://kodiwpigulce.pl/zip/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.738 T 3224966016 WARNING Repository add-on repository.polishteam uses plain HTTP for add-on downloads in path http://polishteam.ru/REPO/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 46.744 T 3224966016 WARNING Repository add-on repository.supremacy uses plain HTTP for add-on downloads in path http://supremacy.org.uk/zip/plugin/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled! 2019-11-09 07 51 49.214 T 3684889472 NOTICE Polish Team Wizard: Ignore Log File: kodi.log

**Comment by notoco** [comment]
mbebe nas zabije za robienie tu syfu.
Moja skórka w 100% ma prawo nie działać. Jest robiona pod to, czego używam (choć testuję na różnych systemach) - nie odpowiadam za nią, to raczej dla bardziej zaawansowanych użytkowników...
Sprawdź wersję script.skinshortcuts - bo to na nim się wykrzacza - ja mam 1.0.19~alpha na boxie - z repo PTW Collection https://github.com/CherryKodi/CHERRY/tree/master/zips/repository.pltwcollection

**Comment by notoco** [comment]
@timtumturutumtum - w sprawie skórki pisz tutaj:
https://github.com/notoco/univ/issues
