### ISSUE TITLE
CP GO

### ISSUE THREAD

**Issue by Orzech-85** [mbebe/blomqvist#214]
Czy można by z wtyczki cp go załadować kanały telewizyjne do iptv simple client?

**Comment by p3t3n3t** [comment]
Ja próbowałem na zasadzie NC+ ale jakoś niestety nie chciało działać, możliwe że coś źle robiłem więc z cała mocą dołączam się do pytania @Orzech-85

**Comment by BlackGlassSkin** [comment]
Możecie sprawdzić pod ten wzór

plugin://plugin.video.internetws/?url=https://internetowa.tv/channel/13-ulica/&prem=&page=1&mode=playTV

Url potrzebny ze strony www w cp jest page=0 , mode=nie pamiętam cos w ten deseń playcpgo

**Comment by p3t3n3t** [comment]
Właśnie na podobnej zasadzie robiłem czyli, dodałem do ulubionych następnie otworzyłem plik favourites.xml  i z niego kopiowałem do listy.  Od "plugin://plugin.video.cpgo/........." do  ".......;page=0" i tak też robiłem z NC+ tam działa a z CP GO nie śmiga.

**Comment by BlackGlassSkin** [comment]
nie śmiga bo jest PLOT

zobacz na wzór jeszcze raz , i jeszcze raz 
(nie wiem czy ruszy ale bardziej prawdopobne niż z favourites)

**Comment by Orzech-85** [comment]
dodałem HBO do ulubionych i stamtąd działa, ale listy m3u już nie.

plugin://plugin.video.cpgo?url=https://go.cyfrowypolsat.pl/tv/channel/14625&mode=playCPGO&page=0

url skopiowany z przeglądarki, mode z ulubionych
próbowałem też url=14625 - taki url jest w ulubionych

w logu jest następujący błąd:

> NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 31 channels.
NOTICE: PVR Manager: Starting
NOTICE: PVR Manager: Started
NOTICE: EPG thread started
NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
ERROR: Previous line repeats 1 times.
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'result'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.cpgo/main.py", line 717, in <module>
                                                playCPGO(exlink,cofaj=True)
                                              File "/storage/.kodi/addons/plugin.video.cpgo/main.py", line 222, in playCPGO
                                                playback = response['result']['mediaItem']['playback']
                                            KeyError: 'result'
                                            -->End of Python script error report<--

**Comment by tomkolp** [comment]
Jest możliwość przełączania programów bez wychodzenia do listy programów? Np. Jakiś skrót na klawiaturze.

**Comment by kunraf** [comment]
nie mogę sobie z tym poradzić a jest to faktycznie świetna alternatywa dla jeżdżenia myszką po kołdrze, takie dodanie pc go do apki smart IPTV.

POMOŻECIE??

**Comment by tomkolp** [comment]
Ja używam teraz m-tvguide działa cpgo działa jak rakieta i jeszcze Epg jest.

**Comment by kunraf** [comment]
ok, ale tam dalej trzeba wkleić listę m3u, której nie mogę zrobić

**Comment by kunraf** [comment]
może jakiś gotowiec?

**Comment by tomkolp** [comment]
Jeżeli chodzi o cpgo to wystarczy wpisać login i hasło

**Comment by kunraf** [comment]
podpowiesz gdzie w konfiguracji?

**Comment by kunraf** [comment]
mialem nieaktualna wtyczke, zrobilem dzieki
