### ISSUE TITLE
Bajeczki.org - poprawka?

### ISSUE THREAD

**Issue by Kantel88** [mbebe/blomqvist#224]
We wtyczce nie dzialaja linki, na stronie wszystko śmiga. Czy da się zrobić jakąś poprawkę do bajeczek? ;)

**Comment by mbebe** [comment]
poprawione - wersja 1.3 w repo

**Comment by bkc22** [comment]
Dałoby radę podrasować kod wtyczki, aby przechodziła na następną stronę wyników w katalogu danej bajki tudzież w wynikach wyszukiwania?

**Comment by PetitDiablePL** [comment]
taki błąd w logach:

Error Type: <type 'exceptions.IndexError'>                                        
                                            Error Contents: list index out of range                                           
                                            Traceback (most recent call last):                                                
                                              File ".kodi/addons/plugin.video.bajeczkiorg/main.py", line 360, in <module>
                                                getLinks(exlink)
                                              File ".kodi/addons/plugin.video.bajeczkiorg/main.py", line 307, in getLinks
                                                new=re.findall('data-item="([^"]+)"',result[0])[0].replace('&quot;','"')
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-02-21 16:53:45.913 T:139949941668544   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajeczkiorg/?url=https%3A%2F%2Fbajeczki.org%2Fswiat-elmo%2Fskrzypce%2F&page=1&mode=getLinks&foldername=%C5%9Awiat+Elmo+-+Skrzypce]

**Comment by PetitDiablePL** [comment]
w uzupełnieniu do poprzedniejszego mojego posta.
wychodzi na to, że niektóre bajki można oglądać a niektóre nie. np psi patrol działa

**Comment by mbebe** [comment]
To sa wyniki z nowej wersji wtyczki?

**Comment by PetitDiablePL** [comment]
wersja 1.3

**Comment by PetitDiablePL** [comment]
baranek timmy, aktualny log:

2020-02-24 19:24:04.348 T:140218710644480  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.97
2020-02-24 19:24:05.274 T:140218710644480   ERROR: NEWADDON Unknown Video Info Key "href"
2020-02-24 19:24:05.274 T:140218710644480   ERROR: NEWADDON Unknown Video Info Key "img"
2020-02-24 19:24:05.275 T:140218710644480   ERROR: NEWADDON Unknown Video Info Key "href"
2020-02-24 19:24:05.275 T:140218710644480   ERROR: NEWADDON Unknown Video Info Key "img"
2020-02-24 19:24:05.276 T:140218710644480   ERROR: NEWADDON Unknown Video Info Key "href"                                     
2020-02-24 19:24:05.276 T:140218710644480   ERROR: NEWADDON Unknown Video Info Key "img"                                      
2020-02-24 19:24:08.092 T:140218710644480  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.97                        
2020-02-24 19:24:09.795 T:140218710644480   ERROR: ResolveURL: ResolverError Error - From: dailymotion Link: https://www.dailymotion.com/embed/video/x2p0nfh?autoplay=1&#038;logo=0&#038;info=1&#038;hideInfos=1&#038;start=0&#038;syndication=254517&#038;foreground=&#038;highlight=&#038;background=: Unable to locate config

**Comment by PetitDiablePL** [comment]
zainstalowałem przed chwilą werję 1.4

2020-02-24 19:33:43.801 T:139810788448000  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.97                        
2020-02-24 19:33:44.780 T:139810788448000   ERROR: NEWADDON Unknown Video Info Key "href"                                     
2020-02-24 19:33:44.780 T:139810788448000   ERROR: NEWADDON Unknown Video Info Key "img"                                      
2020-02-24 19:33:44.831 T:139810788448000   ERROR: NEWADDON Unknown Video Info Key "href"                                     
2020-02-24 19:33:44.831 T:139810788448000   ERROR: NEWADDON Unknown Video Info Key "img"                                      
2020-02-24 19:33:44.832 T:139810788448000   ERROR: NEWADDON Unknown Video Info Key "href"                                     
2020-02-24 19:33:44.832 T:139810788448000   ERROR: NEWADDON Unknown Video Info Key "img"                                      
2020-02-24 19:33:47.746 T:139810788448000  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.97                        
2020-02-24 19:33:49.544 T:139810788448000   ERROR: ResolveURL: ResolverError Error - From: dailymotion Link: https://www.dailymotion.com/embed/video/x2p0nfh?autoplay=1&#038;logo=0&#038;info=1&#038;hideInfos=1&#038;start=0&#038;syndication=254517&#038;foreground=&#038;highlight=&#038;background=: Unable to locate config

**Comment by PetitDiablePL** [comment]
przeinstalowałem resolvurl i nagle prawie wszystko to co wcześniej nie działało zaczęło działać (sprawdzałem tylko te pozycje na których mi najbardziaj zależy). np gryzli i lemingi zaczęły się odtwarzać ale baranek timmy nadal nie. (ten sam błąd)

**Comment by PetitDiablePL** [comment]
już chhyba wiem w czym rzecz. właściwie wszystko śmiga ok ale np w tym baranku timmy na samym początku odtwarzania pojawia się (na stronie www) komunikat, że oglądając to video zgadzamy sie na coś tam. i pewnie w tym przyczyna braku odtwarzania na kodi.
