### ISSUE TITLE
Hejo.tv

### ISSUE THREAD

**Issue by Katapulta** [mbebe/blomqvist#227]
Ktoś coś wie o co chodzi ?? Logowanie na pewno poprawne ale nie wiem dlaczego wtyczka nagle przestała działać 
```

2020-01-06 16:35:40.343 T:5148   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\plugin.video.hejotv\main.py", line 866, in <module>
                                                home()
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\plugin.video.hejotv\main.py", line 78, in home
                                                login()
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\plugin.video.hejotv\main.py", line 241, in login
                                                kukz=re.findall("""setCookie\(['"](.+?)['"],['"](.+?)['"]""",unpacked)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-01-06 16:35:40.435 T:4592   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.hejotv/
2020-01-06 16:35:40.445 T:7248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hejotv/) failed

```

**Comment by mbebe** [comment]
Dzis pod wieczor zostanie poprawiona strona i wtyczka ruszy. ;-)

**Comment by Katapulta** [comment]
> 
> 
> Dzis pod wieczor zostanie poprawiona strona i wtyczka ruszy. ;-)

O co chodzi "z tą nową funkcjonalnością" na hejo ?? Ktos coś wie , tak na marginesie ??

**Comment by mbebe** [comment]
sprawdz czy dziala wtyczka ;-)

**Comment by Katapulta** [comment]
> 
> 
> Nie dziala wtyczka, ok - poprawiam :-D
> 
> > O co chodzi "z tą nową funkcjonalnością" na hejo ?? Ktos coś wie , tak na marginesie ??
> 
>     * dodawanie do ulubionych kanalow, filmow i seriali
> 
>     * zmiana wyszukiwania filmow i seriali
>       ;-)

nie działa, ciagle mam ten sam błąd w kodi - ten który wkleiłem wyżej , bez logowania do serwisu wtyczka się odpala - po wpisaniu danych logowania wywala błąd.

**Comment by Katapulta** [comment]
Ok, udało mi się zalogować natomiast lista filmów i seriali - pusto. TV odpala.
