### ISSUE TITLE
filman nie działa

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#229]
Filmann.cc chyba padł. Nie pokazuje ani filmów ani seriali, kategorie też nie działają
W logach:
```
2020-01-07 07:21:40.848 T:11824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py", line 918, in <module>
                                                listSeries(ex_link,page)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py", line 147, in listSeries
                                                mlinks,mparams = getSeries(ex_link)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py", line 611, in getSeries
                                                result=parseDOM(content,'div', attrs={'class': "col-sm-9"})[1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-01-07 07:21:40.940 T:11816   ERROR: XFILE::CDirectory::GetDirectory - Error getting 
```

**Comment by Katapulta** [comment]
ale to już lezy trupem przecież od dawien dawna chyba

**Comment by mbebe** [comment]
dziala dziala.  Dodali zabezpieczenie.

**Comment by telewizortcl** [comment]
Wtyczka zaczęła również działać!

Ale jeśli we wtyczce wybiorę sortowanie wg np. dat premier, to na pierwszej stronie pokazuje prawidłowo filmy, ale na kolejnych już niestety, ale wraca chyba do domyślnego.

Poza tym:
 - nie pokazuje żadnych filmów w zakładce "Dla dzieci" (na stronie www są filmy w tej kategorii)
 - przy próbie wyświetlenia Seriali pojawia się komunikat o błędzie
 - Telewizja (LIVE) też generuje komunikat o błędzie (na stronie www działa)

Fajnie jakby udało się poprawić wtyczkę, bo dużo zasobów ta strona zawiera.

**Comment by mbebe** [comment]
O. To niespodzianka, ze wtyczka ruszyla. :-D

**Comment by telewizortcl** [comment]
Pojawiły się następujące problemy:
 - Nie działa większość linków - tylko z clipwatching.com działają - może to wina resolvera?
 - W zakładce Telewizja żaden z kanałów nie ma linków.

**Comment by mbebe** [comment]
do sprawdzenia ta wersja.
[plugin.video.filmancc-2.3.zip](https://github.com/mbebe/blomqvist/files/4887385/plugin.video.filmancc-2.3.zip)

**Comment by telewizortcl** [comment]
Jak się wchodzi na stronę poprzez przeglądarkę, często na samym początku uruchamiany jest jakiś skrypt sprawdzający przeglądarkę (antyDDOS) i dopiero po kilku sekundach wyświetla się właściwa zawartość strony. Nie wiem, na jakiej zasadzie działa takie sprawdzanie przeglądarki, ale dodatek w Kodi chyba nigdy nie przechodzi takiego testu. Nie ma na to sposobu?

**Comment by mbebe** [comment]
Wersja 2.3 nie dziala?

**Comment by telewizortcl** [comment]
Na ten moment nie działa; ale to pewnie przez ten skrypt sprawdzający o którym napisałem post wcześniej; w logach takie zapisy:
`2020-07-12 12:40:05.444 T:3868   ERROR: C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py:990: SyntaxWarning: name 'mybtn_user' is assigned to before global declaration
                                              global mybtn_user
2020-07-12 12:40:07.188 T:3868   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py", line 905, in <module>
                                                listTv(ex_link)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py", line 112, in listTv
                                                mlinks= getTvs(ex_link)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.filmancc\main.py", line 425, in getTvs
                                                result=parseDOM(content,'div', attrs={'class': "row tv-list"})[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-07-12 12:40:07.255 T:3168   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.filmancc/?ex_link=https%3a%2f%2ffilman.cc%2ftelewizja-online-pl&foldername=Telewizja%20(LIVE)&iconImage=DefaultFolder.png&mode=ListTv&page=1&token=wRHbnFbsDV_PocNj-c75GHT4yQA%3d5NConikJSV3Q2rqBApsF5X29RK0%3b5XnCp8ROHeTAwSTAD40aWLQtxa4%3dMyEqgbPGdKxFn5xRtaWiYjOoHc8%3bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3d1594636443%3bxKYht8hz2GFGS40501t0LnoLmAY%3d1594550043%3b__cfduid%3dd7846526e8f83a0563f75a09bf8c7ede41594550061
2020-07-12 12:40:07.266 T:3404   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.filmancc/?ex_link=https%3a%2f%2ffilman.cc%2ftelewizja-online-pl&foldername=Telewizja%20(LIVE)&iconImage=DefaultFolder.png&mode=ListTv&page=1&token=wRHbnFbsDV_PocNj-c75GHT4yQA%3d5NConikJSV3Q2rqBApsF5X29RK0%3b5XnCp8ROHeTAwSTAD40aWLQtxa4%3dMyEqgbPGdKxFn5xRtaWiYjOoHc8%3bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3d1594636443%3bxKYht8hz2GFGS40501t0LnoLmAY%3d1594550043%3b__cfduid%3dd7846526e8f83a0563f75a09bf8c7ede41594550061) failed
2020-07-12 12:40:07.343 T:4504 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BB%5DZaloguj%5B%2FB%5D&ex_link=&mode=Opcje
2020-07-12 12:40:07.343 T:4504   ERROR: InputStream: Error opening, plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BB%5DZaloguj%5B%2FB%5D&ex_link=&mode=Opcje
2020-07-12 12:40:07.345 T:4504 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BCOLOR+lightblue%5DWersja%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&ex_link=&mode=filtr%3Aversion
2020-07-12 12:40:07.345 T:4504   ERROR: InputStream: Error opening, plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BCOLOR+lightblue%5DWersja%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&ex_link=&mode=filtr%3Aversion
2020-07-12 12:40:07.346 T:4504 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BCOLOR+lightblue%5DJako%C5%9B%C4%87%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&ex_link=&mode=filtr%3Aquality
2020-07-12 12:40:07.346 T:4504   ERROR: InputStream: Error opening, plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BCOLOR+lightblue%5DJako%C5%9B%C4%87%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&ex_link=&mode=filtr%3Aquality
2020-07-12 12:40:07.347 T:4504 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BCOLOR+lightblue%5DSortowanie%3A%5B%2FCOLOR%5D+%5BB%5DDaty+dodania%5B%2FB%5D&ex_link=&mode=filtr%3Asort
2020-07-12 12:40:07.347 T:4504   ERROR: InputStream: Error opening, plugin://plugin.video.filmancc/?token=wRHbnFbsDV_PocNj-c75GHT4yQA%3D5NConikJSV3Q2rqBApsF5X29RK0%3B5XnCp8ROHeTAwSTAD40aWLQtxa4%3DMyEqgbPGdKxFn5xRtaWiYjOoHc8%3Bq9-OLyxRH4r1Ig7uAWRDaqNj-uM%3D1594636443%3BxKYht8hz2GFGS40501t0LnoLmAY%3D1594550043%3B__cfduid%3Dd7846526e8f83a0563f75a09bf8c7ede41594550061&page=1&foldername=%5BCOLOR+lightblue%5DSortowanie%3A%5B%2FCOLOR%5D+%5BB%5DDaty+dodania%5B%2FB%5D&ex_link=&mode=filtr%3Asort
`

**Comment by mbebe** [comment]
Ten skrypt jest w tej wersji dodany.

**Comment by telewizortcl** [comment]
Nie wiedziałem, że trzeba się logować. Do tej pory nie trzeba było się logować.
Faktycznie, po wpisaniu danych logowania działa.
A dlaczego nie może działać bez logowania?

**Comment by mbebe** [comment]
Moze nic  nie mozna odtworzyc bez zalogowania sie.

**Comment by telewizortcl** [comment]
na stronie WWW można bez logowania.

**Comment by telewizortcl** [comment]
Na stronie filman.cc znów pojawiła się zakładka "Telewizja", czy można prosić o przywrócenie jej we wtyczce? (kiedyś była)

**Comment by mbebe** [comment]
Jak widzisz to jest jak walka z wiatrakami. Dzis dziala, na nastepny dzien im wylaczaja.
Dzis nie dziala.  :confused:

**Comment by telewizortcl** [comment]
Ponawiam prośbę o przywrócenie w tej wtyczce pozycji "Telewizja" (bo kiedyś była). Na stronie internetowej pojawiło się już całkiem sporo kanałów do oglądania. Jeśli witryna w danym momencie nie chowa się za Cloudflare to wtyczka w kodi działa bardzo dobrze.
