### ISSUE TITLE
pastebinVID - problem z CDA

### ISSUE THREAD

**Issue by Vonzgj** [mbebe/blomqvist#281]
Witam. Mam problem z odtwarzaniem niektórych filmów z CDA.pl - wyskakuje błąd wtyczki pastebinVID. Z tego co zauważyłem, problem dotyczy filmów, które nie mają opcji wyboru jakości video na cda.pl (np. https://www.cda.pl/video/10047738 lub https://www.cda.pl/video/2899227e3). Z resztą filmów nie ma problemów.

Błąd z logów:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\dawid\AppData\Roaming\Kodi\addons\plugin.video.pastebinVID\main.py", line 468, in <module>
                                                getLinks(exlink)
                                              File "C:\Users\dawid\AppData\Roaming\Kodi\addons\plugin.video.pastebinVID\main.py", line 281, in getLinks
                                                stream = cdapl.getLinkCda(stream)
                                              File "C:\Users\dawid\AppData\Roaming\Kodi\addons\plugin.video.pastebinVID/resources/lib\cdapl.py", line 81, in getLinkCda
                                                srce = re.compile('href="(.*?)"', re.DOTALL).findall(qua[0][1])[::-1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by mbebe** [comment]
Dzieki za informacje. Poprawione. Wtyczka w repo - 1,8.7.

**Comment by Arek76** [comment]
@mbebe Juz az mi glupio no ale :) Od wczoraj wieczorem znowu lipa :) Nie wiem czy po tej aktualizacji czy nie : 
 NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
2020-04-07 07:43:22.980 T:12479 WARNING: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom-kodi.cba.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2020-04-07 07:43:23.201 T:12479 WARNING: Previous line repeats 2 times.
2020-04-07 07:43:23.201 T:12479 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2020-04-07 07:43:23.247 T:12550 WARNING: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom-kodi.cba.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2020-04-07 07:43:25.196 T:12479 WARNING: Previous line repeats 3 times.
2020-04-07 07:43:25.196 T:12479   ERROR: CGUIMediaWindow::GetDirectory(addons://) failed
2020-04-07 07:43:34.142 T:12554  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.109
2020-04-07 07:43:46.954 T:12561  NOTICE: Previous line repeats 1 times.
2020-04-07 07:43:46.954 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:46.954 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:46.971 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:46.971 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:46.988 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:46.988 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.005 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.005 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.021 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.022 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.037 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.037 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.039 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.039 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.040 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.040 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.055 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.055 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.056 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.056 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.057 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.057 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.058 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.058 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.070 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.070 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.072 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.072 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.073 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.073 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.074 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.074 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.075 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.075 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.076 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.076 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.077 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.077 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.078 T:12561   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-07 07:43:47.078 T:12561   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-07 07:43:47.232 T:12508 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F489617211%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:43:47.232 T:12508   ERROR: InputStream: Error opening, plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F489617211%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:43:47.236 T:12510 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F494812311%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:43:47.236 T:12510   ERROR: InputStream: Error opening, plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F494812311%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:44:02.521 T:12609  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.109
2020-04-07 07:44:05.579 T:12479  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Fwww.cda.pl%2Fvideo%2F493857424%3Fwersja%3D720p+&mode=getLinks&page=0
2020-04-07 07:44:06.493 T:12479   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://vwaw590.cda.pl/sPg2MyEPuBnbi8RbdbDJvQ/1586281445/sda283c57cc62123e43aeb1d5fcf1552f70rsp.mp4|Cookie=PHPSESSID=1&Referer=http://static.cda.pl/flowplayer/flash/flowplayer.commercial-3.2.18.swf
2020-04-07 07:44:06.496 T:12623  NOTICE: Creating InputStream
2020-04-07 07:44:07.108 T:12623   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-04-07 07:44:07.108 T:12623   ERROR: CCurlFile::Open failed with code 403 for https://vwaw590.cda.pl/sPg2MyEPuBnbi8RbdbDJvQ/1586281445/sda283c57cc62123e43aeb1d5fcf1552f70rsp.mp4:
2020-04-07 07:44:07.502 T:12623   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-04-07 07:44:07.502 T:12623   ERROR: CCurlFile::Open failed with code 403 for https://vwaw590.cda.pl/sPg2MyEPuBnbi8RbdbDJvQ/1586281445/sda283c57cc62123e43aeb1d5fcf1552f70rsp.mp4:
2020-04-07 07:44:07.503 T:12623   ERROR: Open - failed to open source <https://vwaw590.cda.pl/sPg2MyEPuBnbi8RbdbDJvQ/1586281445/sda283c57cc62123e43aeb1d5fcf1552f70rsp.mp4|Cookie=PHPSESSID=1&Referer=http://static.cda.pl/flowplayer/flash/flowplayer.commercial-3.2.18.swf>
2020-04-07 07:44:07.503 T:12623   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Fwww.cda.pl%2Fvideo%2F493857424%3Fwersja%3D720p+&mode=getLinks&page=0]
2020-04-07 07:44:07.503 T:12623  NOTICE: CVideoPlayer::OnExit()
2020-04-07 07:44:07.523 T:12479  NOTICE: CVideoPlayer::CloseFile()
2020-04-07 07:44:07.524 T:12479  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-07 07:44:07.524 T:12479  NOTICE: VideoPlayer: finished waiting
2020-04-07 07:44:15.029 T:12629  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.109
2020-04-07 07:44:18.840 T:12479  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F370283840%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:44:19.680 T:12479   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://vwaw594.cda.pl/Knv4v4RHS5TvbnxVoePWHQ/1586281458/hd4954ecfea39d78c2507d83ffe18695193f3e31b94f542bb3c1018e725baa9d7b0rsp.mp4|Cookie=PHPSESSID=1&Referer=http://static.cda.pl/flowplayer/flash/flowplayer.commercial-3.2.18.swf
2020-04-07 07:44:19.687 T:12644  NOTICE: Creating InputStream
2020-04-07 07:44:20.320 T:12644   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-04-07 07:44:20.320 T:12644   ERROR: CCurlFile::Open failed with code 403 for https://vwaw594.cda.pl/Knv4v4RHS5TvbnxVoePWHQ/1586281458/hd4954ecfea39d78c2507d83ffe18695193f3e31b94f542bb3c1018e725baa9d7b0rsp.mp4:
2020-04-07 07:44:20.706 T:12644   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-04-07 07:44:20.706 T:12644   ERROR: CCurlFile::Open failed with code 403 for https://vwaw594.cda.pl/Knv4v4RHS5TvbnxVoePWHQ/1586281458/hd4954ecfea39d78c2507d83ffe18695193f3e31b94f542bb3c1018e725baa9d7b0rsp.mp4:
2020-04-07 07:44:20.706 T:12644   ERROR: Open - failed to open source <https://vwaw594.cda.pl/Knv4v4RHS5TvbnxVoePWHQ/1586281458/hd4954ecfea39d78c2507d83ffe18695193f3e31b94f542bb3c1018e725baa9d7b0rsp.mp4|Cookie=PHPSESSID=1&Referer=http://static.cda.pl/flowplayer/flash/flowplayer.commercial-3.2.18.swf>
2020-04-07 07:44:20.706 T:12644   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F370283840%3Fwersja%3D1080p+&mode=getLinks&page=0]
2020-04-07 07:44:20.706 T:12644  NOTICE: CVideoPlayer::OnExit()
2020-04-07 07:44:20.720 T:12479  NOTICE: CVideoPlayer::CloseFile()
2020-04-07 07:44:20.725 T:12479  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-07 07:44:20.725 T:12479  NOTICE: VideoPlayer: finished waiting
2020-04-07 07:44:49.358 T:12508 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F489617211%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:44:49.358 T:12508   ERROR: InputStream: Error opening, plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F489617211%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:44:49.364 T:12510 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F494812311%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:44:49.364 T:12510   ERROR: InputStream: Error opening, plugin://plugin.video.pastebinVID/?url=https%3A%2F%2Febd.cda.pl%2F805x204%2F494812311%3Fwersja%3D1080p+&mode=getLinks&page=0
2020-04-07 07:44:51.493 T:12655  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.109
2020-04-07 07:44:51.593 T:12654   ERROR: GetDirectory - Error getting plugin://plugin.video.pastebinVID/
2020-04-07 07:44:51.612 T:12479   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pastebinVID/) failed
2020-04-07 07:44:51.619 T:12661   ERROR: Unable to find plugin
2020-04-07 07:44:51.619 T:12661   ERROR: GetDirectory - Error getting plugin://
2020-04-07 07:44:51.622 T:12479   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2020-04-07 07:45:07.147 T:12479 WARNING: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom-kodi.cba.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
