### ISSUE TITLE
Hejo.tv - Error Contents: list index out of range

### ISSUE THREAD

**Issue by suleks** [mbebe/blomqvist#284]
blad wywala dla zalogowanego uzytkownika
wersja wtyczki: 2.2.71

Wszystko dzialalo do dzisiaj(08/04/2020) do okolo 22:00 i nagle przestalo.

`ERROR: /home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-04-08 22:35:57.583 T:1493168864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.hejotv/main.py", line 934, in <module>
                                                home()
                                              File "/home/osmc/.kodi/addons/plugin.video.hejotv/main.py", line 120, in home
                                                login()
                                              File "/home/osmc/.kodi/addons/plugin.video.hejotv/main.py", line 256, in login
                                                kukz=re.findall("""setCookie\(['"](.+?)['"],['"](.+?)['"]""",unpacked)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-04-08 22:35:57.721 T:1537200864   ERROR: GetDirectory - Error getting plugin://plugin.video.hejotv/
2020-04-08 22:35:57.723 T:1916171824   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hejotv/) failed`

**Comment by penguinspl** [comment]
Ten sam problem wrocilem z pracy o 23 czasu UK zalaczylem hejo dzialalo jakies 5 min aczkolwiek co chwile buforowalo po czym dostalem error przy uruchomieniu wtyczki.Juz nic nie da sie zrobic

**Comment by mbebe** [comment]
Poszla poprawka w repo. wersja 2.2.80.

**Comment by suleks** [comment]
Smiga jak zloto, dzieki :)
