### ISSUE TITLE
3.filmy.com

### ISSUE THREAD

**Issue by FXcodi** [mbebe/blomqvist#291]
Mam oto taki problem z tym serwisem

> ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-04-13 11:09:07.584 T:31572   ERROR: Previous line repeats 2 times.
2020-04-13 11:09:07.584 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.584 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.601 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.601 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.602 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.602 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.634 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.634 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.636 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.636 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.667 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.667 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.669 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.669 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.684 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.684 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.686 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.686 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.702 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.702 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.704 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.704 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.734 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.734 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.736 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.736 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.737 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.737 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.750 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.751 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.768 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.768 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.770 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.770 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.772 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.772 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.773 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.773 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:07.786 T:31572   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:07.786 T:31572   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:15.700 T:31604   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-04-13 11:09:16.541 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.541 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.561 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.561 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.582 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.582 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.604 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.604 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.641 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.641 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.643 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.643 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.680 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.680 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.702 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.702 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.705 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.705 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.741 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.741 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.760 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.760 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.762 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.762 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.780 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.780 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.781 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.782 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.784 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.784 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.805 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.805 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.841 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.841 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.843 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.844 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.846 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.846 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:16.848 T:31604   ERROR: NEWADDON Unknown Video Info Key "href"
2020-04-13 11:09:16.848 T:31604   ERROR: NEWADDON Unknown Video Info Key "img"
2020-04-13 11:09:21.868 T:31658   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-04-13 11:09:22.142 T:31658   ERROR: Previous line repeats 1 times.
2020-04-13 11:09:22.142 T:31658   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.3filmy/main.py", line 649, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.3filmy/main.py", line 641, in router
                                                Play3Filmy(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.3filmy/main.py", line 350, in Play3Filmy
                                                qual=max(eval(re.findall('q_avb":(\[.+?\])',aa)[0]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by mbebe** [comment]
Na jakim filmie?

**Comment by mbebe** [comment]
I trzeba byc zalogowanym, bez zalogowania nic na pewno nie pojdzie.

**Comment by FXcodi** [comment]
Aha, mam tak bez logowania.
Czyli muszę się zarejestrować?

**Comment by mbebe** [comment]
A sprawdz na stronie. :-/
![3e3e3e3e3e3](https://user-images.githubusercontent.com/30195202/79123182-db3e8f80-7d99-11ea-8978-15649a36860b.jpg)

**Comment by FXcodi** [comment]
Po zalogowaniu jest już wporzadku.
Dzięki:-)
