### ISSUE TITLE
3 filmy

### ISSUE THREAD

**Issue by papulus** [mbebe/blomqvist#301]
Od dzisiaj jest jakiś problem z 3filmy
Nie odpala filmów ani seriali. Czy też tak macie?

**Comment by Bogdan16** [comment]
witam
wyskakoje mi Blad 3filmy

pozdrawiam

**Comment by Katapulta** [comment]
`020-04-27 10:49:30.783 T:1736   ERROR: Previous line repeats 1 times.
2020-04-27 10:49:30.783 T:1736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\plugin.video.3filmy\main.py", line 649, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\plugin.video.3filmy\main.py", line 641, in router
                                                Play3Filmy(exlink)
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\plugin.video.3filmy\main.py", line 350, in Play3Filmy
                                                qual=max(eval(re.findall('q_avb":(\[.+?\])',aa)[0]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
`


błąd w kodi wygląda tak. Jak by komuś był potrzebny.

**Comment by rafalmar1981** [comment]
Tak mi przestało działać 3filmy, nie odpala żadnego linku, mam też problem z odpaleniem linków na efilmy i nie mogę się zalogować na ekino, ResolveURL6.4.120.
Log
https://paste.kodi.tv/owusijaboc

**Comment by lucjan76** [comment]
potwierdzam na efilmy jest captcha a po wpisaniu nie odpala linków

**Comment by mbebe** [comment]
Spoko. Od jutra mam nadzieje ogarniac. ;-)

**Comment by rafalmar1981** [comment]
Dziękujemy

**Comment by papulus** [comment]
Wszystko działa perfekcyjnie. Dziękujemy mbebe.

**Comment by mbebe** [comment]
Poszla poprawka.

**Comment by papulus** [comment]
Ok dziękujemy @mbebe wszystko działa bez zarzutu
