### ISSUE TITLE
hejo.tv list index out of range

### ISSUE THREAD

**Issue by suleks** [mbebe/blomqvist#323]
hejo.tv chyba znowu zmienilo cos w API i sie wywala calkowicie przy proboie uruchomienia pluginu.

`2020-06-08 12:28:57.475 T:1916126768   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-06-08 12:28:59.417 T:1521476320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.hejotv/main.py", line 945, in <module>
                                                home()
                                              File "/home/osmc/.kodi/addons/plugin.video.hejotv/main.py", line 119, in home
                                                login()
                                              File "/home/osmc/.kodi/addons/plugin.video.hejotv/main.py", line 266, in login
                                                token=parseDOM(response, 'meta', attrs={'name':'csrf-token'},ret='content')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-06-08 12:28:59.531 T:1529869024   ERROR: GetDirectory - Error getting plugin://plugin.video.hejotv/
2020-06-08 12:28:59.533 T:1916126768   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hejotv/) failed`

**Comment by mbebe** [comment]
Ruszylo od nowa? ;-) Bo u mnie nie ma jakiegos bledu.

**Comment by suleks** [comment]
ha, zaczelo dzialac :D, musieli naprawic po swojej stronie. Dzieki za spojrzenie na to!
