### ISSUE TITLE
HDSeans - wyszukiwarka

### ISSUE THREAD

**Issue by telewizortcl** [mbebe/blomqvist#337]
Witam
Chciałem zgłosić, że w dodatku HDSeans, jeśli wyszukujemy tekst, który zawiera znaki diakrytyczne, to po następnym wejściu w wyszukiwarkę (po ponownym uruchomieniu KODI) wyskakuje komunikat o błędzie;  Zatem na ten moment trzeba wpisywać "Roza" zamiast "Róża", bo inaczej nie skorzystamy następnym razem z wyszukiwarki (po ponownym uruchomieniu KODI), dopóki nie skasujemy pliku "commoncache.db". Ten problem występuje na pewno pod Windowsem, nie wiem jak jest pod Androidem.
Pozdrawiam
`2020-07-11 12:09:15.090 T:5624   ERROR: C:\Program Files\Kodi\system\python\Lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              return ''.join(map(quoter, s))
2020-07-11 12:09:15.091 T:5624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'\xf3'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.HDseans\main.py", line 633, in <module>
                                                addDir(name=entry, ex_link='https://hdseans.pl/autocomplete?query='+urllib.quote_plus(entry), mode='ListSearch', page=1, fanart=None, contextmenu=contextmenu)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib.py", line 1306, in quote_plus
                                                return quote(s, safe)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib.py", line 1299, in quote
                                                return ''.join(map(quoter, s))
                                            KeyError: u'\xf3'
                                            -->End of Python script error report<--
2020-07-11 12:09:15.160 T:5660   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.HDseans/?ex_link&foldername=%5bB%5dSzukaj%5b%2fB%5d&mode=Szukaj&page=0
2020-07-11 12:09:15.164 T:5448   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.HDseans/?ex_link&foldername=%5bB%5dSzukaj%5b%2fB%5d&mode=Szukaj&page=0) failed
`

**Comment by mbebe** [comment]
tez do sprawdzenia:
[plugin.video.HDseans-1.8.zip](https://github.com/mbebe/blomqvist/files/4907541/plugin.video.HDseans-1.8.zip)

**Comment by telewizortcl** [comment]
Teraz nie pojawia się już komunikat o błędzie, czyli OK, ale w logach takie dziwne zapisy (choć wszystko działa):
`2020-07-12 12:55:09.930 T:5596   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
2020-07-12 12:55:09.930 T:5496   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2020-07-12 12:55:12.601 T:5916   ERROR: XFILE::CDirectory::GetDirectory - Error getting library://music/recentlyplayedalbums.xml
2020-07-12 12:55:12.618 T:5916   ERROR: XFILE::CDirectory::GetDirectory - Error getting library://music/genres.xml
2020-07-12 12:55:14.802 T:5496   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-07-12 12:55:19.444 T:4500 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DGatunki%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afkat
2020-07-12 12:55:19.444 T:4500   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DGatunki%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afkat
2020-07-12 12:55:19.445 T:4500 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DOceny+widz%C3%B3w%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afoce
2020-07-12 12:55:19.445 T:4500   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DOceny+widz%C3%B3w%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afoce
2020-07-12 12:55:19.446 T:4500 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DRok+produkcji%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Aflat
2020-07-12 12:55:19.446 T:4500   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DRok+produkcji%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Aflat
2020-07-12 12:55:19.446 T:4500 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DJako%C5%9B%C4%87%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afjak
2020-07-12 12:55:19.446 T:4500   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DJako%C5%9B%C4%87%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afjak
2020-07-12 12:55:19.447 T:4500 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DWersja+j%C4%99zykowa%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afwer
2020-07-12 12:55:19.447 T:4500   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DWersja+j%C4%99zykowa%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afwer
2020-07-12 12:55:55.791 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.791 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.791 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.791 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.791 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.791 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.792 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.807 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.807 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.807 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.807 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.807 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.807 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "img"
2020-07-12 12:55:55.808 T:4772   ERROR: NEWADDON Unknown Video Info Key "url"
2020-07-12 12:56:37.693 T:4488 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DGatunki%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afkat
2020-07-12 12:56:37.694 T:4488   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DGatunki%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afkat
2020-07-12 12:56:37.694 T:4488 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DOceny+widz%C3%B3w%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afoce
2020-07-12 12:56:37.694 T:4488   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DOceny+widz%C3%B3w%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afoce
2020-07-12 12:56:37.695 T:4488 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DRok+produkcji%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Aflat
2020-07-12 12:56:37.695 T:4488   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DRok+produkcji%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Aflat
2020-07-12 12:56:37.696 T:4488 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DJako%C5%9B%C4%87%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afjak
2020-07-12 12:56:37.696 T:4488   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DJako%C5%9B%C4%87%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afjak
2020-07-12 12:56:37.697 T:4488 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DWersja+j%C4%99zykowa%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afwer
2020-07-12 12:56:37.697 T:4488   ERROR: InputStream: Error opening, plugin://plugin.video.HDseans/?foldername=%5BCOLOR+blue%5DWersja+j%C4%99zykowa%3A%5B%2FCOLOR%5D+%5BB%5DWszystkie%5B%2FB%5D&page=1&ex_link=&mode=filtr%3Afwer
`
