### ISSUE TITLE
Wtyczka canalplusvod - problem z logowaniem

### ISSUE THREAD

**Issue by abc-300** [mbebe/blomqvist#381]
Witam,

Mam wykupiony dostep do portalu canalplus. Niestety podczas uruchomienia wtyczki canalplusvod dostaje nizej zamieszczony komunikat bledu. Bez problemu loguje sie do portalu przez przegladarki(na windowsie i linuxie) oraz na androidzie. Poprawnosc hasla oraz loginu sprawdzalem kilka razy.

Nie widzialem, aby ktos zglaszal podobny problem - wiec moze to byc problem u mnie - poprosze inne osoby o potwierdzenie, ze u nich wtyczka dziala (lub nie).

Dzieki!

2020-10-04 16:35:36.755 T:5108  NOTICE: Starting Kodi (18.8 (18.8.0) Git:20200727-45686bddb1). Platform: Windows NT x86 64-bit
2020-10-04 16:35:37.286 T:10268  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
2020-10-04 16:35:56.777 T:11008   ERROR: C:\Users\abc-20180601\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1004:
            InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-04 16:35:58.804 T:11008   ERROR: Previous line repeats 15 times.
2020-10-04 16:35:58.804 T:11008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\abc-20180601\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 1148, in <module>
                                                home()
                                              File "C:\Users\abc-20180601\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 92, in home
                                                CANALvod().logowanie()
                                              File "C:\Users\abc-20180601\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 714, in logowanie
                                                response = json.loads(authresponse[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-10-04 16:35:58.823 T:3636   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.canalplusvod/
2020-10-04 16:35:58.830 T:5108   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canalplusvod/) failed

**Comment by praspp** [comment]
Masz znak "+" w aliasie adresu email którym się logujesz?

**Comment by abc-300** [comment]
Loguje sie adresem email w postaci: aaaa.b@cc.dd - jest tam kropka.

**Comment by abc-300** [comment]
Znalazlem zrodlo problemu: wtyczka canalplusvod nie zaloguje sie do portalu https://www.canalplus.com/pl/ jezeli
w hasle wystepuje znak & (ampersand). Podczas logowania przez przegladarke problem nie wystepuje.

**Comment by praspp** [comment]
Tak samo jak znak "+" w aliasie email uniemożliwia zalogowanie do serwisu.

**Comment by mbebe** [comment]
Sprawdz te wersje.
[plugin.video.canalplusvod-1.6.1.zip](https://github.com/mbebe/blomqvist/files/5360870/plugin.video.canalplusvod-1.6.1.zip)

**Comment by praspp** [comment]
> Sprawdz te wersje.
> [plugin.video.canalplusvod-1.6.1.zip](https://github.com/mbebe/blomqvist/files/5360870/plugin.video.canalplusvod-1.6.1.zip)
> 

Logowanie ze znakiem "+" w aliasie w wersji  1.6.1 działa poprawnie. Dziękuję.

Czy mógłbyś spojrzeć na issues: #379 i #382 ?

**Comment by abc-300** [comment]
Dziala. Dziekuje.
