### ISSUE TITLE
wtyczki nie działają gdy strona stosuje dodatek anty ddos cloadfire

### ISSUE THREAD

**Issue by telewizortcl** [mbebe/blomqvist#425]
Dzień dobry,
Zauważyłem, serwis "darmowa-tv.ws" dodał jakieś zabezpieczenie anty-ddos cloudfire sprawdzające przeglądarkę i chyba przez to nie działa plugin w KODI. Nie wiem na czym to polega, ale w przeglądarce tak jakby trzeba poczekać kilka sekund i dopiero wpuszcza.
To samo też dla wtyczki filman.cc - nie może się nawet zalogować (pojawia się napis błąd logowania).
Czy da się zaimplementować mechanizm tak aby wtyczkę, jak przeglądarkę, dopuszczał do treści serwisu?

W logach takie coś:
2020-12-11 17:40:45.689 T:4912 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.darmowatv\maintv.py", line 1270, in
router(sys.argv[2][1:])
File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.darmowatv\maintv.py", line 1246, in router
getDarmowaws()
File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.darmowatv\maintv.py", line 169, in getDarmowaws
result = parseDOM(html, 'div', attrs={'class': "entry-content"})[0]
IndexError: list index out of range
-->End of Python script error report<--
2020-12-11 17:40:45.720 T:5136 ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.darmowatv/?image=C%3a%5cUsers%5cuser%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.darmowatv%2fresources%2fdarm.png&mode=darmowatvws&title=darmowatv.ws&url=http%3a%2f%2fdarmowa-tv.ws
2020-12-11 17:40:45.722 T:3940 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.darmowatv/?image=C%3a%5cUsers%5cuser%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.darmowatv%2fresources%2fdarm.png&mode=darmowatvws&title=darmowatv.ws&url=http%3a%2f%2fdarmowa-tv.ws) failed

**Comment by mbebe** [comment]
No tak. I na ten moment jest to nie do ominiecia. :-D

**Comment by endrju800** [comment]
https://github.com/VeNoMouS/cloudscraper
Może coś w ten deseń 🤷🤷🤔🤔
