### ISSUE TITLE
Wtyczka CanalPLUS-VOD nie działa

### ISSUE THREAD

**Issue by wapacz** [mbebe/blomqvist#426]
Dziś rano próbowałem uruchomić Canal PLUS ale nie mogłem nawet wejść do wtyczki.
W logach taki błąd:
```
2020-12-15 11:36:22.916 T:1765798112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.canalplusvod/main.py", line 1197, in <module>
                                                home()
                                              File "/home/osmc/.kodi/addons/plugin.video.canalplusvod/main.py", line 92, in home
                                                CANALvod().logowanie()
                                              File "/home/osmc/.kodi/addons/plugin.video.canalplusvod/main.py", line 751, in logowanie
                                                response = json.loads(authresponse[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```

**Comment by BlackGlassSkin** [comment]
Logowanie działa poprawnie , wpisz poprawne dane...

**Comment by wapacz** [comment]
Closed
