### ISSUE TITLE
Kanały TV w dodoatku PlayerPLmb

### ISSUE THREAD

**Issue by bienonygus** [mbebe/blomqvist#444]
Wystąpił jakiś problem z odtwarzaniem kanałów na żywo w dodatku PlayerPLmb - inne treści działają poprawnie, poniżej część logu:

```
2020-12-30 16:15:25.638 T:140084223497984   ERROR: NEWADDON Unknown Video Info Key "img"
2020-12-30 16:15:25.638 T:140084223497984   ERROR: NEWADDON Unknown Video Info Key "url"
2020-12-30 16:15:29.692 T:140084223497984   ERROR: /home/a/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-12-30 16:15:30.244 T:140084223497984   ERROR: Previous line repeats 3 times.
2020-12-30 16:15:30.244 T:140084223497984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'subtitles'
                                            Traceback (most recent call last):
                                              File "/home/a/.kodi/addons/plugin.video.playermb/main.py", line 916, in <module>
                                                PLAYERPL().playvid(exlink)
                                              File "/home/a/.kodi/addons/plugin.video.playermb/main.py", line 507, in playvid
                                                stream_url, license_url, subtitles = self.getPlaylist(str(id))
                                              File "/home/a/.kodi/addons/plugin.video.playermb/main.py", line 469, in getPlaylist
                                                subs = vid['video']['subtitles']
                                            KeyError: 'subtitles'
                                            -->End of Python script error report<--
2020-12-30 16:15:30.276 T:140086085786304   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.playermb/?name=ALE+KINO%2B+HD&moviescount=0&url=57601%3Akanal&movie=True&image=https%3A%2F%2Fr-scale-cc.dcs.redcdn.pl%2Fscale%2Fo2%2Fn%2FedytorEPG%2Flogo%2Flogotype_250242.png%3Ftype%3D0%26srcmode%3D4%26srcx%3D0%252F1%26srcy%3D0%252F1%26dstw%3D400%26dsth%3D200&mode=playvid&page=1]
2020-12-30 16:15:37.743 T:140086085786304  NOTICE: Stopping player
```

**Comment by HerrFlick84** [comment]
Dodam tylko że aktualizacja poszła u mnie 28.12 i od tego czasu nie działa

**Comment by ScriptNewbie** [comment]
U mnie również to samo. W wersji 1.4 działa.

**Comment by mbebe** [comment]
Poszla poprawka.

**Comment by bienonygus** [comment]
wszystko działa, wielkie dzięki :)
