### ISSUE TITLE
CanalPlus-VOD - Nie działa

### ISSUE THREAD

**Issue by praspp** [mbebe/blomqvist#473]
CanalPlus-VOD 1.7.1

Windows 7 Professional 64 bit, Kodi 18.9

Fire OS 6.2.7.7 (Android 7.1.2), Kodi 18.9

Proszę o sprawdzenie.

![CanalPlus-VOD_1 7 1](https://user-images.githubusercontent.com/62591068/108063789-0c43bc80-705c-11eb-8cb3-c8eafce72a66.png)

**Comment by mbebe** [comment]
Ale to to, co to jest?
Nie wyswietla tresci, nie odtwarza?

**Comment by praspp** [comment]
Nie wyświetla treści.

**Comment by tete90** [comment]
Witam serdecznie. Jest ewidentny problem z logowaniem. 
Bardzo proszę o pomoc.

**Comment by praspp** [comment]
> Ale to to, co to jest?
> Nie wyswietla tresci, nie odtwarza?

2021-02-19 03:08:37.409 T:7504   ERROR: CPythonInvoker(77, C:\Users\pras_pp\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py): script didn't stop in 5 seconds - let's kill it
2021-02-19 03:08:37.409 T:7504   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.canalplusvod/
2021-02-19 03:08:37.415 T:9632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canalplusvod/) failed

**Comment by pogo1975** [comment]
Brak możliwości zalogowania w logu jedynie informacje tak jak @praspp napisał

**Comment by praspp** [comment]
@mbebe, spójrz na to, proszę.

**Comment by praspp** [comment]
Czy ktoś z użytkowników może potwierdzić działanie lub niedziałanie wtyczki CanalPlus-VOD 1.7.1 ?

**Comment by mbebe** [comment]
https://github.com/mbebe/blomqvist/issues/479
Poszla poprawka.

**Comment by praspp** [comment]
K 18.9, CanalPlus-VOD 1.7.2 teraz taki log:

![error](https://user-images.githubusercontent.com/62591068/109186472-3d756880-7791-11eb-8b97-a4d077c9873c.PNG)

**Comment by praspp** [comment]
Na Fire OS 6.2.7.7 (Android 7.1.2), Kodi 18.9 w repozytorium brak wersji CanalPlus-VOD 1.7.2.

**Comment by mbebe** [comment]
Poprawilem, pospieszylem sie (nie sprawdzilem na czystym kodi) ;-)

**Comment by praspp** [comment]
Teraz - OK! Dziękuję :-) 1.7.3 działa poza odtwarzaniem z menu Kodi "Telewizja" (przez PVR IPTV Simple Client, problem opisany w #387). Podobnym problemem dotknięta jest wtyczka Horizon Go (issues #379). Możesz to poprawić?

**Comment by EuHadii1** [comment]
Sprawdziłem na Android TV i wszystko pięknie działa :) dziękuję

**Comment by praspp** [comment]
Owszem działa, ale nie wszystkie kanały. 1.7.3 nie odtwarza Eleven Sports 4. 
Log:
2021-02-28 10:12:17.291 T:7148   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\pras_pp\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 1366, in <module>
                                                PLAYvodCANAL(exlink)
                                              File "C:\Users\pras_pp\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 201, in PLAYvodCANAL
                                                str_url = re.findall('src="([^"]+)"',response)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-02-28 10:12:17.488 T:10876   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.canalplusvod/?name=ELEVEN+SPORTS+4&moviescount=0&url=https%3A%2F%2Froutemeup2.canalplus-bo.net%2Fplfiles%2Fv1%2Fhss-ssl%2F11Sports4.json%3Fdeviceid%3D3%7C21282&movie=True&image=https%3A%2F%2Fthumb.canalplus.pro%2Fhttp%2Funsafe%2F%7BresolutionXY%7D%2Fncplus-cdn.canal-plus.io%2Fp1%2Fchannel%2F21282%2FCHN43FN%2FEleven_4_640_480_0503.png%3Fdate%3D20210222110723&mode=playCANvod&page=1]
2021-02-28 10:12:18.914 T:4544  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:36674085-7995-11eb-8904-ce3d4504a5e2" for service "urn:upnp-org:serviceId:ContentDirectory" of device "RT-AC56U-ECA8" (timeout = 300)
2021-02-28 10:12:28.908 T:2672  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:3664e33c-7995-11eb-8904-ce3d4504a5e2" for service "urn:upnp-org:serviceId:ConnectionManager" of device "RT-AC56U-ECA8" (timeout = 300)
2021-02-28 10:12:46.460 T:9756 WARNING: Platinum [neptune.http]: NPT_CHECK failed, result=-20014 (NPT_ERROR_TIMEOUT) [(stream.ReadLine(line, NPT_HTTP_PROTOCOL_MAX_LINE_LENGTH))]

**Comment by Konik35** [comment]
U mnie też nie działa mam kodi 18.1 na urządzeniu z linux. Po kliknięciu na ikonę canalplusvod kręci się kółko jakby chciał załadować a niestety nie ładuje. Bardzo proszę o pomoc.

**Comment by mbebe** [comment]
Usun (odinstaluj wtyczke) i sprobuj ponownie.

**Comment by mbebe** [comment]
Na ten eleven4 poszla poprawka.

**Comment by praspp** [comment]
> Na ten eleven4 poszla poprawka.

Dzięki. CanalPlus-VOD v. 1.7.4 rozwiązuje problem z Eleven Sports 4. Wtyczka nadal nie działa poprawnie z pvr iptv simple client - issue #387 (problem z logowaniem). Gorąca prośba o poprawkę.
