### ISSUE TITLE
TVP

### ISSUE THREAD

**Issue by Smerd1233** [mbebe/blomqvist#496]
Jakis dziwny problem pjawil sie na TVP, zaden film, serial, itp nie otwiera sie, a Live Stream tvp info, smiga az milo. Jak ktorys z Panow znalazl chwile zeby na to zerknac bede wdzieczny.

**Comment by hevet** [comment]
Sprawdziłem kilka programów i seriali, wszystko działa bez problemu.

**Comment by Smerd1233** [comment]
dziekuje, wyinstalowalem wtyczke i ponownie zainstalowalem i zaskoczylo
Jeszcze raz dziekuje za informacje

**Comment by gs188** [comment]
A ja mam taki problem (ale zaznaczam ze to jest spoza terytorium Polski) - wtyczka sie otwiera, wybieram dany serial, dostaje informacje ze jest niedostepny i ze moze sprobowac z proxy, szuka proxy znajduje kilka, nawet 8  i wtedy sie wyklada.  Log ponizej jesli cos pomoze, czy moze w 19 brakuje jakiejs wtyczki 'wspierajacej' TVP addon?


2021-03-15 23:03:32.788 T:12561    INFO <general>: CPythonInvoker(32, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/addon.py): script successfully run
2021-03-15 23:03:33.302 T:12561    INFO <general>: Python interpreter stopped
2021-03-15 23:03:36.450 T:12569    INFO <general>: initializing python engine.
2021-03-15 23:03:58.529 T:12586   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.530 T:12586   ERROR <general>: Thread-1
2021-03-15 23:03:58.530 T:12586   ERROR <general>: :
                                                   
2021-03-15 23:03:58.532 T:12586   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.532 T:12586   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.542 T:12586   ERROR <general>:     
2021-03-15 23:03:58.543 T:12586   ERROR <general>: self.run()
2021-03-15 23:03:58.543 T:12586   ERROR <general>: 
                                                   
2021-03-15 23:03:58.543 T:12586   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.544 T:12587   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.545 T:12587   ERROR <general>: Thread-2
2021-03-15 23:03:58.545 T:12587   ERROR <general>: :
                                                   
2021-03-15 23:03:58.545 T:12587   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.545 T:12587   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.553 T:12587   ERROR <general>:     
2021-03-15 23:03:58.553 T:12587   ERROR <general>: self.run()
2021-03-15 23:03:58.553 T:12587   ERROR <general>: 
                                                   
2021-03-15 23:03:58.555 T:12587   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.557 T:12588   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.557 T:12588   ERROR <general>: Thread-3
2021-03-15 23:03:58.558 T:12588   ERROR <general>: :
                                                   
2021-03-15 23:03:58.558 T:12588   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.558 T:12588   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.566 T:12588   ERROR <general>:     
2021-03-15 23:03:58.566 T:12588   ERROR <general>: self.run()
2021-03-15 23:03:58.566 T:12588   ERROR <general>: 
                                                   
2021-03-15 23:03:58.567 T:12588   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.569 T:12589   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.569 T:12589   ERROR <general>: Thread-4
2021-03-15 23:03:58.569 T:12589   ERROR <general>: :
                                                   
2021-03-15 23:03:58.569 T:12589   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.570 T:12589   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.571 T:12587   ERROR <general>:     
2021-03-15 23:03:58.572 T:12587   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.572 T:12587   ERROR <general>: 
                                                   
2021-03-15 23:03:58.572 T:12587   ERROR <general>: TypeError
2021-03-15 23:03:58.572 T:12587   ERROR <general>: : 
2021-03-15 23:03:58.573 T:12587   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.573 T:12587   ERROR <general>: 
                                                   
2021-03-15 23:03:58.574 T:12586   ERROR <general>:     
2021-03-15 23:03:58.575 T:12586   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.575 T:12586   ERROR <general>: 
                                                   
2021-03-15 23:03:58.575 T:12586   ERROR <general>: TypeError
2021-03-15 23:03:58.575 T:12586   ERROR <general>: : 
2021-03-15 23:03:58.575 T:12586   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.576 T:12586   ERROR <general>: 
                                                   
2021-03-15 23:03:58.578 T:12590   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.578 T:12590   ERROR <general>: Thread-5
2021-03-15 23:03:58.579 T:12590   ERROR <general>: :
                                                   
2021-03-15 23:03:58.579 T:12590   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.580 T:12590   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.593 T:12591   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.594 T:12591   ERROR <general>: Thread-6
2021-03-15 23:03:58.594 T:12591   ERROR <general>: :
                                                   
2021-03-15 23:03:58.595 T:12591   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.595 T:12591   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.597 T:12588   ERROR <general>:     
2021-03-15 23:03:58.597 T:12588   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.597 T:12588   ERROR <general>: 
                                                   
2021-03-15 23:03:58.598 T:12588   ERROR <general>: TypeError
2021-03-15 23:03:58.598 T:12588   ERROR <general>: : 
2021-03-15 23:03:58.599 T:12588   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.599 T:12588   ERROR <general>: 
                                                   
2021-03-15 23:03:58.600 T:12589   ERROR <general>:     
2021-03-15 23:03:58.601 T:12589   ERROR <general>: self.run()
2021-03-15 23:03:58.601 T:12589   ERROR <general>: 
                                                   
2021-03-15 23:03:58.601 T:12589   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.604 T:12590   ERROR <general>:     
2021-03-15 23:03:58.605 T:12590   ERROR <general>: self.run()
2021-03-15 23:03:58.605 T:12590   ERROR <general>: 
                                                   
2021-03-15 23:03:58.605 T:12590   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.608 T:12589   ERROR <general>:     
2021-03-15 23:03:58.608 T:12589   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.608 T:12589   ERROR <general>: 
                                                   
2021-03-15 23:03:58.609 T:12589   ERROR <general>: TypeError
2021-03-15 23:03:58.609 T:12589   ERROR <general>: : 
2021-03-15 23:03:58.609 T:12589   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.609 T:12589   ERROR <general>: 
                                                   
2021-03-15 23:03:58.613 T:12590   ERROR <general>:     
2021-03-15 23:03:58.613 T:12590   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.614 T:12590   ERROR <general>: 
                                                   
2021-03-15 23:03:58.614 T:12590   ERROR <general>: TypeError
2021-03-15 23:03:58.614 T:12590   ERROR <general>: : 
2021-03-15 23:03:58.615 T:12590   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.615 T:12590   ERROR <general>: 
                                                   
2021-03-15 23:03:58.615 T:12591   ERROR <general>:     
2021-03-15 23:03:58.616 T:12591   ERROR <general>: self.run()
2021-03-15 23:03:58.616 T:12591   ERROR <general>: 
                                                   
2021-03-15 23:03:58.616 T:12591   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.617 T:12592   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.617 T:12592   ERROR <general>: Thread-7
2021-03-15 23:03:58.617 T:12592   ERROR <general>: :
                                                   
2021-03-15 23:03:58.618 T:12592   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.618 T:12592   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.624 T:12592   ERROR <general>:     
2021-03-15 23:03:58.625 T:12592   ERROR <general>: self.run()
2021-03-15 23:03:58.625 T:12592   ERROR <general>: 
                                                   
2021-03-15 23:03:58.625 T:12592   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.628 T:12591   ERROR <general>:     
2021-03-15 23:03:58.628 T:12591   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.629 T:12591   ERROR <general>: 
                                                   
2021-03-15 23:03:58.629 T:12591   ERROR <general>: TypeError
2021-03-15 23:03:58.629 T:12591   ERROR <general>: : 
2021-03-15 23:03:58.629 T:12591   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.629 T:12591   ERROR <general>: 
                                                   
2021-03-15 23:03:58.630 T:12592   ERROR <general>:     
2021-03-15 23:03:58.631 T:12592   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.631 T:12592   ERROR <general>: 
                                                   
2021-03-15 23:03:58.631 T:12592   ERROR <general>: TypeError
2021-03-15 23:03:58.631 T:12592   ERROR <general>: : 
2021-03-15 23:03:58.632 T:12592   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.632 T:12592   ERROR <general>: 
                                                   
2021-03-15 23:03:58.635 T:12593   ERROR <general>: Exception in thread 
2021-03-15 23:03:58.636 T:12593   ERROR <general>: Thread-8
2021-03-15 23:03:58.636 T:12593   ERROR <general>: :
                                                   
2021-03-15 23:03:58.636 T:12593   ERROR <general>: Traceback (most recent call last):
                                                   
2021-03-15 23:03:58.639 T:12593   ERROR <general>:   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-03-15 23:03:58.645 T:12593   ERROR <general>:     
2021-03-15 23:03:58.646 T:12593   ERROR <general>: self.run()
2021-03-15 23:03:58.646 T:12593   ERROR <general>: 
                                                   
2021-03-15 23:03:58.646 T:12593   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/resources/lib/twork.py", line 14, in run
                                                   
2021-03-15 23:03:58.651 T:12569   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/addon.py:406: DeprecationWarning: isAlive() is deprecated, use is_alive() instead
                                                     while any([i.isAlive() for i in proxies]):
                                                   
2021-03-15 23:03:58.653 T:12593   ERROR <general>:     
2021-03-15 23:03:58.654 T:12593   ERROR <general>: self.result = self._target(*self._args)
2021-03-15 23:03:58.654 T:12593   ERROR <general>: 
                                                   
2021-03-15 23:03:58.654 T:12593   ERROR <general>: TypeError
2021-03-15 23:03:58.655 T:12593   ERROR <general>: : 
2021-03-15 23:03:58.655 T:12593   ERROR <general>: 'NoneType' object is not callable
2021-03-15 23:03:58.655 T:12593   ERROR <general>: 
                                                   
2021-03-15 23:03:59.652 T:12569   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/addon.py:408: DeprecationWarning: isAlive() is deprecated, use is_alive() instead
                                                     done = [t for t in proxies if not t.isAlive()]
                                                   
2021-03-15 23:03:59.657 T:12569    INFO <general>: CPythonInvoker(33, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVP.pl/addon.py): script successfully run
2021-03-15 23:03:59.678 T:4292    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.TVP.pl/?mode=vodTVP_play&foldername=Lepsza+po%C5%82owa%2C+odc.+22&ex_link=51691988%26mime_type%3Dvideo%2Fmp4]
2021-03-15 23:04:00.197 T:12569    INFO <general>: Python interpreter stopped
2021-03-15 23:04:52.944 T:4307     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-03-15 23:04:52.972 T:4307     INFO <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2021-03-15 23:04:53.059 T:4307     INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 63504 m_frames: 1984 m_frameSize: 8 channels: 2

**Comment by mbebe** [comment]
Sprobuj na tej wersji:
[plugin.video.TVP.pl-2.2.49.zip](https://github.com/mbebe/blomqvist/files/6145073/plugin.video.TVP.pl-2.2.49.zip)

**Comment by gs188** [comment]
No niestety, dalej nie dziala.  Log w zalaczniku.
[tvp.log](https://github.com/mbebe/blomqvist/files/6152517/tvp.log)

**Comment by Smerd1233** [comment]
U mnie jest dokladnie to samo na K19, i tez mieszkam poza granica PL, na K18 wszystko smiga bardzo ladnie.

**Comment by mbebe** [comment]
Kolejna wersja do sprawdzenia.
[plugin.video.TVP.pl-2.2.50.zip](https://github.com/mbebe/blomqvist/files/6155986/plugin.video.TVP.pl-2.2.50.zip)

**Comment by gs188** [comment]
No niestety dalej nie dziala.  Tym razem "wizualnie" wyglada to tak - wybieram odcinek danego serialu, mowi ze sa ograniczenia licencyjne, naciskam na "Yes" - szuka proxy, znajduje 8, negatywnie odpowiedzialo 0.  Na tym komunikacie stoi kolo 30-40 sekund po czym wywala blad i wraca do menu.  Log zalaczony.
[test.log](https://github.com/mbebe/blomqvist/files/6156714/test.log)

**Comment by mbebe** [comment]
jaki serial?

**Comment by gs188** [comment]
np. Lepsza polowa

**Comment by mbebe** [comment]
Ok. Tu powinno byc ok.
[plugin.video.TVP.pl-2.2.51.zip](https://github.com/mbebe/blomqvist/files/6157494/plugin.video.TVP.pl-2.2.51.zip)

**Comment by gs188** [comment]
U mnie niestety dalej nie dziala - tzn pokazuje ze znalazlo 8 proxy servers, potem odlicza ile odpowiedzialo negatywnie - jak przechodzi przez wszystkie to sie wyklada... ale moze problem jest z proxy servers ktore mi znajduje, sam nie wiem.

**Comment by mbebe** [comment]
U mnie znajdowalo i odtwarzalo. ;-/

**Comment by Smerd1233** [comment]
Moze ktos jeszcze napisal by swoja opinie kto uzywa tvp poprzez proxy, czy dziala wlasciwie czy tez nie po ostatniej poprawce 2.2. 51.zip

**Comment by gs188** [comment]
Chcialem dodac ze jest jakis progres - tzn probowalem przed chwila jeszcze raz i teraz dochodze dalej, tzn mam pytanie czy uzyc proxy bo ograniczenia licencyjne, szuka darmowych serwerow proxy, po 1 ktory odpowiada negatywnie idzie dalej tzn wyskauje lista bitrates (jakosci) do wyboru ale... no niewazne ktora wybiore, kreci sie koleczko kilkanascie sekund po czym wywala z powrotem do menu.  Zalaczam log jesli cos pomoze...

[tvp2.log](https://github.com/mbebe/blomqvist/files/6160250/tvp2.log)

**Comment by Smerd1233** [comment]
Nie wiem, kto, co, i jak (pewnie Pan mbebe) ale spiesze doniesc ze tvp zaczelo dzialac pieknie poza granicami Polski. Dziekujemy !!!!

**Comment by gs188** [comment]
U mnie status jest taki ze 2.2.48 (ten z repo) dalej nie dziala, natomiast wersja testowa 2.2.51 odpalila odcinek 'Lepsza polowa' ale nie mialem wyboru bitrate/jakosci wczesniej.  Mozliwe ze to jakies zmiany po stronie tvp a nie wtyczki?

**Comment by papulus** [comment]
Witam,

Sprawdzilem wszystkie trzy wersje tzn 49 ,50 i 51 i zadna nie odpala po przez darmowe proxy. Mbebe mozna by prosic o pomoc.
Dziekuje
