### ISSUE TITLE
CanalPlus- nie działa generator listy kanałów na Kodi 19

### ISSUE THREAD

**Issue by hevet** [mbebe/blomqvist#539]
Zaktualizowałem na jednym z urządzeń kodi do wersji 19 i przy próbie generowania listy kanałów wyskakuje bład dodatku, na kodi 18.9 generator działa poprawnie. Czy ktoś może potwierdzić u niego ten błąd? Ewentualnie prośba do @mbebe o poprawkę.

**Comment by EuHadii1** [comment]
https://drive.google.com/file/d/1pRuVyL3fkinmiIxdgJra3c5cNOescyG0/view?usp=drivesdk

Do sprawdzenia pod kodi 18 i 19. Trochę się z tym męczyłem, bo cały czas był błąd kodowania, ale chyba udało się rozwiązać problem

**Comment by hevet** [comment]
@EuHadii1 nie można pobrać, pokazuje "plik w koszu właściciela".

**Comment by EuHadii1** [comment]
https://drive.google.com/file/d/1eott9oI5skl73jLehozcADIFUaAsruL3/view?usp=drivesdk

Wrzuciłem jeszcze raz

**Comment by hevet** [comment]
Wygląda na to, że działa 😁

**Comment by hevet** [comment]
Zainstalowałem na Kodi 18.9 ale wyskakuje błąd dodatku, znaczy dodatek w ogóle się nie uruchamia. Widnieje nadal wersja 1.7.4.6. Po instalacji dodatku z repozytorium działa.

**Comment by EuHadii1** [comment]
https://drive.google.com/file/d/1jBNQwm-74dJXwSpOappXwQfDgwAt7e6Q/view?usp=sharing

Mała poprawka pod kodi 18.9 :) Teraz w obu wersjach powinno działać.

@mbebe - proszę o update w repo

**Comment by hevet** [comment]
@EuHadii1 
Dzisiaj wykupiłem nowe pakiety, niestety przestał działać generator listy na Kodi 18.9. Kawałek logu:
`2021-05-27 21:53:13.069 T:8540   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 1469, in <module>
                                                GenList()
                                              File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 196, in GenList
                                                m3u8.addM3UChannel(count, item['title'], item['image'], grouptitle, count, canalurl)
                                              File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\playlist.py", line 13, in addM3UChannel
                                                genreStr = unicode(group)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--`

**Comment by EuHadii1** [comment]
Instalowałeś z tego linku, który jest powyżej?

https://drive.google.com/file/d/1jBNQwm-74dJXwSpOappXwQfDgwAt7e6Q/view?usp=sharing

**Comment by hevet** [comment]
Tak, z tego linku. Ogólnie to wiem gdzie tkwi błąd. W poprzednich pakietach nie miałem TVP3, które teraz generator listy przypisuje do kategorii "Ogólne". Błąd jest właśnie przez polski znak "ó". Gdy w jednym z pliku dodatku zmieniłem na "Ogolne" bez polskiego "ó", błędu nie ma. Na kodi 19 tego problemu nie ma.

**Comment by praspp** [comment]
@hevet Przetestowałem generowanie listy przez wtyczkę CanalPlus-VOD 1.7.4.7 na Kodi 18.9 (Android 7.1 i Win7 64bit). U mnie listy m3u8 generowane są poprawnie. Opisywany przez Ciebie problem nie występuje.

**Comment by hevet** [comment]
U mnie też poprawnie działała, dopóki nie zmieniłem pakietu. Może to kwestia jeszcze jakichś ustawień, np. w systemie?

**Comment by Delavor** [comment]
Hmm u mnie na wersji 1.7.4.7 niestety też wywala błąd:
`2021-07-26 23:07:01.755 T:7528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\delav\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 1475, in <module>
                                                GenList()
                                              File "C:\Users\delav\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 199, in GenList
                                                m3u8.addM3UChannel(count, item['title'], item['image'], grouptitle, count, canalurl)
                                              File "C:\Users\delav\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\playlist.py", line 23, in addM3UChannel
                                                genreStr = unicode(group)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--`

**Comment by hevet** [comment]
Spróbuj tej wersji 
[plugin.video.canalplusvod.zip](https://github.com/mbebe/blomqvist/files/6882562/plugin.video.canalplusvod.zip)
