### ISSUE TITLE
Kimcartoon not working

### ISSUE THREAD

**Issue by crak3rjack** [mbebe/blomqvist#555]
@mbebe  Nothing working in the addon!  :(

**Comment by hevet** [comment]
W logu pokazuje takie błędy:

`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.kimcartoon\main.py", line 586, in <module>
                                                       router(sys.argv[2][2:])
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.kimcartoon\main.py", line 563, in router
                                                       ListLinks(exlink)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.kimcartoon\main.py", line 149, in ListLinks
                                                       links=getLinks(exlink)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.kimcartoon\main.py", line 174, in getLinks
                                                       servers =  parseDOM(html,'select', attrs={'id': "selectServer"})[0]#select id="id"
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--`

**Comment by mbebe** [comment]
Please check new version.

**Comment by crak3rjack** [comment]
@mbebe thanks a lot bud... back to enjoying cartooms...your work is super!😉💪

**Comment by mujunk** [comment]
This is broken again. Can you please check

**Comment by hevet** [comment]
It works on Kodi 19.1.
