### ISSUE TITLE
goNET.TV - LEPŠÍ.TV

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#565]
j.w.
dodane do repo.
[plugin.video.gonettv-1.3.zip](https://github.com/mbebe/blomqvist/files/6626635/plugin.video.gonettv-1.3.zip)

**Comment by xxcriticxx** [comment]
Usługa działa wszędzie na terenie Unii Europejskiej.

Czyli u mnie nie dziala yey :)

**Comment by hevet** [comment]
@mbebe po wejściu w zakładkę radio wyświetla się tylko 201 stacji, niezależnie czy wybiorę wszystkie czy tylko polskie. Na stronie goNET.TV podają, że stacji jest ponad 25tysięcy. Jest możliwość dodania kolejnych stron ze stacjami radiowymi?

**Comment by hevet** [comment]
Obecnie przy próbie uruchomienia wyskakuje błąd

`Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.gonettv\main.py", line 862, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.gonettv\main.py", line 860, in router
                                                       home()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.gonettv\main.py", line 241, in home
                                                       logged,dod = login2()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.gonettv\main.py", line 223, in login2
                                                       usl2 = re.findall('<span title=.*?>([^<]+)',d,re.DOTALL)[0].replace('  ','')
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--`

**Comment by tete90** [comment]
Gonet wer.(plugin.video.gonettv-1.3) przestał działać. Można się zalogować, ale nie wyświetla telewizji i nie odpala vod. Bardzo proszę o poprawkę, oczywiście w miarę wolnego czasu. Pozdrawiam!
