### ISSUE TITLE
IplaTV Nie działa.

### ISSUE THREAD

**Issue by LukaszZdunek** [mbebe/blomqvist#575]
Cześć,

Proszę o pomoc IplaTVmb nie działa na Windows 10 Kodi 18.9 oraz na Raspberry Pi 4 Kodi 19.1

Poniżej logi proszę o pomoc.

`2021-06-22 17:28:02.382 T:8152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'result'
                                            Traceback (most recent call last):
                                              File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.iplatvmb\main.py", line 1095, in <module>
                                                ListContent(exlink,page)
                                              File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.iplatvmb\main.py", line 265, in ListContent
                                                items,itemss,npage = IPLA().getContent(categid,page)
                                              File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.iplatvmb\main.py", line 771, in getContent
                                                self.getSesja()
                                              File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.iplatvmb\main.py", line 921, in getSesja
                                                self.DANE=self.sesja(data)
                                              File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.iplatvmb\main.py", line 579, in sesja
                                                sesja=data['result']['session']
                                            KeyError: 'result'
                                            -->End of Python script error report<--
2021-06-22 17:28:02.431 T:13388   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.iplatvmb/?image=http%3a%2f%2fipla.pluscdn.pl%2fp%2fredb%2ffh%2ffhaygcsr1w47sp6a17f4vhowwmwsanw1.jpg&mode=listContent&movie=True&moviescount=0&name=%c5%9awi%c4%99ty&page=0&url=5017754%7cnull
2021-06-22 17:28:02.454 T:12884   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iplatvmb/?image=http%3a%2f%2fipla.pluscdn.pl%2fp%2fredb%2ffh%2ffhaygcsr1w47sp6a17f4vhowwmwsanw1.jpg&mode=listContent&movie=True&moviescount=0&name=%c5%9awi%c4%99ty&page=0&url=5017754%7cnull) failed
`

**Comment by LukaszZdunek** [comment]
I log z Raspberry 

`/rpc/drm/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xc77c1b98>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.iplatvmb/main.py", line 1093, in <module>
                                                       IPLA().PlayIpla(exlink)
                                                     File "/storage/.kodi/addons/plugin.video.iplatvmb/main.py", line 953, in PlayIpla
                                                       acc=self.checkAccess(id_)
                                                     File "/storage/.kodi/addons/plugin.video.iplatvmb/main.py", line 937, in checkAccess
                                                       data = getRequests('https://b2c-www.redefine.pl/rpc/drm/', data = POST_DATA, headers=self.HEADERS)
                                                     File "/storage/.kodi/addons/plugin.video.iplatvmb/main.py", line 328, in getRequests
                                                       content=sess.post(url,headers=headers,json=data, params=params, verify=False).json()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 590, in post
                                                       return self.request('POST', url, data=data, json=json, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPSConnectionPool(host='b2c-www.redefine.pl', port=443): Max retries exceeded with url: /rpc/drm/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xc77c1b98>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   -->End of Python script error report<--
                                                   
2021-06-22 17:37:13.707 T:1569     INFO <general>: Python interpreter stopped
2021-06-22 17:37:13.748 T:885     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.iplatvmb/?mode=playtvs&url=bdc26e9c07851f0d8f16a2cb7144d7e0%7Cnull&page=0&moviescount=0&movie=True&name=%C5%9Awi%C4%99ty+-+Odcinek+128&image=http%3A%2F%2Fipla.pluscdn.pl%2Fp%2Fvm2images%2F77%2F773e2i4g2abtb9cryw9m5v7j54br84sh.jpg]`

**Comment by LukaszZdunek** [comment]
Przepraszam za zawracanie głowy :) IPLA była blokowana przez PiHole ale udało się na to wpaść :)
