### ISSUE TITLE
PlayerPLmb 

### ISSUE THREAD

**Issue by motomouse** [mbebe/blomqvist#587]
Kodi wersja 19.1
PlayerPLmb wersja 1.9

Kanały Eurosportu od 3 do 9 wyrzucają błąd jak poniżej. Kanały 1 i 2 działają normalnie. 

`2021-08-02 13:26:21.892 T:16439    INFO <general>: CPythonInvoker(12, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playermb/main.py): script successfully run
2021-08-02 13:26:22.205 T:16439    INFO <general>: Python interpreter stopped
2021-08-02 13:26:29.352 T:16471    INFO <general>: initializing python engine.
2021-08-02 13:26:30.851 T:16471   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'player.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-08-02 13:26:30.985 T:16471   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'konto.tvn.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-08-02 13:26:31.118 T:16471   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'player.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-08-02 13:26:31.685 T:16471   ERROR <general>: Skipped 1 duplicate messages..
2021-08-02 13:26:31.685 T:16471   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'widevine'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playermb/main.py", line 931, in <module>
                                                       PLAYERPL().playvid(exlink)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playermb/main.py", line 508, in playvid
                                                       stream_url, license_url, subtitles = self.getPlaylist(str(id))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playermb/main.py", line 478, in getPlaylist
                                                       widev=vid['video']['protections']['widevine']['src']
                                                   KeyError: 'widevine'
                                                   -->End of Python script error report<--
                                                   
2021-08-02 13:26:32.002 T:16471    INFO <general>: Python interpreter stopped
2021-08-02 13:26:32.014 T:15101   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.playermb/?mode=playvid&url=4890070%3Akanal&page=1&moviescount=0&movie=True&name=EUROSPORT+9+HD&image=https%3A%2F%2Fr-scale-b4.dcs.redcdn.pl%2Fscale%2Fo2%2Ftvnplayer%2Fportal-uat%2Fupload%2Flive%2F5095018%2Fimages%2F50858904%3Fdsth%3D200%26dstw%3D400%26srcmode%3D0%26srcx%3D0%26srcy%3D0%26quality%3D65%26type%3D0%26srcw%3D1%2F1%26srch%3D1%2F1]
2021-08-02 13:26:36.622 T:16476    INFO <general>: initializing python engine.
2021-08-02 13:26:38.091 T:16476   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'player.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-08-02 13:26:38.221 T:16476   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'konto.tvn.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-08-02 13:26:38.359 T:16476   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'player.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-08-02 13:26:38.879 T:16476   ERROR <general>: Skipped 1 duplicate messages..
2021-08-02 13:26:38.878 T:16476   ERROR <general>: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'r.dcs.redcdn.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(`

**Comment by michael112** [comment]
Streamy Eurosportu 3-9, tak samo jak dodatkowe transmisje z wydarzeń olimpijskich, nie mają DRMu i trzeba je inaczej wrzucać do odtwarzania.

**Comment by rysson** [comment]
@mm1992 dodał Eurosport, jest w kandydacie na [1.12](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.11.13).
