### ISSUE TITLE
Playermb Katalogi KeyError

### ISSUE THREAD

**Issue by AdamKonefal** [mbebe/blomqvist#616]
Niektóre katalogi mają błędy klucza podczas pobierania adresu URL obrazu.

> ERROR: GetDirectory - Error getting plugin://plugin.video.playermb/?image=https%3a%2f%2fr-scale-a0.dcs.redcdn.pl%2fscale%2fo2%ftvn%2fweb-content%fm%fp24%fi%2f931a
->End of Python script error report <-
Key Error 'pc'
foto = f['images']['pc'][0]['mainurl']
File "storage/.../org.xmbc.kodi/files/.kodi/add-ons/plugin.video.playermb/main.py", line 698, in ListEpizody
PLAYERPL().ListyEpizody (exlink)
File "storage/.../org.xmbc.kodi/files/.kodi/add-ons/plugin.video.playermb/main.py", line 914, in <module>
Traceback (most recent call last):
Error Contents: 'pc'
Error Type: <type 'exceptions.KeyError'>

Przykładem tego jest Dzień Dobry TVN sezon 34 i 35.

Katalogi nie są dostępne, mimo że są dostępne na stronie internetowej.

Dzięki!!

**Comment by hevet** [comment]
Dziwne, na stronie nie mogę znaleźć w ogóle tych sezonów, są tylko odcinki podzielone na części.

**Comment by AdamKonefal** [comment]
Nie wiem, dlaczego wtyczka numeruje sezony, ale sezony 34 i 35 odpowiadają SIERPIEŃ 2021 i WRZESIEŃ 2021 na stronie.

**Comment by AdamKonefal** [comment]
Zamieniłem to (line 698)
```
foto = f['images']['pc'][0]['mainUrl']
foto = 'https:' + foto if foto.startswith('//') else foto
```
na to
```
try:
    foto = f['images']['pc'][0]['mainUrl']
    foto = 'https:' + foto if foto.startswith('//') else foto
except KeyError:
    foto = None
```
a teraz wszystko działa.

**Comment by hevet** [comment]
Jesteś w stanie udostępnić tutaj zmodyfikowany plik?

**Comment by hevet** [comment]
@AdamKonefal działa, dzięki :)

**Comment by Mariusz89B** [comment]
Sprawdz czy w f[ ] jest inne zrodlo zdjecia, wywala keyerror bo brakuje w zdjecia ['images']['pc'].

**Comment by rysson** [comment]
Problem powinien być naprawiony w [1.9.901](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.9.901) (taka alfa). Proszę o test desperatów :-P
