### ISSUE TITLE
Spotowa

### ISSUE THREAD

**Issue by sahuja78** [mbebe/blomqvist#623]
The addon is not working properly again. Tried sportsbay and gives an error when i try to get into sub folder.

**Comment by SzymonKaminski** [comment]
Sportsbay is not working most likely due to the lawsuit, it's not issue of the Sportowa addon. You can read more about it at https://torrentfreak.com/several-sportsbay-pirate-streaming-sites-go-dark-in-wake-of-us-lawsuit-210924/

**Comment by sahuja78** [comment]
gor it. thanks

**Comment by daplam84** [comment]
The webpage was update to https://www.sportsbay.es, i updated the url in the maintv file, and got this error.

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.PLsportowo/maintv.py", line 3008, in <module>
                                                getsportsbayschedule()
                                              File "/storage/.kodi/addons/plugin.video.PLsportowo/maintv.py", line 496, in getsportsbayschedule
                                                imagi = parseDOM((parseDOM(link,'td', attrs={'class': "type"})[1]),'img',ret='src')[1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-09-28 20:11:52.867 T:2444829504   

ERROR: GetDirectory - Error getting plugin://plugin.video.PLsportowo/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.PLsportowo%2fresources%2fsoccer.png&mode=getsportsbayschedule&title=Football&url=https%3a%2f%2fsportsbay.es%2fsports%2ffootball%2f1
2021-09-28 20:11:52.893 T:3011855744  

 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.PLsportowo/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.PLsportowo%2fresources%2fsoccer.png&mode=getsportsbayschedule&title=Football&url=https%3a%2f%2fsportsbay.es%2fsports%2ffootball%2f1) failed

**Comment by sahuja78** [comment]
can someone see why that updated url is not working ?
thanks
