### ISSUE TITLE
Kodi 18.9 na enigma2 - zgemma h9 twin problem z wtyczkami video

### ISSUE THREAD

**Issue by kunraf** [mbebe/blomqvist#630]
Od kilku dni problemy z wtyczkami video z repo mbebe. 
Netflix, tvp działają, na wtyczkach mbebe jest błąd, dziennik zdarzeń nic nie rejestruje

https://user-images.githubusercontent.com/49157039/135719997-06a98dcc-1744-4740-8f9e-b274250282ec.mp4

**Comment by DeGH** [comment]
Problem z playerem jest znany. Wkrótce @rysson powinien to ogarnąć.

**Comment by kunraf** [comment]
a pozostałe wtyczki - hejo, internetowa, cda, polsatgo?
to ten sam problem?, jeszcze tydzień temu wszystkie chodziły

**Comment by hustlereq** [comment]
W nawiązaniu do tematu: mam taką samą konfigurację (Zgemma H9Twin/Open ATV 6.4 z zainstalowanym Kodi), faktycznie aktualizacja wtyczki Player do 1.9.5 spowodowała problemy (raportowałem w innym wątku), jednak po cofnięciu się do wtyczki 1.9 wszystko działa w jak najlepszym porządku. Ipla przestała działać, ale to zrozumiałe, bo serwis został zastąpiony przez Polsat Box GO (czy jakoś tak), o czym wtyczka Ipli informowała komunikatem. Innych wtyczek nie instalowałem.

**Comment by rysson** [comment]
To jest jakiś generalny problem z obsługą SSL (raczej certyfikatów niż samego protokołu). PlayreMB 1.9 miał wprost zapisane, żeby ignorował SSL, co nie jest najbardziej bezpiecznym rozwiązaniem. Developerska wersja 1.9.904 ma opcję, w której można  SSL wyłączyć i wtedy działa tak jak 1.9.
Co nie rozwiązuje problemu, dlaczego w ogóle jest błąd SSL.

**Comment by hustlereq** [comment]
A jakby zrobić domyślnie wyłączony ten ssl? To wtedy uznać by można, że 
wtyczka działa, nie? :D


------ Wiadomość oryginalna ------
Od: "rysson" ***@***.***>
Do: "mbebe/blomqvist" ***@***.***>
DW: "hustlereq" ***@***.***>; "Comment" 
***@***.***>
Data: 03.10.2021 20:13:27
Temat: Re: [mbebe/blomqvist] Kodi 18.9 na enigma2 - zgemma h9 twin 
problem z wtyczkami video (#630)

**Comment by rysson** [comment]
No to jest przypudrowanie problemu. Mam silną awersję do ignorowania błędów bezpieczeństwa, szczególnie jak jakieś dane wrażliwe idą (dane do logowania). Niby tylko przejąc można bez trudu konto do playera, ale sama idea jest bardzo zła.

Pewnym kompromisem mogłoby być wykrycie błędu i rzucenie komunikatu, weź sobie oglądaczu i przestaw.

**Comment by hustlereq** [comment]
o to to to!

------ Wiadomość oryginalna ------
Od: "rysson" ***@***.***>
Do: "mbebe/blomqvist" ***@***.***>
DW: "hustlereq" ***@***.***>; "Comment" 
***@***.***>
Data: 03.10.2021 20:18:58
Temat: Re: [mbebe/blomqvist] Kodi 18.9 na enigma2 - zgemma h9 twin 
problem z wtyczkami video (#630)

**Comment by plonkaadam** [comment]
> No to jest przypudrowanie problemu. Mam silną awersję do ignorowania błędów bezpieczeństwa, szczególnie jak jakieś dane wrażliwe idą (dane do logowania). Niby tylko przejąc można bez trudu konto do playera, ale sama idea jest bardzo zła.

no ale akurat logowanie przechodziło w wersji 1.9.5, błąd pojawiał się dopiero na trzecim poziomie wyboru kategorii. Czy to oznacza że tylko niektóre zapytania mają włączone sprawdzanie SSL?

**Comment by DeGH** [comment]
@plonkaadam ogólnie jest problem z certyfikatami w waszych systemach (https://kodi.wiki/view/SSL_certificates).
Czy twój system na tej malinie jest aktualny? Czy w ogóle próbowałeś aktualizować?
Możesz spróbować wymusić aktualizację certyfikatów komendą: sudo update-ca-certificates
Dodatkowo komendą: sudo pip3 list  możesz sprawdzić czy masz zainstalowane paczki "certifi" oraz "cryptography" i w jakich wersjach.
No i jeszcze jedna opcja to sprawdzenie paczki "certifi" w Kodi.
Ustawienia > Ustawienia systemu > Dodatki > Zarządzaj zależnościami > certifi
Sprawdź czy jest to aktywne i w najnowszej wersji, ew. możesz spróbować to przeinstalować.

**Comment by plonkaadam** [comment]
System aktualny, update puszczam co parę tygodni, sprawdzę resztę później jak znajdę czas.
Ale nie takie było pytanie - pytam jak to możliwe że część requestów (na przykład logowanie) przechodzi. Czy to oznacza że sprawdzanie SSL jest wyłączone do logowania a włączone do innych operacji?

**Comment by kunraf** [comment]
gdzie znajde repo od mbebe sprzed ostatniej aktualiazacji? sam player nic mi nie daje

**Comment by rysson** [comment]
@plonkaadam, dzisiaj odsypiam. Ale w między czasie możesz na tej maszynie uruchomić testowy skrypt?

```python
import requests
import urllib3

url='https://player.pl/playerplus'

with requests.Session() as sess:
    with sess.get(url) as resp:
        print(len(resp.text))

http = urllib3.PoolManager()
resp = http.request('GET', url)
text = resp.data.decode('utf-8')
print(len(text))
```

Aby uruchomić skrypt (powiedzmy, że go masz w `/tmp/c.py`) razem z modułami kodi, to możesz wpisać w konsoli:
```bash
PYTHONPATH=$(ls -d $HOME/.kodi/addons/script.module.*/lib | tr '\n' ':') python /tmp/c.py
```

Może sprawniej było na Discordzie się skomunikować jeśli idzie o dyskusję o poprawkach poprawek?

Dobranoc :-)

**Comment by plonkaadam** [comment]
Wynik taki jakiego można było się spodziewać

```
23804
Traceback (most recent call last):
  File "./skrypt.py", line 11, in <module>
    resp = http.request('GET', url)
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='player.pl', port=443): Max retries exceeded with url: /playerplus (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

```

`sudo update-ca-certificates`
nic nie zrobiło (0 updated)

certifi i cryptography są na liście, zaktualizowałem ich wersję ale to też nic to nie zmieniło.
Zaktualizowałem teraz cały system i wszystkie pakiety, nadal to samo

**Comment by rysson** [comment]
Oprócz naprawy certyfikatów nigdy nie wiadomo, czy się u kogoś nie popsują, więc nie zrezygnowałem z pomysłu pytania co zrobić przy błędach SSL.
Przykład działania (`yyy` to sztuczne odwołanie do https://wrong.host.badssl.com, na końcu się wywala bo tam nie ma JSON-a).

https://user-images.githubusercontent.com/5898312/136266747-da6690b3-cb28-41f3-9ac4-dea5382ee96b.mp4

**Comment by rysson** [comment]
Wystawiłem pull-request z ostatnimi poprawkami: mbebe/blomqvist_srcs#2
Poprosiłem @mbebe o przejrzenie, akceptację i wydanie. Wersję oznaczyłem jako 1.10.

@kunraf, zerknij czy dla playera jest lepiej. Resztę masz w tym repo, w tym własnie piszemy: https://github.com/mbebe/blomqvist/tree/master/zips
Zawsze możesz zablokować aktualizację i wyjąc sobie zip-y w tej wersji, która Ci pasuje i zainstalować ręcznie. Chyba zawsze jest parę wersji wstecz. @mbebe  usuwa najstarsze, żeby nie było za dużego śmietnika. Ale i one są, bo w końcu repozytorium git.

Jeśli nie masz dla nas logów z tym co się wywala, to więcej nie możemy pomóc. W takim razie prosiłbym o zamknięcie zgłoszenia, bo wtyczka z filmu jest poprawiona, miejsce starszych wtyczek wskazane.
