### ISSUE TITLE
Błąd odtwarzania na PVR IPTV Simple Client

### ISSUE THREAD

**Issue by hevet** [mbebe/blomqvist#633]
Mam problem z odtwarzaniem kanałów TV na PVR IPTV Simple Client. Problem występuje na Kodi 19.1 na Raspberry Pi z Libreelec. Problem nie występuje na Kodi 19.1 zainstalowanym na Windows 10. Przykładowy log z Polsat Box Go. Problem występuje też na wtyczce TVP.pl, Player.
`Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.pgobox/main.py", line 1216, in <module>
                                                       IPLA().PlayIpla(exlink)
                                                     File "/storage/.kodi/addons/plugin.video.pgobox/main.py", line 1065, in PlayIpla
                                                       if '|' in id_ :
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--`

**Comment by Axis963** [comment]
U mnie na Libreelec, tylko ze na Kodi 18, dziala lista zrobiona z C+VOD, PGOBOX, TVP, Player, Wp Pilot, wszystko bez problemu 🤔

**Comment by hevet** [comment]
@Axis963 na Kodi 18.9 ta lista też działała, po przesiadce na 19.1 wywala blędu

**Comment by mbebe** [comment]
Pokaz kawalek listy.

**Comment by hevet** [comment]
@mbebe  , kawałek listy z kanałami z Polsat Box Go i TVP.pl , te nie działają

`#EXTINF:0 tvg-id="TVP Kultura 2", TVP Kultura 2
plugin://plugin.video.TVP.pl/?mode=palyLiveVideo&amp;ex_link=http%3A%2F%2Ftvpstream.vod.tvp.pl%2Fsess%2Ftvplayer.php%3Fobject_id%3D51161266
#EXTINF:0 tvg-id="TVP Historia 2", TVP Historia 2
plugin://plugin.video.TVP.pl/?mode=palyLiveVideo&amp;ex_link=http%3A%2F%2Ftvpstream.vod.tvp.pl%2Fsess%2Ftvplayer.php%3Fobject_id%3D52451208
#EXTINF:0 tvg-id="TVP 3 Bydgoszcz", TVP 3 Bydgoszcz
plugin://plugin.video.TVP.pl/?mode=palyLiveVideo&amp;ex_link=http%3A%2F%2Ftvpstream.vod.tvp.pl%2Fsess%2Ftvplayer.php%3Fobject_id%3D14813071
#EXTINF:0 tvg-id=TVP e-szkoła, TVP e-szkoła
plugin://plugin.video.TVP.pl/?mode=palyLiveVideo&amp;ex_link=http%3A%2F%2Ftvpstream.vod.tvp.pl%2Fsess%2Ftvplayer.php%3Fobject_id%3D51466523
#EXTINF:0 tvg-id=POLAND IN, POLAND IN


#EXTINF:0 tvg-id="Polsat", Polsat
plugin://plugin.video.pgobox/?mode=playtvs&amp;url=23985&amp;page=0&amp;moviescount=0&amp;movie=True&amp;name=POLSAT&amp;image=http%3A%2F%2Fipla.pluscdn.pl%2Fp%2Fredb%2F9p%2F9p5nq31mdscc5xxw97ctuuphjqd48a8q.jpg
#EXTINF:0 tvg-id="Polsat 2", Polsat 2
plugin://plugin.video.pgobox/?mode=playtvs&amp;url=10258&amp;page=0&amp;moviescount=0&amp;movie=True&amp;name=POLSAT+2+HD&amp;image=http%3A%2F%2Fipla.pluscdn.pl%2Fp%2Fredb%2Fjq%2Fjq2o2cf53xychm7ivuy5rzbgjj7kmqwx.jpg
#EXTINF:0 tvg-id="Nick JR.", Nick JR.
plugin://plugin.video.pgobox/?mode=playtvs&amp;url=10250&amp;page=0&amp;moviescount=0&amp;movie=True&amp;name=NICK+JR&amp;image=http%3A%2F%2Fipla.pluscdn.pl%2Fp%2Fredb%2Fgt%2Fgt4e2y3y2u5xz5h488yvwmf5nc5s7u5m.jpg
#EXTINF:0 tvg-id="Disney Junior", Disney Junior
plugin://plugin.video.pgobox/?mode=playtvs&amp;url=10905&amp;page=0&amp;moviescount=0&amp;movie=True&amp;name=DISNEY+JUNIOR&amp;image=http%3A%2F%2Fipla.pluscdn.pl%2Fp%2Fredb%2Frb%2Frbo1j2mdzxg3fhdgenycutwow539fgub.jpg
#EXTINF:0 tvg-id="BBC CBEEBIES", BBC CBEEBIES
plugin://plugin.video.pgobox/?mode=playtvs&amp;url=13334&amp;page=0&amp;moviescount=0&amp;movie=True&amp;name=BBC+CBEEBIES&amp;image=http%3A%2F%2Fipla.pluscdn.pl%2Fp%2Fredb%2F6k%2F6kxdehmjkwp6gke6x1ywwdbum3mka6ny.jpg`
