### ISSUE TITLE
Vectra.pl

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#634]
Ponizej wtyczka do vectra.
Bez podzielenia sie jakimis danymi z pakietem lub jakimis, gdzie sa np. filmy dalej nie rusze.
Zrobilem tylko to, do czego mialem dostep
[plugin.video.vectrapl-0.3.zip](https://github.com/mbebe/blomqvist/files/7295741/plugin.video.vectrapl-0.3.zip)
.

**Comment by mbebe** [comment]
Na maila napisze.

**Comment by arturrsl** [comment]
Dziękuję za udostępnienie. Przy próbie zalogowania również pojawia się komunikat "Missing device". Kodi 19.0

**Comment by mbebe** [comment]
ta nowa wersja 0.3?

**Comment by zuzia-dev** [comment]
Owszem, skutecznie :)

**Comment by kkrupaa** [comment]
Cześć,
Na wstępie dzięki za udostępnienie wtyczki @mbebe . Na prawdę kawał dobrej roboty :)

Próbuje ją uruchomić na Kodi na Raspberry PI (Kodi (18.9). Platform: Linux ARM (Thumb) 32-bit).

Wszystko wygląda dobrze, udało mi się zalogować i poprawnie wyświetla się lista kanałów.
Natomiast w momencie gdy próbuje odtworzyć jeden z kanałów, nic się nie dzieje :(

W logu widzę błąd 403 - więc tak jakby coś nie tak z uprawnieniami, jednak wszystko działa poprawnie gdy np. próbuję w przeglądarce. Co ciekawe z przeglądarki też leci podobny request - i tez jest dla niego odpowiedź 403, ale jednak kanał się poprawnie uruchamia.

Poniżej log z kodi:
```
2021-11-02 09:52:47.272 T:1457516768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vectrapl/main.py", line 99, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.vectrapl/main.py", line 80, in router
                                                Vectra.PlayTV(exlink, 'channel')
                                              File "/home/osmc/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 624, in PlayTV
                                                vsessid = jsdata.get("videoSession",None).get("videoSessionId",None)
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2021-11-02 09:52:47.489 T:1916023728   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vectrapl/?moviescount=0&url=85c8b8ca-xxxx-42cd-8a93-2afd5cfc3975&movie=True&image=https%3A%2F%2Flh3.googleusercontent.com%2F6MFnPIw4dpnvOL9j4bX8BKl2-ZDFIqNtPQeXgcjZKox30T902S_xqblYUPIVjnOO3u8xxxxM4O2EPghJHqnxgAhC9VqWlW-1YQSvLUAAfg81PjD2jihV&title=Polsat+HD&mode=playtv&page=0]
2021-11-02 09:53:46.163 T:1631527136  NOTICE: ES: Client  from ::ffff:172.25.25.94 timed out
2021-11-02 09:55:22.840 T:1431269600  NOTICE: [script.module.inputstreamhelper] User had declined an update on 2021-11-01 17:31
2021-11-02 09:55:22.961 T:1916023728  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.vectrapl/?moviescount=0&url=5234b234-647a-47b9-xxxx-b21ed321140c&movie=True&image=https%3A%2F%2Flh3.googleusercontent.com%2FYPz0fIDeB_PgY-JaDxRzTzvHswynPxu2xTOhi0zumZ0dfz5e24iFR99sKyY2afqk-jL9_P3qA0tmq_2-xxxxxx-Us9yJ3plxYCoQfw&title=TVP+1+HD&mode=playtv&page=0
2021-11-02 09:55:22.967 T:1481625824  NOTICE: Creating InputStream
2021-11-02 09:55:25.234 T:1481625824   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2021-11-02 09:55:25.234 T:1481625824   ERROR: CCurlFile::Open failed with code 403 for https://api.tvonline.vectra.pl/player/video/2/drm/widevine?videoSessionId=1aa96c04-xxxx-4a8b-a901-4ed01596d017&videoAssetId=4:
2021-11-02 09:55:25.235 T:1481625824   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2021-11-02 09:55:25.235 T:1481625824   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2021-11-02 09:55:25.335 T:1481625824   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2021-11-02 09:55:25.337 T:1481625824   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vectrapl/?moviescount=0&url=5234b234-647a-47b9-xxxx-b21ed321140c&movie=True&image=https%3A%2F%2Flh3.googleusercontent.com%2FYPz0fIDeB_PgY-JaDxRzTzvHswynPxu2xTOhi0zumZ0dfz5e24iFR99sKyY2afqk-jL9_P3qA0tmq_2-xxxxxx-Us9yJ3plxYCoQfw&title=TVP+1+HD&mode=playtv&page=0]
2021-11-02 09:55:25.337 T:1481625824  NOTICE: CVideoPlayer::OnExit()
2021-11-02 09:55:25.394 T:1916023728  NOTICE: CVideoPlayer::CloseFile()
2021-11-02 09:55:25.394 T:1916023728  NOTICE: VideoPlayer: waiting for threads to exit
2021-11-02 09:55:25.394 T:1916023728  NOTICE: VideoPlayer: finished waiting
```
Będę wdzięczny za pomoc w uruchomieniu tego.

Jeśli potrzeba dodatkowych informacji czy logów to oczywiście dostarczę wszystko  - tylko dajcie znać co jest potrzebne.

**Comment by kkrupaa** [comment]
Udało mi się rozwiązać problem. Teraz wszystko działa jak należy :)
Gdyby ktoś napotkał na coś podobnego, to winna jest stara wersja biblioteki libwidevinecdm.so.
Niestety najnowsze wersje tej biblioteki także nie działają na Kodi 18.x (więc aktualizacja do najnowszej wersji nie pomaga).

Udało mi się pobrać odpowiednią wersję korzystając z poniższych poleceń:
```

sudo apt-get install gnupg
curl -s --compressed "https://wagnerch.github.io/ppa/buster/KEY.gpg" | sudo apt-key add -
sudo curl -s --compressed -o /etc/apt/sources.list.d/wagnerch-buster-ppa.list "https://wagnerch.github.io/ppa/buster/wagnerch-buster-ppa.list"
sudo apt-get update
sudo apt-get install --only-upgrade libc6
curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2252.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null
sudo reboot

```
Gdyby ktoś był zainteresowany szczegółami, to tutaj można znaleźć więcej informacji na ten temat:
https://github.com/xbmc/inputstream.adaptive/issues/678
