### ISSUE TITLE
CanalPLUS-VOD - nie działa generator listy m3u

### ISSUE THREAD

**Issue by zuzia-dev** [mbebe/blomqvist#639]
@mbebe możesz w wolnej chwili rzucić okiem?

```
2021-10-09 21:58:41.543 T:140674088929024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/zuzia/.kodi/addons/plugin.video.canalplusvod/main.py", line 1474, in <module>
                                                GenList()
                                              File "/home/zuzia/.kodi/addons/plugin.video.canalplusvod/main.py", line 196, in GenList
                                                m3u8.addM3UChannel(count, item['title'], item['image'], grouptitle, count, canalurl)
                                              File "/home/zuzia/.kodi/addons/plugin.video.canalplusvod/playlist.py", line 13, in addM3UChannel
                                                genreStr = unicode(group)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--
2021-10-09 21:58:41.688 T:140674080536320   ERROR: GetDirectory - Error getting plugin://plugin.video.canalplusvod/?image=%2fhome%2fzuzia%2f.kodi%2faddons%2fplugin.video.canalplusvod%2fresources%2f..%2ficon.png&mode=genlist&movie=True&moviescount=0&name=Generator%20listy%20m3u&page=1&url
2021-10-09 21:58:41.698 T:140674752066304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canalplusvod/?image=%2fhome%2fzuzia%2f.kodi%2faddons%2fplugin.video.canalplusvod%2fresources%2f..%2ficon.png&mode=genlist&movie=True&moviescount=0&name=Generator%20listy%20m3u&page=1&url) failed
```

Kodi 18.9.

**Comment by Mariusz89B** [comment]
Polske znaki w nazwie, zmien na:
`m3u8.addM3UChannel(count, item['title'].decode('utf-8'), item['image'], grouptitle, count, canalurl)`

**Comment by PrzemekSkw** [comment]
Witam, wygenerowałem liste i wgrałem na moim serwerze emby. Widzę tam tylko kanały live (które nie działają). Czy za pomocą tej listy można oglądać zawartość VOD?
Pozdrawiam.
