### ISSUE TITLE
CanalPLUS-VOD nie działa generowanie list m3u 

### ISSUE THREAD

**Issue by lorek123** [mbebe/blomqvist#659]
Kodi w wersji: 19.3
plugin w wersji: 1.7.4.8
Po kliknięciu generuj listy m3u pojawia się w logach błąd:
````
2021-11-01 13:56:30.030 T:94992   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "/home/lorek/.kodi/addons/plugin.video.canalplusvod/main.py", line 1475, in <module>
                                                       GenList()
                                                     File "/home/lorek/.kodi/addons/plugin.video.canalplusvod/main.py", line 159, in GenList
                                                       profile = xbmc.translatePath(addon.getAddonInfo('profile')).decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2021-11-01 13:56:30.049 T:94992    INFO <general>: Python interpreter stopped
```

**Comment by Mariusz89B** [comment]
W main.py linia 159 zmien na:

```python
try:
     profile = xbmc.translatePath(addon.getAddonInfo('profile'))
except:
     profile = xbmc.translatePath(addon.getAddonInfo('profile')).decode('utf-8')
```

**Comment by lorek123** [comment]
Zapis pliku nie działa:
```
2021-11-01 16:36:14.024 T:225642   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeEncodeError'>
                                                   Error Contents: 'ascii' codec can't encode character '\xd3' in position 2798: ordinal not in range(128)
                                                   Traceback (most recent call last):
                                                     File "/home/lorek/.kodi/addons/plugin.video.canalplusvod/main.py", line 1478, in <module>
                                                       GenList()
                                                     File "/home/lorek/.kodi/addons/plugin.video.canalplusvod/main.py", line 202, in GenList
                                                       m3ufile.write(m3u8.getM3UList())
                                                   UnicodeEncodeError: 'ascii' codec can't encode character '\xd3' in position 2798: ordinal not in range(128)
                                                   -->End of Python script error report<--
```

**Comment by Mariusz89B** [comment]
@lorek123 Ciekawe ze tobie nie wywala blad xbmcvfs. Tu poprawka:
https://drive.google.com/file/d/1Cg12-qquZoopSw-yDbqFs8f9bNOFP0R1/view?usp=sharing

**Comment by hevet** [comment]
Poprawiona wersja z kategorią Lifestyle zamiast Fun&Info 
[plugin.video.canalplusvod-1.7.4.9_v3.zip](https://github.com/mbebe/blomqvist/files/7698781/plugin.video.canalplusvod-1.7.4.9_v3.zip)
