### ISSUE TITLE
Player brak programu w pakiecie w 1.10

### ISSUE THREAD

**Issue by klosiu** [mbebe/blomqvist#673]
Hej,
od wersji 1.10 część programów jest oznaczona jako brak w pakiecie (np. masterchef, kuchenne rewolucje, lego masters).
Zorientowałem się, bo przed chwilką zainstalowałem na nowo libre elec i od nowa player i widzę, że kilka rzeczy nie działa, które działały 30 minut temu. Na stronce jest ok, więc zaciągnąłem 1.9.5, zainstalowałem i normalnie mogę oglądać te programy. Zrobiłem raz jeszcze aktualizację do 1.10 i znów są oznaczone jako niedostępne w pakiecie. Więc cofnąłem do 1.9.5 i wyłączyłem automatyczne aktualizacje póki co.

Łączę się z Polski, bez vpn. Raspberry 3, Libre elec 9.2.8 na Kodi 18.
Jak trzeba jakieś logi, lub inne konkrety to proszę o info co mam podesłać.

**Comment by rysson** [comment]
@klosiu, a to ciekawe, co 1.10 to w sumie podbicie wersji 1.9.5.
Choć jeszcze jedną zmianę widzę i to tylko w plakatach, przyjrzę się jej w niedzielę.
Logi chętnie łyknę. Najlepiej od restartu taka sama ścieżka wejścia dla obu wersji.

Chyba, że masz `Exception` w logach w 1.10 to może wystarczyć na początek.

**Comment by martiinezz** [comment]
Cześć - mam to samo od wczoraj - nagle większość pokazuje (brak w pakiecie) mimo, że na stronce playera mogę materiał odtwarzać. Dla przykładu Wielkie teorie darwina są ok - Misje, Pajęczyna i masa innych (brak w pakiecie) - wersja 1.10.
Widzę takie błędy:

2021-11-20 09:34:55.035 T:1799328640 WARNING: PLAYER.PL: getRequests('https://player.pl/playerapi/subscriber/bookmark', data=None, headers={'API-ProfileUid': '', 'API-DeviceInfo': '2e520525f3677e0a;2e520525f25e374d;Android;9;566838e5ecaf4ddd;1.0.38(62);', 'Host': 'player.pl', 'X-NewRelic-ID': 'VQEOV1JbABABV1ZaBgMDUFU=', 'API-SubscriberPub': '65b1e18f20ee017a2dbe1717d34f2363', 'API-DeviceUid': '338d647001efa1b8', 'API-Authentication': '1a24ac61-8784-470d-a8e9-9fee0b209f41', 'API-SubscriberHash': 'f70ff9927fb7d304ee84e163fe3849a963ae630b32ed297fad93d131734630b6476dcb2a45405b1f4972fb2c64a84937', 'Authorization': 'Basic', 'User-Agent': 'okhttp/3.3.1 Android'}, params={'platform': 'ANDROID_TV', 'type': 'FAVOURITE', '4K': 'true'})
2021-11-20 09:35:12.783 T:1807721344 WARNING: PLAYER.PL: ENTER: mode=' ', name='40 kontra 20 - [COLOR khaki]([I]brak w pakiecie[/I])[/COLOR]', exlink='4738763'
2021-11-20 09:35:12.965 T:1799328640   ERROR: GetDirectory - Error getting plugin://plugin.video.playermb/?image=https%3a%2f%2fr-scale-47.dcs.redcdn.pl%2fscale%2fo2%2ftvn%2fweb-content%2fm%2fp24%2fi%2fef41d488755367316f04fc0e0e9dc9fc%2fe069c5d1-700b-4e33-b913-e8024e43902b.jpg%3fsrcx%3d0%26srcy%3d0%26srcw%3d2048%26srch%3d1154%26type%3d1%26srcmode%3d0%26quality%3d65%26dstw%3d1920%26dsth%3d1080&mode=%20&movie=True&moviescount=0&name=40%20kontra%2020%20-%20%5bCOLOR%20khaki%5d(%5bI%5dbrak%20w%20pakiecie%5b%2fI%5d)%5b%2fCOLOR%5d&page=1&url=4738763
2021-11-20 09:35:12.969 T:1936741440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.playermb/?image=https%3a%2f%2fr-scale-47.dcs.redcdn.pl%2fscale%2fo2%2ftvn%2fweb-content%2fm%2fp24%2fi%2fef41d488755367316f04fc0e0e9dc9fc%2fe069c5d1-700b-4e33-b913-e8024e43902b.jpg%3fsrcx%3d0%26srcy%3d0%26srcw%3d2048%26srch%3d1154%26type%3d1%26srcmode%3d0%26quality%3d65%26dstw%3d1920%26dsth%3d1080&mode=%20&movie=True&moviescount=0&name=40%20kontra%2020%20-%20%5bCOLOR%20khaki%5d(%5bI%5dbrak%20w%20pakiecie%5b%2fI%5d)%5b%2fCOLOR%5d&page=1&url=4738763) failed

**Comment by martiinezz** [comment]
Tak to jednak coś z kodem - podgrałem w miejsce 1.10 to https://github.com/mbebe/blomqvist/blob/master/zips/plugin.video.playermb/plugin.video.playermb-1.9.zip i śmigają wszystkie poprzednio używane materiały, które w 1.10 mają status (brak w pakiecie). Pewnie jakiś mało oczywisty babol się wkradł.

**Comment by hevet** [comment]
Wgrałem wersję 1.9.5 i na razie te programy działają. Informacyjnie udostępniono TVN HD we wszystkich pakietach, a zablokowano ITVN, ITVN Extra, TVN24 International, które i tak są dla zagranicy ale działały przez kilka miesięcy w podstawowych pakietach.

**Comment by rysson** [comment]
Zabawne, TVN łamie swoje własne API. Stworzyli tablicę ID (115 tyś), które pozycje (filmy, sezony, seriale) są dozwolone, a które nie. Oparłem się na nich a tu sami olewają te dane.
Wygląda na to, że trzeba wrócić do chamskiego sprawdzania czy `ncPlus` albo `Canal+`. Żenada w moim mniemaniu.

**Comment by hevet** [comment]
Widać sami specjaliści tam pracują :P. Oby jeszcze nie namieszali z kanałami TV tak jak w Canal+ Online.

**Comment by martiinezz** [comment]
Pewnie więcej - może robią jakieś zmiany - a może programiści z łapanki - co w dużych korporacjach często się zdarza.

**Comment by rysson** [comment]
Wersja [1.10.1](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.10.1) do testów.

Jestem trochę sceptyczny co do tych zmian, bo w kodzie jest, że do video (nie folder) jeśli jest `ncPlus`, a teraz musiałem dodać forsowanie gdy nie `ncPlus`. Można się zastanowić, czy tego forsowania nie dać tylko dla folderów (np. sezonów itp.), ale choler wie co jeszcze wytną.

- forsowanie pozycji, które nie są dla nas, ale nie są `ncPlus` – dość brutalne, sterowana zaawansowaną flagą `Naprawiaj zepsute API` (domyślnie włączona)
- usuwanie duplikatów jeśli ID już był użyty, sterowane flagą `Usuwaj duplikaty` (domyślnie włączone), choć wypisuje w logach zawsze

@martiinezz, racja, w samych kuchniach mam:
```
2021-11-20 21:14:31.453 T:1300830 WARNING <general>: PLAYER.PL: item 1173187 ('Patent na Święta') already processed
2021-11-20 21:14:31.460 T:1300830 WARNING <general>: PLAYER.PL: item 52954 ('Kuchenne rewolucje') already processed
2021-11-20 21:14:31.479 T:1300830 WARNING <general>: PLAYER.PL: item 13280 ('Apetyt na miłość') already processed
2021-11-20 21:14:31.479 T:1300830 WARNING <general>: PLAYER.PL: item 9900 ('10 zadań specjalnych Michela Morana') already processed
```

**Comment by klosiu** [comment]
@rysson Dzięki za szybką reakcję. Dziś postaram się przetestować, choć podejrzewam, że ktoś mnie wyprzedzi.

**Comment by hevet** [comment]
Na szybko sprawdzone i u mnie działa dobrze. Dzięki 🙂

**Comment by hevet** [comment]
@rysson jednak znalazłem błąd.
Przykładowo Masterchef sezo 10, odcinek 1 i 13 widoczny jest jako folder, nie można ich odtworzyć.
Milionerzy sezon 10 - odcinek 457 to samo.

**Comment by rysson** [comment]
@hevet, ale to *false positive* czy same video zniknęło? Znaczy:

- pokazuje foldery, których nie ma na www?
- pokazuje foldery ale puste / z zawartością nie do odtworzenia ale na www da się je oglądać?

**Comment by klosiu** [comment]
Potwierdzam zachowanie zgłoszone przez @rysson.
Masterchef seria 10:

- Odcinek 13 jest widoczny jak folder. W poprzednich wersjach był widoczny jako zwykły odcinek. Żadne zachowanie nie jest prawidłowe, bo to jest jedynie zapowiedź odcinka z przyszłego tygodnia i nie można go obejrzeć na stronie Player.pl (choć widnieje tam z opisem Oglądaj Wkrótce)

- Odcinek 01 jest widoczny jak folder. W poprzednich wersjach był widoczny jako zwykły odcinek. Zachowanie z poprzednich wersji było prawidłowe. Odcinek jest dostępny na player.pl i można go normalnie tam oglądać. Być może znaczenie ma oznaczenie tego odcinka na stronie player.pl jako `odcinek specjalny`.

**Comment by hevet** [comment]
@rysson  Odcinek 457 Milionerów i 1 Masterchefa , normalnie odtwarza na stronie, w dodatku widoczny jako folder i nie można w niego wejść, więc nie wiadomo czy jest pusty :).

**Comment by hevet** [comment]
@rysson z ciekawostek mogę jeszcze dodać, że w dodatku wersja 1.9.5, wszystkie odcinki Masterchefa są widoczne tylko wtedy gdy w opcjach nie ma zaznaczonej opcji "Dostępne dla Ciebie", gdy ją zaznaczymy znika odcinek 1 i 13.

**Comment by michael112** [comment]
Najlepsze że na starszej wersji wtyczki (1.9) działa. Ja dzisiaj miałem problem z serialem 19+ (TVN7) który mi się w aktualnej wersji wtyczki wyświetlał jako 'brak w pakiecie'.

**Comment by rysson** [comment]
Do testów [1.10.2](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.10.2).

- Naprawa dostępu, teraz można oglądać gdy
    - video jest free (nie ma ani `payable` ani `ncPlus`)
    - jak płatne to musi być w `mylist`
- Dodane tytuły epizodów.
- Dodane zapowiedzi (data od kiedy będzie można oglądać).

Muszę oddać honor autorom, bo ja nie umiem czytać. Zamiast `payable` czytałem `playable`, co z deczka to zmienia znaczenia. Jeśli nie jest płatny to nie musi być na liście, na co ostatnio psioczyłem.

---

Podgląd dodatkowych dodatków.

![20211126-223732-350x96](https://user-images.githubusercontent.com/5898312/143657315-80a50c27-d57e-4216-a70c-20a52c5dca1b.png)

![20211126-223658-631x329](https://user-images.githubusercontent.com/5898312/143657322-4557f1ee-880d-403a-b8b7-3c33d52a4598.png)

**Comment by fr3sh** [comment]
Wygląda że ta wersja chodzi dzięki..

**Comment by SzymiB** [comment]
W wersji 1.10.2 pokazuje mi tylko kanały, które nie są dostępne w pakiecie, a np TVN w ogóle nie ma na liście.

**Comment by rysson** [comment]
Kolejna wersja [1.10.3](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.10.3) (nie ma to jak coś poprawiać, gdy się ledwo na oczy patrzy).

- naprawa kanałów TV.
- nazwa linku z minusem a labelka z półpauzą i tytułem  (pomięta oglądane).

**Comment by klosiu** [comment]
Coś nie tak. Wtyczka się wysypuje przy próbie otworzenia drugiego sezonu Lego Masters. Tym razem załączam log od restartu. Nie zaglądałem do kodu, ale stawiam na obsługę tej półpauzy w opisie i tytule.
[kodi.log](https://github.com/mbebe/blomqvist/files/7612145/kodi.log)

**Comment by mauritus321** [comment]
W kodi 19.3 windows, player 1.10 -1.10.3 taki jest obraz [](https://mega.nz/file/Z0NwXToA#zDDMqx3TV4pJ39U5Bj69XKDii2gouqPvR2iOsx-nUAY)

**Comment by rysson** [comment]
@mauritus321, a w pozostałych (wcześniejszych) jest normalny?
Pytam, bo link idący do odtwarzania nie był dotykany. Wyżej jest rozmowa o linku w liście kodi, a tam od 1.10.3 jest taki jaki był.

@klosiu, zerkam...

**Comment by rysson** [comment]
@klosiu  widzę, że 18, Python2 nie skleił unicode i utf-8, wystarczy dodać `PLchar` (co nie jest najładniejsze, ale działa) czyli zmienić linijkę 986 na:
```python
            suffix = PLchar(suffix or '')
```

Zobaczę czy coś się wyjaśni ze strumieniem i wydam poprawkę.

**Comment by mauritus321** [comment]
@rysson tak samo

**Comment by hevet** [comment]
@mauritus321 wyłącz przyspieszenie sprzętowe w ustawieniach Kodi-odtwarzacz

**Comment by rysson** [comment]
Wersja [1.10.4](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.10.4) poprawką kodowania dla Python2 (czyli Kodi 18).

**Comment by hevet** [comment]
@rysson na Kodi 18.9 nie działa np. sezon 13 Mam talent, w logu błąd kodowania 0xe2.

**Comment by hevet** [comment]
W Kodi19.3 np. po włączeniu TVN, po kilku sekundach wywala się. Log
2021-11-28 02:02:27.218 T:5608  WARNING <general>: PLAYER.PL: getPlaylist('1908473'): data: {'options': {'auto_play': True, 'disable_next_episode_board': False}, 'version': '3.0', 'movie': {'advertising': {'ad_server_error': 'http://player.pl/_pix/monitor-tvnplayer/application-web/error-silverlight/asset_id=1908473_live_tvn_hd/episode_name=tvn_hd/title=1908473_live_tvn_hd/pix.gif', 'ad_server': 'https://tvn.adocean.pl/ad.xml?tvn_vod_trailer=0/aocodetype=1/midcnt=2/predur=91/mid4dur=24/postdur=91/overdur=1320/tvn_vod_embed=0/catchup_no_fee=0/id=sWAF1P9.7YbPgc_jLC2JNX3XvRCh5YbAgDo4XsYpXSD.t7/tvn_vod_serie=1908473_live_tvn_hd/tvn_login=yes/tvn_content_category=kanaly_tv/tvn_collection=2935666/tvn_vod_traffic_category=mezczyzna,kobieta/tvn_price=no/tvn_vod_prepremiere=0/tvn_terminal=24/access_model=svod/tvn_id=449da4870c3fa4ee8fe40131ac15ad0a/profile_id=1053056/', 'is_autopromo': True, 'ads_counter': {'type': 'combined', 'text': ' ', 'autopromo_text': ' ', 'right_text': ' ', 'right_href': ' '}}, 'video': {'is_live': True, 'is_catchup': False, 'is_trailer': False, 'is_video_360': False, 'is_protected': False, 'protections': {'playready': {'src': 'https://player.pl/playerapi/product/drm/playready/1908473?platform=ANDROID_TV&type=LIVE'}, 'fairplay': {'src': 'https://player.pl/playerapi/product/drm/fairplay/1908473?platform=ANDROID_TV&type=LIVE', 'cert': 'https://r.dcs.redcdn.pl/http/o2/tvnplayer/portal/certification/fairplay/cert.pub'}, 'widevine': {'src': 'https://player.pl/playerapi/product/drm/widevine/1908473?platform=ANDROID_TV&type=LIVE'}}, 'sources': {'dash': {'url': 'https://r.dcs.redcdn.pl/livedash/o2/tvnplayer/live/tvn/live.isml/playlist.mpd?indexMode=&dummyfile=', 'is_uhd': False}, 'hls': {'url': 'https://r.dcs.redcdn.pl/livehls/o2/tvnplayer/live/tvn/live.isml/playlist.m3u8', 'is_uhd': False}, 'smooth': {'url': 'https://r.dcs.redcdn.pl/livess/o2/tvnplayer/live/tvn/live.isml/manifest', 'is_uhd': False}}, 'time_shift': {'enabled': True, 'total_length': 7200}, 'buffer_config': {'max_length': 60, 'start_length': 0}}, 'info': {'type': 'live', 'media': {}, 'id': '1908473', 'series_title': 'TVN HD'}, 'options': {'sleepBoard': False, 'product_placement': {}, 'show_episode_and_season': False, 'embed': False}, 'id': '1908473_live_tvn_hd', 'stats': {'g_stream': {'terminal': 'player_app', 'subterminal': 'player_app', 'platform': 'ott_apps', 'title': 'tvn_hd', 'origin': 'tvn', 'id': '449da4870c3fa4ee8fe40131ac15ad0a', 'form': 'live', 'collection': '2935666', 'traffic_category': 'kobieta,mezczyzna', 'login': 'yes', 'atpl': '1', 'user_package': '8269,1000,8296', 'vod_package': 'brak', 'profile_id': '449da4870c3fa4ee8fe40131ac15ad0a', 'access_model': 'svod'}, 'g_audience': {'params': {'serverHost': 'tvn.hit.gemius.pl', 'programName': '0', 'programType': 'Video', 'autoPlay': '1'}, 'account_id': 'zUdKuCt7hxK_75K0xadI8tWbHZHNavrvckKYhnas1hn.47', 'program_id': '1908473_live_tvn_hd', 'player_id': 'player'}, 'mux': {'env': 'ir8g4jv6crgir51psbohtljnq'}, 'nl_data': {'type': 'content', 'channelName': 'player.pl', 'length': 86400, 'program': 'TVN HD', 'title': 'TVN HD', 'appid': 'PB0506E41-77BC-4319-9189-62E499963DB2', 'assetid': 'PLAYER_1908473', 'isfullepisode': 'n', 'airdate': '19700101 00:00:00', 'subbrand': 'c12'}}, 'portal_data': {'detail_path': '/live/tvn-hd,1908473', 'playlist_url': 'https://player.pl/playerapi/item/1908473/playlist?platform=ANDROID_TV&type=LIVE'}, 'custom': {'product': {'id': 1908473, 'type': 'LIVE'}}}, 'movies': []}
2021-11-28 02:02:27.261 T:5608  WARNING <general>: [script.module.inputstreamhelper] Widevine update check was made on 2021-11-14 21:52
2021-11-28 02:02:27.266 T:5608     INFO <general>: CPythonInvoker(14, C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py): script successfully run
2021-11-28 02:02:27.281 T:6940     INFO <general>: VideoPlayer::OpenFile: pvr://channels/tv/Wszystkie/pvr.iptvsimple_768973412.pvr
2021-11-28 02:02:27.283 T:4108  WARNING <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
2021-11-28 02:02:27.450 T:4628     INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2021-11-28 02:02:27.451 T:4628     INFO <general>: Creating InputStream
2021-11-28 02:02:27.455 T:4628     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
2021-11-28 02:02:27.458 T:4628    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi\addons\inputstream.adaptive\
2021-11-28 02:02:27.665 T:5608     INFO <general>: Python interpreter stopped
2021-11-28 02:02:27.854 T:4628     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: live, Download speed: 0.0000 Bytes/s
2021-11-28 02:02:31.266 T:4628     INFO <general>: Creating Demuxer
2021-11-28 02:02:31.267 T:4628     INFO <general>: Opening stream: 1001 source: 256
2021-11-28 02:02:31.314 T:4628     INFO <general>: Creating video codec with codec id: 27
2021-11-28 02:02:31.315 T:4628     INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2021-11-28 02:02:31.316 T:4628     INFO <general>: Opening stream: 1002 source: 256
2021-11-28 02:02:31.334 T:4628     INFO <general>: Finding audio codec for: 86018
2021-11-28 02:02:31.336 T:4628     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2021-11-28 02:02:31.741 T:4108     INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2021-11-28 02:02:32.381 T:4108  WARNING <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
2021-11-28 02:02:33.781 T:4108     INFO <general>: Skipped 2 duplicate messages..
2021-11-28 02:02:33.781 T:4108     INFO <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
2021-11-28 02:02:39.538 T:4108  WARNING <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
2021-11-28 02:02:39.558 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4105.591064
2021-11-28 02:02:39.558 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4106.575195
2021-11-28 02:02:39.558 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4106.556641
2021-11-28 02:02:39.582 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4106.195190
2021-11-28 02:02:39.592 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4105.794434
2021-11-28 02:02:39.598 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4106.555298
2021-11-28 02:02:39.614 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4106.917725
2021-11-28 02:02:39.630 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4107.264771
2021-11-28 02:02:39.646 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4107.660645
2021-11-28 02:02:39.662 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4107.016479
2021-11-28 02:02:39.678 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4107.385742
2021-11-28 02:02:39.694 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4107.757813
2021-11-28 02:02:39.710 T:5708  WARNING <general>: ActiveAE - large audio sync error: -4108.102661

**Comment by mauritus321** [comment]
@hevet .pomogło,dzięki

**Comment by klosiu** [comment]
Dzięki za wersję 1.10.4! Jest lepiej, ale nadal pojawiają się błędy.
Na przykład przy otwieraniu jednej z serii Masterchef: [kodi.log](https://github.com/mbebe/blomqvist/files/7613380/kodi.log)

**Comment by rysson** [comment]
@hevet, ja strumienie nie ruszałem. Sprawdź proszę np. 1.9.
BTW, kodowanie chyba już uporządkowałem.

**Comment by hevet** [comment]
@rysson na wersji 1.9 tak samo jest, więc tu nic nie ruszyłeś 😀. Co do kodowania to potwierdzam jak @klosiu błąd kodowania 0xe2.

**Comment by rysson** [comment]
No to mam fix (oby skuteczny) [1.10.5](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.10.5)

- fix kodowania py2 (kodi 18)

**Comment by hevet** [comment]
@rysson na Kodi18.9 błąd kodowania zniknął, na Kodi 19.3 pojawił się błąd np. przy próbie włączenia 10 sezonu "Milionerów", log poniżej:
`2021-11-29 19:52:18.501 T:1208  WARNING <general>: PLAYER.PL: ENTER: mode='listEpizody', name='Milionerzy - Sezon 10', exlink='8135:5013705'
2021-11-29 19:52:18.501 T:1208  WARNING <general>: PLAYER.PL: getRequests('https://konto.tvn.pl/oauth/token', data='grant_type=refresh_token&refresh_token=94b319e3-435c-4d23-88d3-123c28bae8b5&client_id=Player_TV_Android_28d3dcc063672068', headers={'Host': 'konto.tvn.pl', 'user-agent': 'okhttp/3.3.1 Android', 'content-type': 'application/x-www-form-urlencoded; charset=UTF-8'}, params=None)
2021-11-29 19:52:18.697 T:1208    ERROR <general>: C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'konto.tvn.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-11-29 19:52:18.872 T:1208  WARNING <general>: PLAYER.PL: getRequests('https://player.pl/playerapi/product/vod/serial/8135/season/5013705/episode/list', data=None, headers={'Authorization': 'Basic', 'API-DeviceInfo': '2e520525f3c1e5cf;2e520525f23a38dc;Android;9;1d2e33faefbc5d77;1.0.38(62);', 'API-DeviceUid': 'ee71ac577a66c735', 'User-Agent': 'okhttp/3.3.1 Android', 'Host': 'player.pl', 'X-NewRelic-ID': 'VQEOV1JbABABV1ZaBgMDUFU=', 'API-Authentication': 'edd6f329-1c16-4236-9bae-3acea8329cb2', 'API-SubscriberHash': '97a580f96fdef939094cb20e252a66de66eee1fa07397d0a38b4ef6c329f110769259bab0ee499956d2b98da3c9e0fdf', 'API-SubscriberPub': '20a743a29f03da9dc532b8090f34823f', 'API-ProfileUid': '449da4870c3fa4ee8fe40131ac15ad0a'}, params={'4K': 'true', 'platform': 'ANDROID_TV'})
2021-11-29 19:52:19.068 T:1208    ERROR <general>: C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'player.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2021-11-29 19:52:19.208 T:1208    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'tuple' object has no attribute '_replace'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 1262, in <module>
                                                       PLAYERPL().listEpizody(exlink)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 1106, in listEpizody
                                                       meta = meta._replace(tytul=tytul)
                                                   AttributeError: 'tuple' object has no attribute '_replace'
                                                   -->End of Python script error report<--`

**Comment by praspp** [comment]
Mam pakiet Eurosport w Player. Kanały live tv E1 i E2 są dostepne w menu wtyczki. We wtyczce brak jakichkolwiek transmisji online, jak i materiałów VOD z pkietu Eurosport. 
@rysson Dasz radę rozwiazać ten problem?

**Comment by michael112** [comment]
@praspp Bawiłem się jakiś czas temu tą kwestią i chyba mam wstępną wersję poprawionej wtyczki. Z tym że kod jest oparty na którejś ze starszych wersji wtyczki, chyba 1.9. Nie miałem czasu dokładnie tego dopracować. Ale oglądałem w ten sposób skoki w zeszły weekend i chyba działa.

**Comment by infortek1991** [comment]
Dzień dobry,

Player.PL na kodi 19.3 na wtyczce 1.10.5 już widzi odpowiednie programy, filmy i seriale, które są w pakiecie.
Gdy oglądam "Chyłka" Sezon 5 przez KODI na tej wersji to cały czas jest mryganie odtwarzanego odcinka. Pokazuje VIDEO a potem znika i pokazuje na przemian VIDEO i zielone tło i na przemiennie. Czy jest możliwość naprawienia tego problemu ?

**Comment by rysson** [comment]
@praspp możemy się jakoś umówić, nie wiem może na sobotę, na dołączenie mojego odbiornika do Twojego pakietu do testów. Na szczęście kod zalogowania nie wymaga przekazania hasła. Zapraszam na discord.

@michael112 jak masz to możesz się pochwalić. Jak nie da patcha zastosować wprost, to ręcznie różnice powinno się dać przenieść.

@infortek1991, a to dziwoląg. Próbowałeś może tych porad wyżej, żeby coś przełączać w akceleracji sprzętowej?
BTW. Chyłka S05 jest już dostępny? Przegapiłem.

**Comment by infortek1991** [comment]
@rysson Tak. 5 Sezon już się zaczął i jest dostępny 1 odcinek. Obecnie problem już mam naprawiony. W moim wypadku musiałem wyłączyć tą akcelerację. Dziękuję za pomoc :)

**Comment by praspp** [comment]
> @praspp możemy się jakoś umówić, nie wiem może na sobotę, na dołączenie mojego odbiornika do Twojego pakietu do testów. Na szczęście kod zalogowania nie wymaga przekazania hasła. Zapraszam na discord.
> 
@rysson Nie ma problemu. Wbiję Twoje urządzenie na listę. Daj sygnał - znak. "Zapraszam na discord" ?

**Comment by rysson** [comment]
@praspp, to świetnie. Gadamy sobie czasem o wtyczkach tutaj https://discord.gg/2Yvr6FGydd

**Comment by praspp** [comment]
@rysson Wbiłem się i czekam soboty.

**Comment by Szifo** [comment]
> @rysson Tak. 5 Sezon już zaczął i jest dostępny 1 odcinek. Obecnie problem już mam naprawiony. W moim wypadku musiałem przejść. Dziękuję za pomoc :)

Możesz mi napisać jak sobie poradziłeś z tym obrazem co migał z zielonym tłem? Ja mam takie objawy przy nowszych odcinkach, starsze normalnie się odtwarzają. Szukałem tej akceleracji sprzętowej i nie mogę znaleźć.

**Comment by infortek1991** [comment]
@Szifo Ustawienia - Ustawienia Systemu - Odtwarzacz - Wideo - Kategoria "Przetwarzanie"
W moim wypadku musiałem odznaczyć opcję "Zezwalaj na sprzętową akcelerację - DXVA2", ale u Ciebie możliwe, że trzeba zaznaczyć.
I aby było ustawione "Metoda renderowania" na "Automatyczne wykrywanie" i chyba tyle.

**Comment by Szifo** [comment]
Dzięki za odpowiedź, lecz to nic nie pomogło. Może komuś jeszcze przytrafiło się, że obraz cały czas mruga z zielonym tłem ( z dźwiękiem jest wszystko ok).
Mnie zastanawia fakt, że dzieje się to z nowszymi odcinkami np: Googlebox, Ślub od pierwszego wejrzenia, Na Wspólnej etc. na Playerze ( mam wykupiony pakiet z reklamami ) na Polsat Go czy TVP problem nie istnieje. Zmieniałem już wersje Kodi, lecz też nic to nie dało.
Czy ktoś zna rozwiązanie lub ma jakieś pomysły ?

**Comment by hevet** [comment]
@Szifo jaka wersja Kodi i jaki sprzęt?

**Comment by Szifo** [comment]
> @Szifo jaka wersja Kodi i jaki sprzęt?

Kodi 19.0 ( testowałem od 19.0-19.3) PC AMD Ryzen 3200G, GF 1050Ti, 16 GB RAM, Win10 x64

**Comment by rysson** [comment]
@mbebe, słyszałem, że już zassałeś 1.10.5. W takim razie podbiłem wersję do 1.11 i proszę o pull request https://github.com/mbebe/blomqvist_srcs/pull/4.

Niniejszym zamykamy to zgłoszenie. @praspp, proszę Cię o założenie nowego w sprawie Eurosportu. Będzie w np. 1.12 (czyli wersje β będą 1.11.x).

Dziękuję wszystkim za współpracę. Oczywiście wymiana wiedzy o aktualizacjach dalej może się toczyć :-D

**Comment by rysson** [comment]
Wydaje się, ze problem został naprawiony w 1.11 i można zamknąć zgłoszenie.
Zresztą jest kandydat na [1.12](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.11.13).
