### ISSUE TITLE
pastebinVID

### ISSUE THREAD

**Issue by Axis963** [mbebe/blomqvist#683]
wtyczka po ostatniej aktualizacji ruszyla, ale cda z wtyczki pastebinVID odtwarzane jest w 480p, a nie 1080p :// . Z innych wtyczek cda dziala normalnie  w 1080, wiec wszystko z ResolveURL jest git. To na Kodi 18.9.

Bo na Kodi 19.3 nie czyta linku, wywala błąd:

2021-12-06 22:12:51.797 T:9405    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: a bytes-like object is required, not 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pastebinVID/main.py", line 936, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pastebinVID/main.py", line 910, in router
                                                       ListPastebin(exlink,page)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pastebinVID/main.py", line 155, in ListPastebin
                                                       lists,np = getPastebin(exlink2,page)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pastebinVID/main.py", line 248, in getPastebin
                                                       html=getUrlReq(exlink)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pastebinVID/main.py", line 195, in getUrlReq
                                                       if 'Warning - Potentially offensive content ahead' in content:
                                                   TypeError: a bytes-like object is required, not 'str'
                                                   -->End of Python script error report<--
                                                   
2021-12-06 22:12:52.633 T:9405     INFO <general>: Python interpreter stopped

**Comment by FXcodi** [comment]
Co się dzieje z tą wtyczką>Nagle przestała odtwarzać stream video embed z większości popularnych serwisów, a także nie działa wtyczka ekino tv.
