### ISSUE TITLE
fmovies.to error

### ISSUE THREAD

**Issue by theface78** [mbebe/blomqvist#684]
The addon always terminates with an error starting today. The Kodi 19.3 log states an https warning and some phyton errors.

**Comment by psychosis448** [comment]
The error thrown is actually:

```log
2021-12-18 02:50:55.354 T:2236    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.fmoviesto/main.py", line 1019, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.fmoviesto/main.py", line 880, in router
                                                       ListMovies(exlink,page)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.fmoviesto/main.py", line 169, in ListMovies
                                                       links, serials, pagin = getMovies(exlink,page)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.fmoviesto/main.py", line 231, in getMovies
                                                       result = parseDOM(html, 'div', attrs={'class': "filmlist"}) [0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--

2021-12-18 02:50:55.354 T:2236    DEBUG <general>: onExecutionDone(103, /var/lib/kodi/.kodi/addons/plugin.video.fmoviesto/main.py)
```

It seems to be an issue with the ParseDOM function, when regexing on the HTML within the `parseDOM` function.

**Comment by mbebe** [comment]
Should be ok in ver. 1.9.

**Comment by theface78** [comment]
Excellent work, I can confirm that it's working again! :)
