### ISSUE TITLE
Televio - nie działa, błędne dane logowania

### ISSUE THREAD

**Issue by hevet** [mbebe/blomqvist#686]
Od dzisiaj wylogowało  mnie, a przy próbie logowania pokazuje błędne dane logowania. Hasła nie zmieniałem, stało się tak zarówno pod Kodi 18.9 i Kodi 19.3. Strona działa prawidłowo, ale z tego co widzę wprowadzono profile użytkowników, pewnie dlatego. W logu niczego nie pokazuje.

**Comment by rysson** [comment]
Po grzebaniu się w połączeniach i zawiłościach HTTP mogę napisać, że nowy site wymusza encodowanie (kompresje) `br`, której `requests` w Kodi nie obsługuje (u mnie w  py3 akurat tak). Wymaga także zamykania połączeń.
```python
           'Accept-Encoding': 'gzip, deflate, br',
           'Connection': 'close',
```
Po dodaniu **koszmarnej** (!!!) implementacji [dekodera](https://github.com/pothos/brotlipython) za to w czystym pythonie (sam autor napisał „*super slow pure python brotli decoder, please ignore*”) i automatycznym wyborze profilu udało się zalogować.
Tyle, że reszta dalej się wywala, bo chyba API zmieniło się bardziej.

**Comment by rysson** [comment]
[televiopl] Fix login, get 1st profile. Fixes #686. 
                                                                          
Fix televiopl:                                                            
- add encoding br (brotli) support                                        
- fix login, add all cookies                                              
- handle profiles, auto-select 1st profile                                                                                                                           
- fix TV list scanning                                                                                                                                               
- keep device id (avoid to create new device for each login)              
                                                                          
Fixes #686.

---

Wersja 0.2.1 do testów. Ale to nie koniec prac, bo parę rzeczy trzeba wyjaśnić.

[plugin.video.televiopl-0.2.1.zip](https://github.com/mbebe/blomqvist/files/7697181/plugin.video.televiopl-0.2.1.zip)

**Comment by hevet** [comment]
@mbebe wersją 0.2.1 działa poprawnie, można się zalogować.  Prośba o podbicie do wersji 0.3 i dodanie do repo.

**Comment by zuzia-dev** [comment]
> @mbebe wersja 0.2.1 działa poprawnie, można się zalogować. 
Potwierdzam, wtyczka odzyskała funkcjonalność pod Kodi 18.9.
Tylko trzeba usunąć i zainstalować jeszcze raz, sama aktualizacja nie wystarczy.

**Comment by SonGoku90** [comment]
Na kodi 19.4 nie działa wtyczka 0.3, proszę o naprawienie

**Comment by hevet** [comment]
@SonGoku90 jaki błąd, podaj log.

**Comment by SonGoku90** [comment]
`http://paste.kodi.tv/tezexirode`

**Comment by zuzia-dev** [comment]
Wrzucam log.
```

                                   INFO <general>: CAddonMgr::FindAddon: plugin.video.televiopl v0.5 installed
                                   INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
                                   INFO <general>: initializing python engine.
                                   INFO <general>: CPythonInvoker(18, /home/zuzia/.kodi/addons/plugin.video.televiopl/main.py): script successfully run
                                   INFO <general>: Python interpreter stopped
                                   INFO <general>: initializing python engine.
                                WARNING <general>: Attempt to use invalid handle -1
                                   INFO <general>: Skipped 4 duplicate messages..
                                   INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
                                   INFO <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
                                WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
                                WARNING <general>: Skipped 6 duplicate messages..
                                WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
                                   INFO <general>: Skipped 7 duplicate messages..
                                   INFO <general>: CPythonInvoker(19, /home/zuzia/.kodi/addons/plugin.video.televiopl/main.py): script successfully run
                                   INFO <general>: initializing python engine.
                                   INFO <general>: Python interpreter stopped
                                 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: error() invoked
                                                   Traceback (most recent call last):
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/main.py", line 80, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/main.py", line 78, in router
                                                       Televio.home()
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/televio/__init__.py", line 80, in home
                                                       user = self.logowanie()
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/televio/__init__.py", line 113, in logowanie
                                                       html = resp_text(resp)
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/televio/__init__.py", line 31, in resp_text
                                                       return brotlidec(resp.content, out).decode('utf-8')
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/brotlipython.py", line 2600, in brotlidec
                                                       state = parse_prefix_code_block_types_insert_and_copy_lengths()
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/brotlipython.py", line 1915, in parse_prefix_code_block_types_insert_and_copy_lengths
                                                       tmp_ = parse_prefix_code(alphabet_size)
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/brotlipython.py", line 1891, in parse_prefix_code
                                                       return parse_simple_prefix_code(alphabet_size)
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/brotlipython.py", line 1673, in parse_simple_prefix_code
                                                       error() # InvalidSymbol
                                                     File "/home/zuzia/.kodi/addons/plugin.video.televiopl/resources/lib/brotlipython.py", line 78, in error
                                                       raise Exception("error() invoked")
                                                   Exception: error() invoked
                                                   -->End of Python script error report<--
```

**Comment by zuzia-dev** [comment]
Chodzi o to, że reinstalacja pomaga pod Android, zaś pod Linuksem (Debian), nie działa.
