### ISSUE TITLE
Problem z CanalPlusVOD

### ISSUE THREAD

**Issue by pawel-domanski** [mbebe/blomqvist#705]
Wszystko działało poprawnie i w pewnej chwili na Kodi 19 przestała działać możliwość logowania.
Początkowo miałem problem z zalogowaniem na komputerze ale tylko przez chwilę.
W logach mam tylko to

2022-01-25 15:56:29.657 T:1635     INFO <general>: initializing python engine.
2022-01-25 15:56:32.328 T:1485     INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2022-01-25 15:56:47.939 T:1635     INFO <general>: CPythonInvoker(11, /home/pi/.kodi/addons/plugin.video.canalplusvod/main.py): script successfully run
2022-01-25 15:56:48.000 T:1688     INFO <general>: initializing python engine.
2022-01-25 15:56:48.163 T:1635     INFO <general>: Python interpreter stopped
2022-01-25 15:56:51.745 T:1688     INFO <general>: CPythonInvoker(12, /home/pi/.kodi/addons/plugin.video.canalplusvod/main.py): script successfully run
2022-01-25 15:56:51.998 T:1688     INFO <general>: Python interpreter stopped
2022-01-25 15:59:54.034 T:1850     INFO <general>: initializing python engine.
2022-01-25 15:59:55.172 T:1485     INFO <general>: Loading skin file: /home/pi/.kodi/addons/screensaver.digitalclock/resources/skins/default/720p/skin.estuary.xml, load type: LOAD_ON_GUI_INIT
2022-01-25 16:12:17.660 T:2273     INFO <general>: initializing python engine.
2022-01-25 16:12:26.569 T:2273    ERROR <general>: Skipped 1 duplicate messages..
2022-01-25 16:12:26.569 T:2273    ERROR <general>: NEWADDON Unknown Video Info Key "image"
2022-01-25 16:12:26.627 T:2273     INFO <general>: Skipped 4 duplicate messages..
2022-01-25 16:12:26.627 T:2273     INFO <general>: CPythonInvoker(14, /home/pi/.kodi/addons/plugin.video.canalplusvod/main.py): script successfully run
2022-01-25 16:12:26.703 T:2283     INFO <general>: initializing python engine.
2022-01-25 16:12:27.048 T:2273     INFO <general>: Python interpreter stopped
2022-01-25 16:12:27.463 T:1850     INFO <general>: CPythonInvoker(13, /home/pi/.kodi/addons/screensaver.digitalclock/default.py): script successfully run
2022-01-25 16:12:27.515 T:1850     INFO <general>: Python interpreter stopped
2022-01-25 16:12:31.261 T:2276    ERROR <general>: NEWADDON Unknown Video Info Key "image"
2022-01-25 16:12:32.065 T:2276     INFO <general>: Skipped 4 duplicate messages..
2022-01-25 16:12:32.065 T:2276     INFO <general>: CPythonInvoker(15, /home/pi/.kodi/addons/plugin.video.canalplusvod/main.py): script successfully run
2022-01-25 16:12:32.278 T:2276     INFO <general>: Python interpreter stopped
2022-01-25 16:12:33.929 T:2289     INFO <general>: initializing python engine.

**Comment by hevet** [comment]
U mnie pokazuje, że niepoprawne dane logowania, pokazuje się opcja Zaloguj w głównym menu, a tak naprawdę jestem zalogowany, bo na dole widnieje opcja Wyloguj. Dziwna sprawa, pewnie znowu coś pozmieniało.

**Comment by Dogbyte01** [comment]
Ja mam to samo. Przy próbie logowania wyskakuje "Błąd. Niepoprawne dane logowania"  Sprawdzane na Android Kodi 19.3 i na Windows 7 Kodi 18.9.  Nie działają kanały TV ani VOD. Pozdrawiam.

**Comment by pawel-domanski** [comment]
Ale jak myślicie czy ktoś nam w tym pomoże ??

**Comment by Mariusz89B** [comment]
Poprawka logowania:
https://github.com/kodi-pl/blomqvist_srcs/releases/tag/plugin.video.canalplusvod-1.7.5.0

**Comment by Dogbyte01** [comment]
Wielkie dzięki Mariusz za tak szybką pomoc. Teraz wszystko działa pięknie. Super!

**Comment by pawel-domanski** [comment]
@Mariusz89B no to genialnie dziękuję, zaraz biorę się do instalacji

**Comment by Dogbyte01** [comment]
Okazało się jednak że nie wszystko działa. Otóż na Win7, Kodi 18.9 - kanały i VOD działają pięknie ale nie można wygenerować pliku m3u. Na Android 9, Kodi 19.3 - kanały są, ale nie startują natomiast VOD działa bez problemów. Żeby było śmiesznie - kanały nie startują ale plik m3u generuje się gładko.  Po załadowaniu tego pliku w Androidzie do IPTV Simple Client i do M-TVGuide kanały są ale nie startują a w Windows startują i w Simple Client i w M-TVGuide. Czy to sa jakieś błędy czy ja mam coś nie tak ustawione? Pozdro.

**Comment by Mariusz89B** [comment]
@Dogbyte01 Mozliwe ze VMP ogranicza dostep, podaj log.

**Comment by PrzemekSkw** [comment]
> @pawel-domanski moze ten ktos taki jak ja :P Tutaj poprawka logowania: https://github.com/kodi-pl/blomqvist_srcs/releases/tag/plugin.video.canalplusvod-1.7.5.0

Hej, a można jakoś zaktualizować w Kodi? Mam Libreelec zainstalowany na Rpi4. Mam dodane repozytorium ale jest tylko starsza wersja.
Pozdrawiam.

**Comment by Mariusz89B** [comment]
> > @pawel-domanski moze ten ktos taki jak ja :P Tutaj poprawka logowania: https://github.com/kodi-pl/blomqvist_srcs/releases/tag/plugin.video.canalplusvod-1.7.5.0
> 
> Hej, a można jakoś zaktualizować w Kodi? Mam Libreelec zainstalowany na Rpi4. Mam dodane repozytorium ale jest tylko starsza wersja. Pozdrawiam.

Nie, bo nie jestem autorem wtyczki, musisz recznie pobrac plik .zip i zainstalowac w Kodi.

**Comment by PrzemekSkw** [comment]
Dziękuję. Czy ktoś sprawdzał czy ta wtyczka jest bezpieczna? Czy nikt nie wykradnie danych logowania?

**Comment by zuzia-dev** [comment]
Jest bezpieczna. W ogóle od @Mariusz89B można instalować śmiało.

**Comment by PrzemekSkw** [comment]
@zuzia-dev Mariusz powyżej napisał, że nie jest autorem 😃

**Comment by zuzia-dev** [comment]
@PrzemekSkw autorem jest kto inny, ale również godny zaufania.

**Comment by PrzemekSkw** [comment]
OK, dzięki. Zaufam Ci 😁
Pozdrawiam.

pt., 28 sty 2022, 23:19 użytkownik zuzia-dev ***@***.***>
napisał:

**Comment by Mariusz89B** [comment]
@PrzemekSkw Jestem autorem innych wtyczek Kodi, pomagamy sobie na wzajem z mbebe, już wcześniej moje poprawki trafiły do jego repozytorium. Najnowsze poprawki są dodane jako "pull request" i czekają na jego potwierdzenie.
https://github.com/mbebe/blomqvist_srcs/pulls

Mariusz
mods-kodi.pl

**Comment by Dogbyte01** [comment]
> @Dogbyte01 Mozliwe ze VMP ogranicza dostep, podaj log.

Podaję logi bez debug z Kodi 18, 19 i 20. Które komponenty mam dołączyć do logów z debugowaniem?
Android 9: Czyste instalacje tylko z C+. Kodi 18 i 19 - VOD działa ale Kanały nie. Kodi 20 Beta - ani VOD ani Kanały nie działają. Po wystartowaniu jakiegoś filmu z VOD Kodi się wyłącza.
Windows 7. Kodi 18 VOD i Kanały działają, nie generuje m3u. 
[kodi18And9.log](https://github.com/mbebe/blomqvist/files/7962546/kodi18And9.log)
[kodi18Win7.log](https://github.com/mbebe/blomqvist/files/7962547/kodi18Win7.log)
[kodi19And9.log](https://github.com/mbebe/blomqvist/files/7962548/kodi19And9.log)
[kodi20And9.log](https://github.com/mbebe/blomqvist/files/7962549/kodi20And9.log)

**Comment by hevet** [comment]
@Dogbyte01 sprawdź tę wersję
[plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)

**Comment by PrzemekSkw** [comment]
Zainstalowałem najnowszą wtyczkę, niestety strasznie zacina. Co chwilę wgrywa mimo że uruchomiłem z VOD jakiś mały program 25 minutowy.

**Comment by hevet** [comment]
Spróbuj tych porad
https://r.tapatalk.com/shareLink/topic?url=https%3A%2F%2Fforum%2Ekodiwpigulce%2Epl%2Fshowthread%2Ephp%3Ftid%3D4174&share_tid=4174&share_fid=1966499&share_type=t&link_source=app

**Comment by PrzemekSkw** [comment]
Dzięki, teraz działa super.

**Comment by Dogbyte01** [comment]
> @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)

Wszystko hula pięknie. Dzięki wielkie.

**Comment by pawel-domanski** [comment]
Znów nagrzebali z logowaniem
2022-02-01 10:43:40.260 T:1383    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'token'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.canalplusvod/main.py", line 1407, in <module>
                                                       home()
                                                     File "/home/pi/.kodi/addons/plugin.video.canalplusvod/main.py", line 107, in home
                                                       CANALvod().logowanie()
                                                     File "/home/pi/.kodi/addons/plugin.video.canalplusvod/main.py", line 902, in logowanie
                                                       self.CMStoken = response['token']
                                                   KeyError: 'token'
                                                   -->End of Python script error report<--

**Comment by Mariusz89B** [comment]
@pawel-domanski sprawdzilem przed chwila na mojej wersji 1.7.5.1 to sie poprawnie zalogowalo.

**Comment by Dogbyte01** [comment]
Rano ok. 11 coś grzebali w C+. Ja byłem zalogowany w aplikacji w TV i widziałem że oferta się zmieniła, kanały live zniknęły na jakiś czas itp... Potem wszystko wróciło do normy i działa poprawnie.

**Comment by pawel-domanski** [comment]
Tak rzeczywiście wszystko wróciło do normy, pewnie wdrożenie jakieś się nie udało i zrobili rollback :)

**Comment by kkraszy** [comment]
> @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)

Witam,

Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3)  .

Jest jednak jedna niegodność - kanały TV starują zawsze z najniższej rozdzielczości SD. Może ręcznie przełączyć na HD ale jest to bardzo uciążliwe. 
Czy jest jakiś sposób aby kanały odpalały się domyślnie w HD (720p) ?

**Comment by PrzemekSkw** [comment]
Testuję teraz Canal Plus online i niestety w przeglądarce też jest jakość SD. Tragiczna ta usługa.

**Comment by hevet** [comment]
Jakiej przeglądarki używas,z?

**Comment by PrzemekSkw** [comment]
A to ma znaczenie? Odpisali mi z canal plusa że nad tym pracują więc chyba to wszędzie występuje.

**Comment by Mariusz89B** [comment]
@PrzemekSkw Przeczytaj:
https://github.com/mbebe/blomqvist/issues/657#issuecomment-983378636

**Comment by PrzemekSkw** [comment]
Używam Google - Chrome. Lepszej przeglądarki do tego chyba nie znajdę 😃

**Comment by Mariusz89B** [comment]
> Używam Google - Chrome. Lepszej przeglądarki do tego chyba nie znajdę 😃

Ostatnia wersja Widevine byla jakas bledna, wiem ze nad tym pracuja. Mozliwe ze dlatego.

**Comment by PrzemekSkw** [comment]
Myślałem że to tak ogólnie jest kiepski ten c+ i tylko dobrze działa na androidboxie ale teraz przełączyłem się z Linuxa na windowsa i odpaliłem w Edge. Jest jakość HD. Będę musiał na Linuxie Edge sprawdzić może zadziała.
Pozdrawiam.

**Comment by greg83BB** [comment]
> > @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)
> 
> Witam,
> 
> Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3) .
> 
> Jest jedna jednak niedogodność - System TV startują zawsze z natychmiastową rozdzielczością SD. Można ręcznie przełączyć na HD ale jest to bardzo uciążliwe. Czy jest używany sposób, aby odpalić się domyślnie w HD (720p) ?

U mnie to samo da się to jakoś rozwiązać? na wersji 1.7.5.1 kanały tv na zywo mi nie działały na wersji 1.7.5.2. starują w SD i za każdym razem trzeba ustawiać HD po przełączeniu kanału

**Comment by kkraszy** [comment]
> > > @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)
> > 
> > 
> > Witam,
> > Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3) .
> > Jest jedna jednak niedogodność - System TV startują zawsze z natychmiastową rozdzielczością SD. Można ręcznie przełączyć na HD ale jest to bardzo uciążliwe. Czy jest używany sposób, aby odpalić się domyślnie w HD (720p) ?
> 
> U mnie to samo da się to jakoś rozwiązać ? na wersji 1.7.5.1 kanały tv na zywo mi nie działały na wersji 1.7.5.2. starują w SD i za każdym razem trzeba ustawiać HD po przełączeniu kanału

Niestety, mi się nie udało rozwiązać. Ale ułatwiłem sobie przełączanie na HD. Za pomocą wtyczki Keymap Edit można dodać sobie skróty klawiszowe - zmieniam na HD jednym wscisciem przycisku.

**Comment by Mariusz89B** [comment]
> > > @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)
> > 
> > 
> > Witam,
> > Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3) .
> > Jest jedna jednak niedogodność - System TV startują zawsze z natychmiastową rozdzielczością SD. Można ręcznie przełączyć na HD ale jest to bardzo uciążliwe. Czy jest używany sposób, aby odpalić się domyślnie w HD (720p) ?
> 
> U mnie to samo da się to jakoś rozwiązać ? na wersji 1.7.5.1 kanały tv na zywo mi nie działały na wersji 1.7.5.2. starują w SD i za każdym razem trzeba ustawiać HD po przełączeniu kanału

W ust. ISA (inputstream.adaptive)

**Comment by kkraszy** [comment]
> > > > @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)
> > > 
> > > 
> > > Witam,
> > > Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3) .
> > > Jest jedna jednak niedogodność - System TV startują zawsze z natychmiastową rozdzielczością SD. Można ręcznie przełączyć na HD ale jest to bardzo uciążliwe. Czy jest używany sposób, aby odpalić się domyślnie w HD (720p) ?
> > 
> > 
> > U mnie to samo da się to jakoś rozwiązać ? na wersji 1.7.5.1 kanały tv na zywo mi nie działały na wersji 1.7.5.2. starują w SD i za każdym razem trzeba ustawiać HD po przełączeniu kanału
> 
> W ust. ISA (inputstream.adaptive)

Długo walczyłem z ISA, (minimalny bitrate itp) niestety wydaje się że wtyczka C+ ignoruje te ustawienia dla kanałów Livie

**Comment by greg83BB** [comment]
> 

też walczyłem z ISA nic to nie dało, jedynie co udało mi się ustalić to to ze gdy ustawie na jakimś kanale live HD i ustawie domyślnie dla wszystkich mediów to HD działa na wszystkich kanałach dopóki nie wyjdę z KODI. gdy uruchomię ponownie to procedurę trzeba na nowo powtórzyć. tak jakby na stałe nie zapisywało tej domyślnej rozdzielczości.
Jeszcze jakieś pomysły?

**Comment by greg83BB** [comment]
i dlaczego moje komentarze sie zmieniają po opublikowaniu, wygląda to nie składnie i słowa sie zmieniają

**Comment by greg83BB** [comment]
![image](https://user-images.githubusercontent.com/101361834/158053509-e551b653-0e11-4404-8188-2df9142ca885.png)

**Comment by greg83BB** [comment]
> > > > @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)
> > > 
> > > 
> > > Witam, 
> > > Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3) . 
> > > Jest jedna jednak niedogodność - Telewizory systemowe zaczynają zawsze z natychmiastową rozdzielczością SD. Można ręcznie przełączyć na HD ale jest to bardzo uciążliwe. Czy jest używany sposób, aby odpalić się domyślnie w HD (720p) ?
> > 
> > 
> > U mnie to samo da się to jakoś oznaczać? w wersji 1.7.5.1 System tv na zywo mi nie w wersji 1.7.5.2. starują w SD i za każdym razem trzeba ustawiać HD po przełączeniu się na zmianę
> 
> Niestety, mi się nie udało. Ale ułatwiłem sobie przełączanie na HD. Za pomocą nowych map Edytuj można dodać skróty klawiszowe - zmienia się na HD jednym wciśnięciem skrótu.

![image](https://user-images.githubusercontent.com/101361834/158054799-94a53ce8-7276-434a-8a55-a86fa3c0ce34.png)

**Comment by kkraszy** [comment]
> > > > > @Dogbyte01 sprawdź tę wersję, tylko dla Androida. [plugin.video.canalplusvod_1.7.5.2.zip](https://github.com/mbebe/blomqvist/files/7962947/plugin.video.canalplusvod_1.7.5.2.zip)
> > > > 
> > > > 
> > > > Witam,
> > > > Tylko na tej wersji działa TV na certyfikowanym androidzie - (dużo sprawniej na kodi 18.9 niż na 19.3) .
> > > > Jest jedna jednak niedogodność - Telewizory systemowe zaczynają zawsze z natychmiastową rozdzielczością SD. Można ręcznie przełączyć na HD ale jest to bardzo uciążliwe. Czy jest używany sposób, aby odpalić się domyślnie w HD (720p) ?
> > > 
> > > 
> > > U mnie to samo da się to jakoś oznaczać? w wersji 1.7.5.1 System tv na zywo mi nie w wersji 1.7.5.2. starują w SD i za każdym razem trzeba ustawiać HD po przełączeniu się na zmianę
> > 
> > 
> > Niestety, mi się nie udało. Ale ułatwiłem sobie przełączanie na HD. Za pomocą nowych map Edytuj można dodać skróty klawiszowe - zmienia się na HD jednym wciśnięciem skrótu.
> 
> ![image](https://user-images.githubusercontent.com/101361834/158054799-94a53ce8-7276-434a-8a55-a86fa3c0ce34.png)

Nie wszystkie przyciski mogą działać - spróbuj ustawić jakiś klawisz numeryczny np "0" , W złączniku masz wideo jak to się robi

https://user-images.githubusercontent.com/7765867/158071526-fd22bfd6-faec-4467-9e5d-d15f042da8f9.mp4

.

**Comment by praspp** [comment]
Kodi jest nadal transparentne dla C+ Online i nie jedt wliczane do limitu urządzeń. Włączona weryfikacja cert. serwera umożliwia na certyfikowanych urządzeniach z androidem (posiadających Widevine L1 i PlayReady) odtwarzanie kanałów TV w pełnej rozdzielczości - do 1080p.

**Comment by rick1311** [comment]
Czy jest szansa że zaczną dzialać strumienie napisów? Na kanalach c+, HBO są wykrywane, ale za nic nie chce ich wyświetlić zarówno przez wtyczkę jak i iptv clienta...
Co do ręcznej zmiamy na HD niestety potwierdzam.

**Comment by hevet** [comment]
@rick1311 napisy działają zarówno przez wtyczkę jak i IPTV Client.
![napisy](https://user-images.githubusercontent.com/43666290/164617629-a275696e-b696-46dc-bf56-8af4cafb206c.jpg)

**Comment by rick1311** [comment]
U mnie wyświetlają się tylko na chwilę i znikają, zapewne jakiś błąd Kodi od fandagosa (kodi z obsługą Dolby Vision+obsluga libbluray), firestick 4k max i kodi 19.0. Czy na nowszych buildach Kodi szybciej się przelaczają kanały live? u mnie to trwa nawet 10 sekund.

**Comment by hevet** [comment]
Zależy jaki serwis, internet itp.
U mnie z Canal+ trochę trwa przełączenie, z TVP kanały szybko się przełączają.

**Comment by rick1311** [comment]
i tak, sprawdzilem na boxie od canal+, kodi 19, 19.3, 19.4. Wtyczka jak najbardziej działa poza napisami przy strumieniach live - napisy się pojawiają na jakieś 2 sekundy i znikają, filmy z vod działają ok. podobny przypadek mam z hbomax. Wygląda to trochę na jakiś błąd samego kodi dla boxów pod androida. Nie testowalem na windowsie.

**Comment by praspp** [comment]
Potwierdzam problem z wyświetlaniem napisów (znikają po sekundzie od włączenia). W HBOMax (najnowsza wersja 0.9.5) problem nie występuje. Wyglada na bug wtyczki CanalPlusVOD, a nie serwisu. W aplikacji C+ Online napisy działają.
Sprawdzone na: Fire TV Cube 2gn., Fire OS 7 (ATV 9.0), Kodi 19.4, CanalPlusVOD 1.7.5.3

**Comment by rick1311** [comment]
> Potwierdzam problem z wyświetlaniem napisów (znikają po sekundzie od włączenia). W HBOMax (najnowsza wersja 0.9.5) problem nie występuje. Wyglada na bug wtyczki CanalPlusVOD, a nie serwisu. W aplikacji C+ Online napisy działają. Sprawdzone na: Fire TV Cube 2gn., Fire OS 7 (ATV 9.0), Kodi 19.4, CanalPlusVOD 1.7.5.3

a czy we wtyczce hbomax działają ci inne rozdzielczości wyższe od 1080p?  U mnie na firesticku wszystko działalo, aplikacja od hbo również, ale od premiery  Batmana mam na każdej przystawce z androidem max 1080p, we wtyczce hbomax jak wybiorę coś powyżej 1080p mam czarny ekran. Co ciekawe apka na xboxa juz wyswietla 4k z HDRem. Zgłaszałem problem do hbo a oni tradycyjnie nie widzą problemu.
