### ISSUE TITLE
Vectra

### ISSUE THREAD

**Issue by SkyAgency** [mbebe/blomqvist#729]
Wtyczka od dziś nie działa:

`2022-03-01 14:56:36.489 T:447281   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/home/mariusz/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 448, in listVOD
                                                       poster = dt.get("images", None).get("poster", None)[0].get("url", None)
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/mariusz/.kodi/addons/plugin.video.vectrapl/main.py", line 102, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/mariusz/.kodi/addons/plugin.video.vectrapl/main.py", line 91, in router
                                                       Vectra.listVOD('query|'+query, page)
                                                     File "/home/mariusz/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 451, in listVOD
                                                       poster = dt.get("images", None).get("cover", None)[0].get("url", None)
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--`

**Comment by zuzia-dev** [comment]
@SkyAgency trwają prace. Cierpliwości.

**Comment by zuzia-dev** [comment]
@SkyAgency poprawiona wersja.
Podziękowania dla @heppen-dev !

[plugin.video.vectrapl.zip](https://github.com/mbebe/blomqvist/files/8164168/plugin.video.vectrapl.zip)

**Comment by SkyAgency** [comment]
@zuzia-dev dzięki za szybką reakcję!

**Comment by Adam5991** [comment]
Robicie megaae robotę 💪 pozdroe

śr., 2 mar 2022, 11:34 użytkownik SkyAgency ***@***.***>
napisał:

**Comment by zuzia-dev** [comment]
@Adam5991 @SkyAgency czy na nowej wersji od @mbebe https://github.com/mbebe/blomqvist/files/8352908/plugin.video.vectrapl-0.6.zip działa Wam jakiś film VOD? Bo nie mam nic wykupionego, żeby sprawdzić.

**Comment by zuzia-dev** [comment]
@mbebe sprawdziłam, VOD nie działa.

**Comment by heppen-dev** [comment]
Gdyby ktoś był zainteresowany to u mnie w repo jest Vectra, aktywnie wspierania i rozwijana: https://github.com/heppen-dev/plugin.video.tvsmartgo
Możecie pobrac z: https://heppen-dev.github.io :)

Działa VOD, historia wypożyczeń, aktywne wypożczenia, jest TV, catchup 7 dniowy, do tego oddzielne kategorie dla telewizji z EPG i pokategoryzowanej :) W przypadku sugestii śmiało można walić na issue u mnie na GH.
