### ISSUE TITLE
Player się zaczął wywalać

### ISSUE THREAD

**Issue by plonkaadam** [mbebe/blomqvist#739]
Player znowu przestał działać, przy próbie odtworzenia:

```
2022-03-17 23:02:32.234 T:2754085056   ERROR: /usr/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
                                              from cryptography import x509
2022-03-17 23:02:33.100 T:2754085056 WARNING: PLAYER.PL: ENTER: mode='playvid', name='xxxx xx xx\xc5\x82x\xc5\x9b\xc4\x87 - SxxExx', exlink='3142096'
2022-03-17 23:02:38.194 T:2754085056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.playermb/main.py", line 1723, in <module>
                                                PLAYERPL().playvid(exlink)
                                              File "/home/pi/.kodi/addons/plugin.video.playermb/main.py", line 990, in playvid
                                                if not is_helper.check_inputstream():
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-03-17 23:02:38.530 T:2973056128   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.playermb/?name=xxxxx
```

Po wywaleniu linii 990 i 991:

```
            if not is_helper.check_inputstream():
                raise ValueError('To i tak się by wcześniej wywaliło !!!')
```

wszystko działa poprawnie

**Comment by traleka** [comment]
Dzięki. Mi pomogło (nie chciały mi chodzić odcinki programu "Projekt Cupid").
