### ISSUE TITLE
Player - nie można wyświetlić spisu odcinków 7 sezonu "Ślub od pierwszego wejrzenia" (błąd)

### ISSUE THREAD

**Issue by traleka** [mbebe/blomqvist#743]
Player - nie można wyświetlić spisu odcinków 7 sezonu "Ślub od pierwszego wejrzenia" (błąd):

2022-03-22 21:15:40.904 T:955220864 WARNING: PLAYER.PL: ENTER: mode='listEpizody', name='\xc5\x9alub od pierwszego wejrzenia - Sezon 7', exlink='10780:5760184'
2022-03-22 21:15:41.009 T:1332736896 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2022-03-22 21:15:41.893 T:955220864 WARNING: Previous line repeats 1 times.
2022-03-22 21:15:41.893 T:955220864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'tuple' object has no attribute '_replace'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.playermb/main.py", line 1674, in <module>
                                                PLAYERPL().listEpizody(exlink)
                                              File "/storage/.kodi/addons/plugin.video.playermb/main.py", line 1298, in listEpizody
                                                meta = meta._replace(tytul=tytul)
                                            AttributeError: 'tuple' object has no attribute '_replace'
                                            -->End of Python script error report<--

**Comment by hevet** [comment]
U mnie wczytuje poprawnie.
Jaka wersja Kodi, system?
