### ISSUE TITLE
Vectra - wtyczka wyrzuca błąd przy wyborze kategorii "Telewizja" i nie pokazuje spisu kanałów

### ISSUE THREAD

**Issue by traleka** [mbebe/blomqvist#744]
Vectra - wtyczka wyrzuca błąd przy wyborze kategorii "Telewizja" i nie pokazuje spisu kanałów:

2022-03-22 23:16:49.992 T:1009775488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vectrapl/main.py", line 102, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.vectrapl/main.py", line 65, in router
                                                Vectra.listTV(exlink, kateg = True)
                                              File "/storage/.kodi/addons/plugin.video.vectrapl/resources/lib/vectra/__init__.py", line 234, in listTV
                                                img = dt.get("images",None).get("icon",None)[0].get("url",None)
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--

**Comment by mbebe** [comment]
Nie mam loginu do vectra, ale poprawka idzie.
Sprobuj te wersje.
[plugin.video.vectrapl-0.5.zip](https://github.com/mbebe/blomqvist/files/8334602/plugin.video.vectrapl-0.5.zip)

**Comment by Adam5991** [comment]
> Nie mam loginu do vectra, ale poprawka idzie.
> Sprobuj te wersje.
> [plugin.video.vectrapl-0.5.zip](https://github.com/mbebe/blomqvist/files/8334602/plugin.video.vectrapl-0.5.zip)
> 
> 

Cześć, wielki szacun za to co robisz 💪 nie moge doczekać się generatora M3U do Vectry, jeżeli login i hasło pomoże w rozwinięciu wtyczki  odezwij się na Pw, pakiet platynowy,  eleven, HBO i sport na ostro

**Comment by traleka** [comment]
W nowej wersji wtyczki można przejść o jeden krok dalej czyli zobaczyć kategorie kanałów w menu "Telewizja", ale przy wyborze dowolnej kategorii kręci się kółko oczekiwania i nic się nie dzieje (nie pojawia się spis kanałów z danej kategorii):

2022-03-23 21:31:07.504 T:1418720128   ERROR: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.vectrapl/main.py): script didn't stop in 5 seconds - let's kill it
2022-03-23 21:31:07.506 T:1418720128   ERROR: GetDirectory - Error getting plugin://plugin.video.vectrapl/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.vectrapl%2fresources%2f..%2ficon.png&mode=listtv&movie=True&moviescount=0&page=0&title=Og%c3%b3lne&url=ogolne
2022-03-23 21:31:07.517 T:1937729984   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vectrapl/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.vectrapl%2fresources%2f..%2ficon.png&mode=listtv&movie=True&moviescount=0&page=0&title=Og%c3%b3lne&url=ogolne) failed
2022-03-23 21:31:08.530 T:1937729984  NOTICE: NFS is idle. Closing the remaining connections.
2022-03-23 21:32:18.052 T:1906004864  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
2022-03-23 21:32:23.067 T:1799328640   ERROR: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.vectrapl/main.py): script didn't stop in 5 seconds - let's kill it
2022-03-23 21:32:23.307 T:1799328640   ERROR: GetDirectory - Error getting plugin://plugin.video.vectrapl/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.vectrapl%2fresources%2f..%2ficon.png&mode=listtv&movie=True&moviescount=0&page=0&title=Informacja&url=informacja
2022-03-23 21:32:23.327 T:1937729984   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vectrapl/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.vectrapl%2fresources%2f..%2ficon.png&mode=listtv&movie=True&moviescount=0&page=0&title=Informacja&url=informacja) failed

**Comment by mbebe** [comment]
tu wersja z generowaniem listy.
[plugin.video.vectrapl-0.6.zip](https://github.com/mbebe/blomqvist/files/8352908/plugin.video.vectrapl-0.6.zip)

**Comment by zuzia-dev** [comment]
Instalacja na czysto, nie działa, brak zarządzania urządzeniami, zamyka Kodi, brak wpisów w logach. Test na Kodi 19.4.

**Comment by isillo** [comment]
Potwierdzam, wtyczka w wersji 0.6 nie dziala i wywala Kodi 19.4.

**Comment by Adam5991** [comment]
U mnie wszystko śmiga od chwili uruchomienia wtyczki ver 0.6 na kodi 19.3 android

**Comment by zuzia-dev** [comment]
Kodi 19.4 sprawia problemy w wielu wtyczkach. Dziś ostatni dzień miesiąca, dobry czas na test wtyczki Vectry, w razie czego blokada konta wyzeruje się 1 kwietnia i to nie jest primaaprilisowy żart :)

**Comment by zuzia-dev** [comment]
@mbebe pod Kodi 19.4 jest crash, ale tylko przy pierwszym uruchomieniu wtyczki, podczas próby wejścia do konfiguracji, by ustawić login i hasło. Przy drugim podejściu już jest OK. W logach nie ma nic szczególnego. Przetestowałam kanały na żywo i trajlery VOD - działa jak powinno.
