### ISSUE TITLE
CanalPLUS-VOD (błąd przy próbie odtwarzania serialu)

### ISSUE THREAD

**Issue by traleka** [mbebe/blomqvist#745]
CanalPLUS-VOD (błąd przy próbie odtwarzania serialu np. Busz w ogniu):

2022-03-23 21:46:59.802 T:1418720128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canalplusvod/main.py", line 1384, in <module>
                                                PLAYvod2(exlink)
                                              File "/storage/.kodi/addons/plugin.video.canalplusvod/main.py", line 429, in PLAYvod2
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-03-23 21:47:00.173 T:1937729984   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.canalplusvod/?name=Busz+w+ogniu+-+Sezon+1+-+%5BCOLOR+lightgreen%5DOdcinek+1%5B%2FCOLOR%5D&moviescount=0&url=...]
2022-03-23 21:47:11.288 T:1312617344 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder

**Comment by hevet** [comment]
Chyba czas porzucić Kodi 18.
U mnie błędu brak.

**Comment by traleka** [comment]
Zainstalowałem dziś LibreELEC (Kodi 19) 10.0.2 i materiał się zacząć odtwarzać, ale odtwarzanie jest co chwila przerywane buforowaniem danych.

Wróciłem do LibreELEC 9.2 (Kodi 18) i znowu materiały nie chciały się odtwarzać. Okazało się, że jest jakiś problem z Widevine: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495

Po wykonaniu modyfikacji spod linka podanego powyżej odtwarzanie materiałów wideo znów działa, ale odtwarzanie przycina i co chwila leci buforowanie danych dokładnie tak jak to była na Kodi w wersji 19.

Zaczyna mi już brakować pomysłów co dalej :)
