### ISSUE TITLE
Fifa plus nie działa kategoria archiwum.

### ISSUE THREAD

**Issue by hevet** [mbebe/blomqvist#798]
Po wejściu w kategorię "Archive" pokazuje się lista podkategorii, ale próba wejścia w nie kończy się błędem dodatku.

`Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: [Errno Expecting value] : 0
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py", line 6, in <module>
                                                       Fifa()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\resources\lib\fifa.py", line 363, in __init__
                                                       plugin.run()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\resources\lib\fifa.py", line 334, in playvid
                                                       jsdata = helper.request_sess(url, 'get', headers=helper.headers, json=True)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\resources\lib\helper.py", line 154, in request_sess
                                                       return resp.json() if json else resp_text(resp)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 917, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
                                                   -->End of Python script error report<--`

**Comment by jestemWesolyRomek** [comment]
Mam ten sam problem. Można coś zaradzić?

**Comment by mbebe** [comment]
Zaktualizowalem. Powinno dzialac.

**Comment by hevet** [comment]
Dzięki działa :)

**Comment by jestemWesolyRomek** [comment]
Dzięki, jest w porządku.
