### ISSUE TITLE
Fifa Plus Error

### ISSUE THREAD

**Issue by Air-w0lf** [mbebe/blomqvist#820]
Hello, I am using v0.2 of the Fifa Plus plugin and get the following error when trying to play this video:

Originals->Binge Watch Series->Mysteries of Football->Season 1->UFOs

Can someone please help?

```
2022-08-16 20:50:39.445 T:8548    ERROR <general>: C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cxm-api.fifa.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2022-08-16 20:50:39.625 T:8548     INFO <general>: CPythonInvoker(10, C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py): script successfully run
2022-08-16 20:50:39.746 T:8548     INFO <general>: Python interpreter stopped
2022-08-16 20:50:42.687 T:16104    INFO <general>: initializing python engine.
2022-08-16 20:50:43.168 T:16104   ERROR <general>: C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cxm-api.fifa.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2022-08-16 20:50:43.775 T:16104    INFO <general>: CPythonInvoker(11, C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py): script successfully run
2022-08-16 20:50:43.885 T:16104    INFO <general>: Python interpreter stopped
2022-08-16 20:50:48.300 T:12636    INFO <general>: initializing python engine.
2022-08-16 20:50:48.780 T:12636   ERROR <general>: C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cxm-api.fifa.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2022-08-16 20:50:50.927 T:12636    INFO <general>: CPythonInvoker(12, C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py): script successfully run
2022-08-16 20:50:51.070 T:12636    INFO <general>: Python interpreter stopped
2022-08-16 20:50:55.012 T:1972     INFO <general>: initializing python engine.
2022-08-16 20:50:55.496 T:1972    ERROR <general>: C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cxm-api.fifa.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2022-08-16 20:50:56.977 T:1972     INFO <general>: Skipped 1 duplicate messages..
2022-08-16 20:50:56.977 T:1972     INFO <general>: CPythonInvoker(13, C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py): script successfully run
2022-08-16 20:50:57.092 T:1972     INFO <general>: Python interpreter stopped
2022-08-16 20:50:58.181 T:16688    INFO <general>: initializing python engine.
2022-08-16 20:50:58.541 T:16688    INFO <general>: CPythonInvoker(14, C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py): script successfully run
2022-08-16 20:50:58.658 T:16688    INFO <general>: Python interpreter stopped
2022-08-16 20:51:00.041 T:7236     INFO <general>: initializing python engine.
2022-08-16 20:51:00.523 T:7236    ERROR <general>: C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cxm-api.fifa.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2022-08-16 20:51:02.630 T:7236    ERROR <general>: Skipped 2 duplicate messages..
2022-08-16 20:51:02.630 T:7236    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: [Errno Expecting value] : 0
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\main.py", line 6, in <module>
                                                       Fifa()
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\resources\lib\fifa.py", line 376, in __init__
                                                       plugin.run()
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\resources\lib\fifa.py", line 350, in playvid
                                                       jsdata = helper.request_sess(url, 'get', headers=helper.headers, json=True)
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\resources\lib\helper.py", line 154, in request_sess
                                                       return resp.json() if json else resp_text(resp)
                                                     File "C:\Users\xxxx0\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 917, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
                                                   -->End of Python script error report<--
                                                   
2022-08-16 20:51:02.748 T:7236     INFO <general>: Python interpreter stopped
2022-08-16 20:51:02.773 T:12032   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fifaplusbeta/playvid/6sCkgstsbYkkDpdlypIb4L|videoDetails]
2022-08-16 20:51:10.974 T:12032    INFO <general>: Loading skin file: Custom_1100_AddonLauncher.xml, load type: KEEP_IN_MEMORY
2022-08-16 20:51:14.795 T:12032    INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2022-08-16 20:51:16.290 T:12032 WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2022-08-16 20:51:16.722 T:18376    INFO <general>: Skipped 14 duplicate messages..
2022-08-16 20:51:16.722 T:18376    INFO <general>: CPythonInvoker(3, C:\Users\xxxx0\AppData\Roaming\Kodi\addons\plugin.video.fifaplusbeta\serverHTTP.py): script successfully run
2022-08-16 20:51:16.783 T:18376    INFO <general>: Python interpreter interrupted by user
2022-08-16 20:51:20.574 T:12032    INFO <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
2022-08-16 20:51:21.724 T:12032    INFO <general>: Stopping player
2022-08-16 20:51:21.724 T:12032    INFO <general>: Storing total System Uptime
2022-08-16 20:51:21.724 T:12032    INFO <general>: Saving settings
2022-08-16 20:51:21.727 T:12032    INFO <general>: Saving skin settings
2022-08-16 20:51:21.727 T:12032    INFO <general>: Stopping all
2022-08-16 20:51:21.727 T:12032    INFO <general>: ES: Stopping event server
2022-08-16 20:51:21.728 T:12032    INFO <CWebserver[8080]>: Stopped
2022-08-16 20:51:22.415 T:19052    INFO <general>: ES: UDP Event server stopped
```

**Comment by mbebe** [comment]
updated

**Comment by Air-w0lf** [comment]
Thank you - the issue is resolved.
