### ISSUE TITLE
[fmovies] How do you search for something that has spaces in its title?

### ISSUE THREAD

**Issue by pitsi** [mbebe/blomqvist#832]
As the title suggests, I would like to know how it can be done.
Let's take game of thrones as an example. If I simply search it like so `game of thrones`, this comes up in the log
```
2022-09-06 15:57:21.977 T:140043337516800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1238, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1231, in router
                                                ListMovies(url,'1')
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 168, in ListMovies
                                                links, serials, pagin = getMovies(exlink,page)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 223, in getMovies
                                                result = parseDOM(html, 'div', attrs={'class': "filmlist\s+.*?"}) [0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2022-09-06 15:57:22.161 T:140043490412288   ERROR: GetDirectory - Error getting plugin://plugin.video.fmoviesto/?image=DefaultAddonsSearch.png&mode=search&movie=True&moviescount=0&page=1&title=%5bCOLOR%20lightblue%5dSearch%5b%2fCOLOR%5d&url
2022-09-06 15:57:22.173 T:140044958910592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fmoviesto/?image=DefaultAddonsSearch.png&mode=search&movie=True&moviescount=0&page=1&title=%5bCOLOR%20lightblue%5dSearch%5b%2fCOLOR%5d&url) failed
```
And the same happens with quotes around the name, like `"game of thrones"`. However, there are no issues when searching for titles that have no spaces, e.g. `deadpool`.

The above log is from kodi 18.9, which uses python2, but the same happens on kodi 19.4 which uses python3.

**Comment by umonkey13** [comment]
Can confirm searching of anything with a space in returns error and no results. 

Thanks for the update everything else appears to be working normally again.

**Comment by mbebe** [comment]
Updated, ver 1.20 should be in my repo soon.

**Comment by pitsi** [comment]
Thank you!
I would like to add that yesterday I tried stuff like `game-of-thrones`, `game_of_thrones`, `'game of thrones'` and so on, even the syntax with the escape characters for python, but none of them worked!
