### ISSUE TITLE
filman.cc

### ISSUE THREAD

**Issue by xenixganero** [mbebe/blomqvist#833]
Witam, w dodatku filman.cc na androidzie nie działa lista seriali (nie ma możliwości wyboru kolejnych stron) opcja szukaj również na działa :-( 
Z góry dziękuje za pomoc. Pozdrawiam.

**Comment by mtr81** [comment]
Co do wyszukiwarki, to działa w tej wersji -> [https://github.com/mbebe/blomqvist/issues/807#issuecomment-1187573328](https://github.com/mbebe/blomqvist/issues/807#issuecomment-1187573328)

**Comment by xenixganero** [comment]
Dzięki, wyszukiwarka w wersji 2.8 działa poprawnie. Gdyby jeszcze udało się poprawić błąd w liście seriali, byłoby super :-)

**Comment by mtr81** [comment]
Wersja z działającą paginacją w sekcji SERIALE.
[plugin.video.filmancc-2.9.zip](https://github.com/mbebe/blomqvist/files/9506486/plugin.video.filmancc-2.9.zip)
BTW. zauważyłem, że dostęp do niektórych seriali wymaga zalogowania - przykładowo: Gliniarze, Policjanci i Policjantki, Lombard. Nie pamiętam, żeby wcześniej tak było. Nie mam tam konta, więc nie wiem jak sobie radzi wtyczka w takiej sytuacji (bez logowania wywala błąd).

**Comment by xenixganero** [comment]
Teraz wszystko działa, wielkie dzięki :-) Do oglądania większości materiałów, wystarczy zalogować darmowe konto. Pozdrawiam.

**Comment by martiinezz** [comment]
Hmmm a u mnie wręcz odwrotnie niezależnie od wersji (mam 2.7) ale testowałem 2.8 i 2.9 bez skutku, zawsze pluje tym samym błędem:

2022-09-16 22:48:55.063 T:1514140544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1050: InsecureRequestWarning: Unverified HTTPS request is being made to host 'filman.cc'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2022-09-16 22:48:55.133 T:1514140544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 1087, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 991, in router
                                                listSeries(ex_link,page)
                                              File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 175, in listSeries
                                                mlinks,mparams = getSeries(ex_link,int(page),group)
                                              File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 639, in getSeries
                                                result=result[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2022-09-16 22:48:55.450 T:1450177408   ERROR: GetDirectory - Error getting plugin://plugin.video.filmancc/?ex_link=https%3a%2f%2ffilman.cc%2fseriale-online-pl%2f%7cOstatnio%20dodane%20seriale&foldername=%20Ostatnio%20dodane%20seriale&iconImage=DefaultFolder.png&mode=ListSeriale&page=1&token
2022-09-16 22:48:55.453 T:1937622080   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.filmancc/?ex_link=https%3a%2f%2ffilman.cc%2fseriale-online-pl%2f%7cOstatnio%20dodane%20seriale&foldername=%20Ostatnio%20dodane%20seriale&iconImage=DefaultFolder.png&mode=ListSeriale&page=1&token) failed

**Comment by mtr81** [comment]
Jaka wersja Kodi? Jakie urządzenie?

**Comment by martiinezz** [comment]
LibreElec 9.2.8 - RPi2 - Kodi 18.9

**Comment by mtr81** [comment]
Ech... poprawiając tą wtyczkę w ogóle nie zaprzątałem sobie zgodnością poprawności kodu z Kodi 18.

**Comment by martiinezz** [comment]
Widzę, że jest już na Pi2 Elec 10  :) trzeba się bedzie podnieść z wersją

**Comment by martiinezz** [comment]
Wskoczyłem na Kodi 19.3 - Seriale (lista) pusto a w logach tak:

2022-09-16 23:15:04.844 T:957      INFO <general>: initializing python engine.
2022-09-16 23:15:09.059 T:957     ERROR <general>: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'filman.cc'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2022-09-16 23:15:09.126 T:957      INFO <general>: CPythonInvoker(16, /storage/.kodi/addons/plugin.video.filmancc/main.py): script successfully run
2022-09-16 23:15:10.004 T:957      INFO <general>: Python interpreter stopped

**Comment by martiinezz** [comment]
Przy próbie szukania:
2022-09-16 23:16:54.600 T:971     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 1106, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 1073, in router
                                                       listFS(ex_link)
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 234, in listFS
                                                       mlinks,match = search(ex_link)
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 848, in search
                                                       result=parseDOM(content,'div', attrs={'id': "advanced-search"})[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-09-16 23:16:55.519 T:971      INFO <general>: Python interpreter stopped

**Comment by martiinezz** [comment]
Wtyczka 2.9 - co ciekawe pamięta dane z wyszukiwania ze starej wersji mimo, że przy odinstalowaniu kazałem wszystko usunąć.

**Comment by mtr81** [comment]
Odpowiedź jest jedna - Cloudflare.

**Comment by mtr81** [comment]
Prośba. Wrzuć odczyt z logu z poniższej wersji pomiędzy stringiem 'TEST-START' i 'TEST-END' - po użyciu wyszukiwania.
[plugin.video.filmancc_TEST.zip](https://github.com/mbebe/blomqvist/files/9588488/plugin.video.filmancc_TEST.zip)

**Comment by martiinezz** [comment]
Jakieś jaja - bo po zainstalowaniu tej wtyczki testowej - działa wyszukiwanie :) a jeszcze lepsze że w logach nie widzę stringu TEST:

grep TEST kodi.log 
Libre64:~/.kodi/temp #

**Comment by mtr81** [comment]
To jest dokładnie ta sama wersja co tutaj https://github.com/mbebe/blomqvist/issues/833#issuecomment-1239380741
tylko z wrzucaniem do logu Kodi odpowiedzi z wyszukiwania. Przeinstaluj na tą wersję, bo log będzie ci dosyć szybko 'puchł'.

**Comment by martiinezz** [comment]
tę też miałem zainstalowaną - jutro/pojutrze się temu dokładniej przyglądnę - dzięki za ekspresowe wsparcie

**Comment by martiinezz** [comment]
No i dzisiaj niespodzianka (wczoraj działało ładnie):

2022-09-18 20:51:40.307 T:833     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 1109, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 1007, in router
                                                       getEpisodes(ex_link)
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 216, in getEpisodes
                                                       episodes = scanEpisodes(ex_link)
                                                     File "/storage/.kodi/addons/plugin.video.filmancc/main.py", line 784, in scanEpisodes
                                                       gdzie=re.findall('Odcinki(.+?)Dodaj odcinek',content,re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--

:(

**Comment by mtr81** [comment]
To już nie kwestia Kodi a zabezpieczeń. Jak odpalisz pierwszy raz filmana.cc w przeglądarce zobaczysz coś takiego:
![filman](https://user-images.githubusercontent.com/86961563/190924482-ba00b79c-aedf-4764-9f88-7bdd56d2e068.png)

**Comment by martiinezz** [comment]
No właśnie przedwczoraj też widziałem coś takiego, a mimo to wtyczka działała, hmmmm

**Comment by martiinezz** [comment]
OK wlazłem z przeglądarki z kompa na stronkę i zaczęło działać - ale kombinatoryka

**Comment by skutylis** [comment]
Mi wyskakuje błąd logowania,i nie działa wyszukiwarka

niedz., 18 wrz 2022 o 22:31 martiinezz ***@***.***>
napisał(a):

**Comment by mtr81** [comment]
Wszedłeś przed odpaleniem wtyczki na stronę przez przeglądarkę? Zastosowano mechanizm podobny do cloudflare.

**Comment by skutylis** [comment]
Działa,dzięki.

pon., 19 wrz 2022 o 20:59 mtr81 ***@***.***> napisał(a):

**Comment by Smerd1233** [comment]
Od okolo tygodnia na wtyczce wyskakuje blad logowania, strona Filman  dziala pawidlowo na przegladarce logowanie rowniez, ale wtyczka nie rozpoznaje logowania, moze udalo by sie skorygowac problem jesli to oczywiscie jest mozliwe.
dziekuje.

**Comment by mtr81** [comment]
Co to znaczy nie rozpoznaje logowania. Wrzuć jakieś logi z Kodi.

**Comment by mtr81** [comment]
Tam są dwie rzeczy:
1. Oprócz loginu i hasła trzeba przepisać liczbę z obrazka (captcha) - bez problemu do ominięcia
2. W momencie wejścia na stronę logowania mielą się skrypty związane z cloudflare (w przeglądarce widać to tylko przy pierwszym wejściu) - z tym nie jestem nic w stanie zrobić

**Comment by Smerd1233** [comment]
uzywam kodi na android box, a filman wtyczke od mbebe, wiec rozumiem ze problemem jest cloudflare za ktorym sie schowali, 
moze za jakisczas odblokuja, dzieki za pomoc.

**Comment by mtr81** [comment]
Tzn. tą część związaną z przepisywaniem liczby z obrazka trzeba dopisać (w zasadzie mam to zrobione), zaś z cloudflare jest ten problem, że w tej chwili problem dotyka tylko adresu `filman.cc/logowanie`, reszta serwisu we wtyczce działa.

**Comment by Smerd1233** [comment]
wszystko dziala pieknie, gdyby jeszcze udalo sie poprawic wyszukiwarke, bo niestety nie dziala bylo by super, dzieki serdeczne za pomoc.

**Comment by mtr81** [comment]
Poprawiłem wyszukiwarkę i dodałem obsługę captchy przy logowaniu, natomiast nie jestem w stanie sprawdzić czy proces logowania kończy się sukcesem, bo nie mam tam konta.
[plugin.video.filmancc.zip](https://github.com/mbebe/blomqvist/files/9735170/plugin.video.filmancc.zip)

**Comment by Bogdan16** [comment]
witam
Podaj namiar [mtr81] ci podam dane do filman.cc

**Comment by Bogdan16** [comment]
witam
filman.cc zmienil na Proszę przesunąć przycisk do określonej pozycji
>> Przeciągnij suwak, aby zwerifikować
Pozdrawiam

**Comment by Smerd1233** [comment]
po zainstalowaniu tego nowego zipa wtczka kompletnie sie nie otwiera, wyskakuje tylko strona jak z wyszukiwarki i nic wiecej.

**Comment by mtr81** [comment]
Przełącz w ustawieniach wtyczki suwak w lewo przy "Logowanie w serwisie w lewo". Jest jakiś problem z logowaniem - muszę sprawdzić o co chodzi. Wyszukiwarka i reszta powinny działać.

**Comment by Smerd1233** [comment]
Suwak a Lewo, niestety mam puste foldery, nic sie nie otwiera, czy ktos z Panow moze sprawdzic u siebie, bo moze to tylko u mnie sie dzieje, Filman.cc ver 2.9

**Comment by Bogdan16** [comment]
wszystko dziala tylko mam blad logowania

**Comment by mtr81** [comment]
Sprawdziłem przed chwilą - u mnie logowanie działa

**Comment by Bogdan16** [comment]
To cos dziwnego ze u ciebie dziala Logowanie a ja mam wykupione i wyskakoje Blad Logowania

**Comment by mtr81** [comment]
Może kwestia rodzaju konta? Ja loguję się na darmowe
![filman](https://user-images.githubusercontent.com/86961563/194665327-92652f0e-c82b-429a-82a8-126dd57c170d.png)

**Comment by Bogdan16** [comment]
przepraszam mialem email wpisany zmienilem na login i wszystko jest ok

**Comment by mtr81** [comment]
OK. W każdym razie muszę w tej wtyczce jeszcze posprzątać kod, bo przy nieudanym logowaniu czy nie przepisaniu kodu z obrazka wywala z wtyczki.

**Comment by Smerd1233** [comment]
Bogdan zainaalowales ostatniego zipa  z poprawkami od mtr?

**Comment by Bogdan16** [comment]
Tak ale sa problemy w wyszukiwaniu niekture seriale znajduje a niekture nie

**Comment by mtr81** [comment]
Których nie znajduje?

**Comment by Bogdan16** [comment]
NCIS HAWAII

**Comment by Smerd1233** [comment]
dalo by rade uaktualnic filman ver. do aktualnej w mbebe repo. to by bardzo ulatwilo wszystko. teraz jest 2.7

**Comment by mtr81** [comment]
@Bogdan16  Czyli wszędzie gdzie jest spacja... 
@Smerd1233 Jeżeli nie działa ci z zipa, nie będzie ci to samo działać z repo...

**Comment by Bogdan16** [comment]
ok bo mam jedno pytanie co musze zrobic w kodi bo mi nie dziala Player

**Comment by Smerd1233** [comment]
tylko dlaczego nie dziala ? wyinstalowalem wszstko i zainstalowaem ponownie, no i nie dziala ?

**Comment by Bogdan16** [comment]
ja zrobilem kodi na nowo i tylko zainstalowalem plugin filman.cc i jest ok

**Comment by mtr81** [comment]
@Bogdan16 jaka ver Kodi i jaki sprzęt/system?

**Comment by Bogdan16** [comment]
Mam zainstalowane Kodi v19.4 Matrix na Android Beelink GT-King i jest problem nie moge ogladac Player nie mam obrazu kreci sie kulko co musze zrobic
Odznaczamy-Zezwalaj na sprzętową akcelerację - DXVA2 tego nie mam jest MediaCodec i co mam zrobic

**Comment by mtr81** [comment]
Hmm musiałbyś wrzucić log, bo bez tego nie jestem w stanie stwierdzić co się dzieje. A działa Ci Polsat GO, czy cokolwiek co jest zabezpieczone DRM?

**Comment by Bogdan16** [comment]
Polsat Go 2 tygodnie temu jeszcze mi dzialal bez problemu

**Comment by mtr81** [comment]
Tzn. teraz nie działa? Stosujesz jakieś VPN-y, proxy?

**Comment by Bogdan16** [comment]
nie bo nie wykupilem bo wykupilem filman.cc a Player mam juz 2 rok

**Comment by Bogdan16** [comment]
apki dzialaja

**Comment by Smerd1233** [comment]
nie moge sie zalogowac, katalogi sa puste

**Comment by Bogdan16** [comment]
a jak sie logujesz przez email czy imie

**Comment by Smerd1233** [comment]
imie

**Comment by Bogdan16** [comment]
to dziwne bo ja przez email to samo mialem co ty a puzniej imie i wszystko dziala

**Comment by mtr81** [comment]
@Bogdan16  musiałbym zobaczyć log -> być może dzieje się to samo co w tym wątku [https://github.com/mbebe/blomqvist/issues/840#issuecomment-1258637237](https://github.com/mbebe/blomqvist/issues/840#issuecomment-1258637237) ale bez logu trudno stwierdzić
@Smerd1233 obstawiam problemy z cloudflare, w przeglądarce możesz tego nie widzieć. Musiałbyś spróbować otworzyć filmana na innej przeglądarce i sprawdzić czy przed załadowaniem strony nie procesują się jakieś skrypty tak jak tu [https://github.com/mbebe/blomqvist/issues/833#issuecomment-1250369274](https://github.com/mbebe/blomqvist/issues/833#issuecomment-1250369274)

**Comment by Smerd1233** [comment]
moge Ci jakos wyslac moj login?

**Comment by Smerd1233** [comment]
masakra sie ajkas porobila !!!

**Comment by Bogdan16** [comment]
na komputerzy mi wszystko chodzi mam windows 11 Player bez problemu mi chodzi

**Comment by mtr81** [comment]
@Smerd1233 jeśli to chodzi o cloudflare. to nie jest to kwestia logowania. Nawet bez logowania powinieneś mieć kontent w serialach/ filmach i móc korzystać z przeglądarki.

**Comment by mtr81** [comment]
@Bogdan16  PC, a box to zupełnie inne światy, poczynając od systemów operacyjnych. Nie ma co tego porównywać. Jesteś w stanie wrzucić log?

**Comment by Bogdan16** [comment]
mam Beelink GT-King Android 9 zaplacilem za niego 143€ wszystko mi dzialalo bez problemu a od pewnego czasu klapa z Player
a czekam na dostawe GT-King II a za ten model 199€ to nie jest tani szpas

**Comment by Bogdan16** [comment]
a gdzie go znajde ten Log w kodi

**Comment by Smerd1233** [comment]
ale ja nie mam problemu z logowanien sie na kompie w filman, tylko na app. w kodi

**Comment by Bogdan16** [comment]
to wykasoj kodi i zainstaloj na nowo kodi u mnie to zadzialalo

**Comment by mtr81** [comment]
@Bogdan16  Tu masz instrukcję odnośnie  tego jak przygotować log ->https://forum.kodiwpigulce.pl/showthread.php?tid=2478
@Smerd1233 powtarzam, że z tego co opisujesz problem z wtyczką nie dotyczy logowania, tylko tego, że cloudflare blokuje jej działanie, o czym świadczą puste listy seriali i filmów. To powinieneś mieć nawet bez zalogowania.

**Comment by Smerd1233** [comment]
czyli trzeba poczekac az moze odblokuja ?

**Comment by Bogdan16** [comment]
przedtem mialem te repo i wszystko mi dzialalo  repository.mbebe-0.7.zip 
a puzniej zainstalowalem te [repository.mbebe-0.9.zip] i sie zepsulo

**Comment by mtr81** [comment]
Tak, chociaż ostatnio zauważam, że te blokady pojawiają się coraz częściej. Zazwyczaj pomaga wcześniejsze skorzystanie z filmana w przeglądarce (na tym samym urządzeniu), a dopiero potem odpalenie wtyczki.

**Comment by mtr81** [comment]
@Bogdan16  czyli wtyczka do playera na tym urządzeniu Ci kiedyś działała?

**Comment by Bogdan16** [comment]
tak i super zadnego problemu nie mialem

**Comment by mtr81** [comment]
@Bogdan16 A sprawdź jeszcze czy masz zainstalowany InputStream Adapive. ->[https://github.com/mbebe/blomqvist/issues/840#issuecomment-1257077976](https://github.com/mbebe/blomqvist/issues/840#issuecomment-1257077976)

**Comment by Bogdan16** [comment]
mam

**Comment by mtr81** [comment]
A umiesz dodać coś do listy IPTV Simple Client? Bo bym Ci zapodał coś co pozwoliłoby sprawdzić czy Kodi odtwarza ci materiały zabezpieczone DRM?

**Comment by Bogdan16** [comment]
moge

**Comment by mtr81** [comment]
To wrzuć na listę M3U, to i sprawdź czy się odtwarza (powinna być plansza + audio)
```
#EXTINF:-1,TVN24BIS Audio (z Playera)
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://go.tvn24.pl/api/products/12331/drm/widevine?platform=ANDROID_TV&type=LIVE|Content-Type=|R{SSM}|
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://r.dcs.redcdn.pl/livedash/o2/tvn24go/live/tvn24_bis/audio.isml?indexMode=
```

**Comment by Bogdan16** [comment]
juz sprawdzam

**Comment by Bogdan16** [comment]
nie dziala

**Comment by mtr81** [comment]
Czyli prawdopodobnie problem z odtwarzaniem materiałów zabezpieczonych DRM, ale bez logu nie jestem w stanie powiedzieć, w którym miejscu wykłada się Kodi.

**Comment by Bogdan16** [comment]
ok to podam ci log ale musze troche po studiowac i serdeczne dzieki za pomoc

**Comment by mtr81** [comment]
Poprawka wyszukiwarki (spacje w zapytaniach) 
[plugin.video.filmancc.zip](https://github.com/mbebe/blomqvist/files/9738039/plugin.video.filmancc.zip)

**Comment by Bogdan16** [comment]
serdecznie dziekuje
mam jeszcze jedno pytanie w log jest pare w kolorze zultym i czerwonym

**Comment by mtr81** [comment]
Tzn. w tej wtyczce do tworzenia logów?

**Comment by Bogdan16** [comment]
tak

**Comment by mtr81** [comment]
Najświeższy, bez względu na kolor.

**Comment by mtr81** [comment]
Logi są długie, wrzuć link

**Comment by Bogdan16** [comment]
to musze utworzyc za chwile zapodam

**Comment by Bogdan16** [comment]
witam
Jest znowu problem pisze Wprowadź kod weryfikacyjny, aby kontynuować dostęp:

**Comment by Bogdan16** [comment]
VPN nie pomaga

**Comment by mtr81** [comment]
VPN do tego nic nie ma.

**Comment by Bogdan16** [comment]
na filman.cc problemy chyba maja 503 Service Temporarily Unavailable

**Comment by Bogdan16** [comment]
jest mozliwosc dotac ta opcje  Wprowadź kod weryfikacyjny, aby kontynuować dostęp:

**Comment by mtr81** [comment]
Możliwość jest, ale mija się to z celem. Raz, że obecnie znowu jest  aktywna blokada cloudflare, dwa, że ludzie z filmana pewnie śledzą ten wątek i wymyślą kolejne ograniczenie. Jak masz tam konto, to najwygodniej będzie skorzystać z ich apki.

**Comment by Bogdan16** [comment]
tylko od nich ta apka nie aktualizuje seriali

**Comment by Bogdan16** [comment]
moze pan poprawic bo wylonczyli juz blokade cloudflare

**Comment by mtr81** [comment]
Blokada dalej jest. W wersji poniżej dodałem opcję "Cloudflare Test", której wywołanie pozwala na sprawdzenie czy blokada jest aktywna (test kończy się wówczas komunikatem: _Brak dostępu: cloudflare_).
[plugin.video.filmancc.zip](https://github.com/mbebe/blomqvist/files/9742881/plugin.video.filmancc.zip)

**Comment by Bogdan16** [comment]
mam zalonczonego VPN i nic mi nie pokazoje

**Comment by Bogdan16** [comment]
pokazoje mi ale dziwne to jest na stronie daja na kodi plugin.video.filmancc.2.9.zip a blokoja to dziwne jest

**Comment by Bogdan16** [comment]
witam ale na tej poprawce trzeba wpisywac 4 cyfrowy kod mozna to usunac
Pozdrawiam

**Comment by martiinezz** [comment]
będą utrudniać życie :) - ja myślę czy nie dałoby rady aby zalogować się wejść z przeglądarki na kompie - zapisać ciasteczka i nimi przedstawiać się z poziomu Kodi - pewnie upierdliwe - ale chyba jedyne sensowne jak ciągle coś się zmienia.

**Comment by mtr81** [comment]
Jedyne sensowne rozwiązanie - olać i nie korzystać :-)

**Comment by notoco** [comment]
Czyli to o czym mówiłem ci na forum kwp :)

**Comment by szefu19** [comment]
Czesc wszystkim
Na poaczatku chcialbym serdecznie podziekowac osobie (osobom), ktore probuja "wskrzesic" wtyczke do poprawnego dzialania. Sam (i pewnie wiele osob) czest korzystam z filmana, glownie do ogladania seriali. Pobralem poprawione wersje z tego tematu i niestety raz dziala, raz nie. O ile wiem, ze w przypadku gdy aktywne jest Cloudflare niewiele da sie zrobic to niestety dzisiaj pomimo, ze CF bylo wylaczone na stronie nadal byl problem z ogladaniem. U mnie jest tak, ze niestety nie da sie zalogowac (ostatnio dzialalo). Przy logowaniu wyrzuca Captcha do wpisania, wpisuje i pokazuje caly czas blad logowania, probowalem kilka razy i niestety nic (oczywiscie poprawnie przepisuje kod), caly czas blad. Mam KODI 19. Przedwczoraj bylo ok a dzisiaj niestety lipa. Bez zalogowania nie dziala wyszukiwarka, a jesli nawet recznie znajde sobie jakis serial (np. Lombard w Ostatnio dodane seriale) to niestety tez nie wchodzi w folder tylko wyrzuca blad.

**Comment by mtr81** [comment]
Podsumuję to tak. W przypadku Filmana potrzebny jest teraz bardziej patolog niż lekarz.

**Comment by Bogdan16** [comment]
witam
taka wiadomosc dostalem od filman.cc
Witam, kodi nie jest oficjalną aplikacją filmana i nie jest też specjalnie blokowana.

**Comment by mtr81** [comment]
Specjalnie czy niespecjalne nie ma znaczenia. Obecny kod Filmana uniemożliwia korzystanie z wtyczki.

**Comment by Smerd1233** [comment]
Moze sie sie zreflektuja jakiegos dnia i zdejma blokade, bo cokolwiek pisza to wieda ze blokuja serwis co nie pozwala nam kozystac z wtyczki na Kodi.

**Comment by rafalmar1981** [comment]
Witam postanowiłem sprawdzić wersje wtyczek z tego wątku:
filman.cc 2.8 bez logowania w serwisie oraz logowaniem wszystko działa oprócz wyszukiwarki
filman.cc 2.9
plugin.video.filmancc_TEST.zip](https://github.com/mbebe/blomqvist/files/9588488/plugin.video.filmancc_TEST.zip)[

**Comment by mtr81** [comment]
Logowanie na pewno nie działa, bo trzeba przejść captchę (i to nie tą z wpisywaniem danych z obrazka). Z kolei bez logowania nie działa wyszukiwarka (to ostatnie posunięcie Filmana).

**Comment by rafalmar1981** [comment]
nie skończyłem edytować postu a tu szybka odpowiedź :)..na każdej wersji praktycznie wszystko hula bez błędów tylko ta wyszukiwarka, a czy jest ten kod do wpisywania to w zasadzie bez różnicy

**Comment by szefu19** [comment]
No niestety nie jest tak kolorowo jak piszesz, ze tylko wyszukiwarka nie dziala bo filman wlaczyl wymog logowania przy przechodzeniu do konkretnych kategorii np. Filmy czy Seriale, we wtyczce logowanie nie dziala, wiec te kategorie tez nie dzialaja (teraz sprawdzalem na KODI), czasami jest tak, ze przechodzi do kategorii z filmami czy serialami bez logowania, ale juz przy probie wejscia w konkretny folder z tytulem serialu rowniez prosi o zalogowanie. Mozna to prosto sobie sprawdzic na ich stronie gdzie da sie wejsc nie bedac zalogowanym a gdzie nie. Pozostaje liczyc, ze moze ktos poprawi we wtyczce logowanie aby przechodzilo CAPTCHA, ale znajac zycie filman zapewne znowu cos zmieni..

**Comment by rafalmar1981** [comment]
@szefu19 sprawdziłem na stronie filman.cc ja nie będąc zalogowanym wszystko trafiam, że mi odtwarza(może mam szczęście) wszystkie filmy i seriale, na kodi to co mnie interesuje to wchodzi ale masz racje chłopaki z filmana namieszali i nasi magicy się głowią nad tym serwisem niestety.

**Comment by glorifyday** [comment]
Co zrobić, żeby plugin do filmana cc aktualizował się z repo automatycznie?

**Comment by mtr81** [comment]
W repo jest wersja 2.7. więc inne - z tego wątku - ci się z niego nie zaciągną. 
Historię wyszukiwania skazujesz z menu kontekstowego dostępnego z poziomu któregokolwiek wyniku wyszukiwania ("Usuń całą historię").

**Comment by glorifyday** [comment]
Dzięki za odpowiedź. Kodi obsługuję pilotem, nie wiem, czy to daje dostęp do kontekstowego menu, ale jakoś dam radę.

Czy jest jakaś szansa na poprawkę wyszukiwania?

**Comment by gs188** [comment]
Czy komus ostatnio dziala wtyczka do Filman wersja 2.9?  w kodi przestalo mi 'captcha' wyswietlac juz od paru dni :(

**Comment by mtr81** [comment]
Na chwilę obecną:
1. przy wejściu na www - cloudflare
2. wyszukiwarka - tylko dla zalogowanych
3. logowanie - zabezpieczone captchą
4. dostęp do większości katalogów z odcinkami seriali - dla zalogowanych.
Mając na uwadze powyższe zapomnij o reaktywacji wtyczki.

**Comment by osip1992** [comment]
Czy ma ktos problem z zalogowaniem sie do wtyczki w wersjach 2.7, 2.9?

**Comment by muxyk** [comment]
> Czy ma ktos problem z zalogowaniem sie do wtyczki w wersjach 2.7, 2.9?

Przeczytałeś choć wątek w którym się dopisałeś? Wystarczy nawet przeczytać co jest napisane tuż nad Twoim pytaniem, a jak dalej nie wiesz, to czytaj wiecej.

**Comment by zalinek** [comment]
Mam w tym wszystkim dobrą informację dot. Filman, a mianowicie zauważyłem, że od niedawna (po jakiejś aktualizacji) wtyczka FanFilm w Kodi zaczęła ponownie wyszukiwać żródła z Filman-u!!! Od czasu wystąpienia błędu z logowaniem wtyczki Filman (i wyszukiwaniem w tej wtyczce), przestało też od razu wyszukiwać we wtyczce FanFilm źródła z Filman-u. I zrobiła się lipa, bo np. niektóre seriale, które miałem w FanFilmie dzięki źródłom z Filman-u nagle przestały się pojawiać - wyszukiwać i nie można było już oglądać. Jednak jak pisałem na wstępie, od niedawna wtyczka FanFilm ponownie zaczęła działać z serwisem Filman pomimo, że sama wtyczka Filman nadal pokazuje błąd logowania po uruchomieniu. Znów tak jak wcześniej we wtyczce FanFilm wyszukuje źródła z Filmanu i filmy i seriale z tych źródeł działają pomimo, że sama wtyczka Filman tego nie daje - błąd logowania itp. Nie wiem, czy ktoś jeszcze też to zauważył? Uważam, że FanFilm to jest w tej chwili super alternatywa dla pojedynczej, niedziałającej wtyczki Filman. Sprawdźcie u siebie, bo u mnie to działa!

**Comment by mtr81** [comment]
Bazują na 3ksodusie, który jest mirrorem filmana. Serwis padnie i problem wróci.

**Comment by zalinek** [comment]
Tak właśnie jest w tym KODI - już kilka lat go użytkuję i trwa ciągła walka z licznymi, co róż pojawiającymi się problemami, błędami i przeciwnościami, które trzeba pokonywać. Ale fakt faktem, że na chwilę obecną (do czasu upadku 3ksodus-a) to działa więc korzystajmy, póki można!

**Comment by notoco** [comment]
@mtr81 nie. Bazują na czymś innym. Zerknij w źródła. 3eksodus doszedł dopiero teraz a filman działa od jakiegoś czasu już. Jest inna metoda.

**Comment by zalinek** [comment]
Też nie bardzo mi to pasowało z tym mirrorem, bo także zauważyłem, że źródła 3ksodus zaczęły pojawiać się w FanFilmie całkiem niedawno. Ale faktem jest, że kilka pozycji które obsługiwał mi Filman, teraz obsługuje 3ksodus, ale także w moim FanFilmie tak jak pisałem pojawiają się od niedawna dokładnie źródła z Filman-a, których jakiś czas w ogóle od momentu upadku wtyczki Filman - FanFilm nie pokazywał. Więc coś jeszcze innego chyba jest na rzeczy, że wtyczka Filman nie działa prawidłowo (właściwie nie ma teraz z niej większego pożytku) a źródła z Filmana w FanFilmie działają aż miło, przynajmniej na razie.
