### ISSUE TITLE
Problem z wtyczką CanalPLUS-VOD

### ISSUE THREAD

**Issue by LukaszZdunek** [mbebe/blomqvist#852]
Dzień dobry,

Mam problem z wtyczką CanalPLUS-VOD czyściłem cache, odinstalowywałem i instalowałem różne wersje m.in. 1.7.5.1, 1.7.5.4, 1.7.5.5, na wszystkich mam ten sam problem nie mogę poprawnie oglądać kanałów na żywo.
Przy próbie włączenia jakiegokolwiek kanału jest dźwięk ale nie ma obrazu, tak jak na załączonym zrzucie ekranu.
Windows 11 x64, wersja Kodi obecna to 19.0 wcześniej korzystałem z 19.4 również występował ten sam błąd.

![image](https://user-images.githubusercontent.com/53077569/196285832-25d3c19d-982f-4a0c-b924-64f1470cef99.png)

**Comment by LukaszZdunek** [comment]
Dopiszę również że nie działa nic z kategorii VOD 
Poniżej log:
`2022-10-17 23:41:39.781 T:11464    INFO <general>: CPythonInvoker(21, C:\Users\lukas\AppData\Roaming\Kodi\addons\weather.multi\default.py): script successfully run
2022-10-17 23:41:39.998 T:11464    INFO <general>: Python interpreter stopped
2022-10-17 23:41:40.369 T:10112    INFO <general>: ###Trakt Error###: 403 Client Error: Forbidden for url: https://api.trakt.tv/sync/last_activities
2022-10-17 23:41:40.369 T:10112    INFO <general>: ###FEN###: TraktMonitor Service Update FEN TraktMonitor - Failed. Error from Trakt - Next Update in 40 minutes...
2022-10-17 23:41:40.436 T:5404     INFO <general>: script.module.slyguy - Proxy Started: http://127.0.0.1:52103/
2022-10-17 23:41:40.439 T:5404     INFO <general>: script.module.slyguy - Widevine Level (fallback): 3
2022-10-17 23:41:40.439 T:5404     INFO <general>: script.module.slyguy - HDCP Level (fallback): 0.0
2022-10-17 23:41:41.447 T:4936     INFO <general>: CPythonInvoker(24, C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.thepromise\thepromise.py): script successfully run
2022-10-17 23:41:41.694 T:4936     INFO <general>: Python interpreter stopped
2022-10-17 23:41:41.829 T:11700    INFO <general>: CPythonInvoker(23, C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.thepromise\thepromise.py): script successfully run
2022-10-17 23:41:42.062 T:11700    INFO <general>: Python interpreter stopped
2022-10-17 23:41:43.765 T:10164    INFO <general>: CPythonInvoker(25, C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py): script successfully run
2022-10-17 23:41:43.988 T:10164    INFO <general>: Python interpreter stopped
2022-10-17 23:41:45.746 T:9128     INFO <general>: initializing python engine.
2022-10-17 23:41:45.933 T:5172     INFO <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2022-10-17 23:41:50.220 T:6492     INFO <general>: CPythonInvoker(20, C:\Users\lukas\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\runner.py): script successfully run
2022-10-17 23:41:50.444 T:6492     INFO <general>: Python interpreter stopped
2022-10-17 23:41:50.656 T:9128     INFO <general>: CPythonInvoker(27, C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py): script successfully run
2022-10-17 23:41:50.872 T:9128     INFO <general>: Python interpreter stopped
2022-10-17 23:41:51.021 T:11428   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/046d22cf.jpg
2022-10-17 23:41:53.122 T:2640     INFO <general>: initializing python engine.
2022-10-17 23:41:53.391 T:2640     INFO <general>: CPythonInvoker(28, C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py): script successfully run
2022-10-17 23:41:53.621 T:2640     INFO <general>: Python interpreter stopped
2022-10-17 23:41:54.705 T:9392     INFO <general>: initializing python engine.
2022-10-17 23:41:54.993 T:9392     INFO <general>: CPythonInvoker(29, C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py): script successfully run
2022-10-17 23:41:55.210 T:9392     INFO <general>: Python interpreter stopped
2022-10-17 23:41:56.571 T:8988     INFO <general>: initializing python engine.
2022-10-17 23:41:56.979 T:8988     INFO <general>: @#@URL_VIDEO_DATAS: https://secure-gen-hapi.canal-plus.com/conso/playset/unit/12859413_70026
2022-10-17 23:41:57.188 T:8988    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'available'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 1398, in <module>
                                                       PLAYvod2(exlink)
                                                     File "C:\Users\lukas\AppData\Roaming\Kodi\addons\plugin.video.canalplusvod\main.py", line 372, in PLAYvod2
                                                       for stream_datas in value_datas_jsonparser["available"]:
                                                   KeyError: 'available'
                                                   -->End of Python script error report<--
                                                   
2022-10-17 23:41:57.412 T:8988     INFO <general>: Python interpreter stopped
2022-10-17 23:41:57.427 T:5172    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.canalplusvod/?mode=playCANvod2&url=https%3A%2F%2Fhodor.canalplus.pro%2Fapi%2Fv2%2Fmycanalint%2Fdetail%2Fef3c521f8b5c8707bdd196af715e9794%2Fokapi%2F12859412_70026.json%3FdetailType%3DdetailSeason%26objectType%3Dseason%26dsp%3DdetailPage%26episodeId%3D12859413_70026%7C12859413_70026&page=1&moviescount=0&movie=True&name=Minuta+ciszy+-+Sezon+1+-+%5BCOLOR+lightgreen%5DOdcinek+1%5B%2FCOLOR%5D&image=https%3A%2F%2Fthumb.canalplus.pro%2Fhttp%2Funsafe%2F%7BresolutionXY%7D%2Ffilters%3Aquality%2870%29%2Fr.dcs.redcdn.pl%2Fhttp%2Fo2%2Fn%2FedytorEPG%2Fmycanal%2F10780000%2FA_10789715.jpg]
`

**Comment by hevet** [comment]
U mnie wszystko działa poprawnie, czy to na androidzie, czy na Windowsie 11.

**Comment by mbebe** [comment]
Wejdz w addons>>my addons>>videoplayerInputstream>>
![can1](https://user-images.githubusercontent.com/30195202/196393153-3a56239c-2941-4c7a-9eb3-0b2b744ad1cd.jpg)

prawy klik na InputstreamAdaptive i ustawienia.
Zmien stream selection na Manualy stream selection.
![can2](https://user-images.githubusercontent.com/30195202/196393178-61aa5015-5104-44c7-8a5a-0c903a55070f.jpg)

I podczas odtwarzania zmien rozdzielczosc na nizsza.
kolko zebate >> video settings >>
![can3](https://user-images.githubusercontent.com/30195202/196393653-b9ea893a-7094-4ee7-9c3a-9daf0079ea87.jpg)

Najwyzsza rozdzielczosc nie dziala (raczej) na KODI.

**Comment by hevet** [comment]
Na telefonie z Androidem,  działa najwyższa rozdzielczość. 🙂

**Comment by mbebe** [comment]
No to na windowsach. ;-)

**Comment by LukaszZdunek** [comment]
Niestety to nie jest problem z wysoką jakością. Próbowałem wszystkich dostępnych i przy każdej rozdzielczości tak samo się dzieje lub Kodi się wyłącza.

**Comment by kamilkamil123** [comment]
działa wam wtyczka canalplus ?

**Comment by hevet** [comment]
Nie działa. Jest błąd logowania.

**Comment by hevet** [comment]
Sprawdźcie czy ta wersja Wam działa
[plugin.video.canalplusvod.zip](https://github.com/mbebe/blomqvist/files/10056413/plugin.video.canalplusvod.zip)

**Comment by kamilkamil123** [comment]
niestety

**Comment by hevet** [comment]
U mnie zadziałała 
![Uploading IMG_20221121_134215.jpg…]()

**Comment by hevet** [comment]
![IMG_20221121_134215](https://user-images.githubusercontent.com/43666290/203058332-150c806b-e91a-4dd4-9aa9-9e29040a98fb.jpg)

**Comment by hevet** [comment]
@praspp tak.

**Comment by juszynsk** [comment]
Czy ktoś nadal ma problem z logowaniem ? 
Wersja wtyczki 1.7.5.8 

Raspberyy Pi2 , Libreelec 10

2022-11-21 16:23:07.408 T:645      INFO <general>: SETTINGS: run # Waiting
2022-11-21 16:23:26.798 T:612      INFO <general>: JSONRPC Server: New connection added
2022-11-21 16:23:30.600 T:586      INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2022-11-21 16:23:30.932 T:654      INFO <general>: initializing python engine.
2022-11-21 16:23:39.022 T:654     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.canalplusvod/main.py", line 1331, in <module>
                                                       home()
                                                     File "/storage/.kodi/addons/plugin.video.canalplusvod/main.py", line 108, in home
                                                       CANALvod().logowanie()
                                                     File "/storage/.kodi/addons/plugin.video.canalplusvod/main.py", line 840, in logowanie
                                                       self.DEVICE_ID = re.compile(r'deviceId\"\:\"(.*?)\"').findall(resp_device_id.text)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-11-21 16:23:39.717 T:654      INFO <general>: Python interpreter stopped
2022-11-21 16:23:39.733 T:653     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.canalplusvod/
2022-11-21 16:23:39.754 T:586     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canalplusvod/) failed

**Comment by hevet** [comment]
@juszynsk https://github.com/mbebe/blomqvist/issues/852#issuecomment-1321976179

**Comment by juszynsk** [comment]
> @juszynsk [#852 (comment)](https://github.com/mbebe/blomqvist/issues/852#issuecomment-1321976179)

Dzięki, Twoja paczka działa

**Comment by Piotreklabaj** [comment]
Witam u mnie błąd logowania 
![8567F191-777B-4F46-84D4-2ABBC2328657](https://user-images.githubusercontent.com/113371403/203169904-463d95db-6ffb-4b37-8a2f-0f1ee1f35b52.jpeg) 
Z góry dzięki za pomoc

**Comment by Piotreklabaj** [comment]
A na drugim tv takie logi 
![Uploading 02A88D25-2A40-4400-8AC5-874CDC0A1A95.jpeg…]()

**Comment by hevet** [comment]
> Witam u mnie błąd logowania ![8567F191-777B-4F46-84D4-2ABBC2328657](https://user-images.githubusercontent.com/113371403/203169904-463d95db-6ffb-4b37-8a2f-0f1ee1f35b52.jpeg) Z góry dzięki za pomoc

Niestety na zdjęciu nie ma żadnego błędu związanego z wtyczką Canal+. Wstaw normalne logi.

**Comment by Piotreklabaj** [comment]
Logi z poprawionej wtyczki nie działają kanały tv bardzo proszę o pomoc 
![Uploading 58BDB058-95B0-4AB4-A511-E46A7FC84787.jpeg…]()

**Comment by Piotreklabaj** [comment]
A gdzie to jest?

**Comment by Piotreklabaj** [comment]
Normalne czyli jakie w formie tekstu?

**Comment by Piotreklabaj** [comment]
Logi 


https://paste.kodi.tv/wafupipiza

**Comment by Piotreklabaj** [comment]
A jak ustawić?w tej kwestii jestem zielony

**Comment by hevet** [comment]
Na androidzie powinno być włączone.

**Comment by Piotreklabaj** [comment]
Czyli szukać w ustawieniach androida?

**Comment by Piotreklabaj** [comment]
Ja mam boxa MI Box S

**Comment by hevet** [comment]
W ustawieniach wtyczki.

**Comment by Piotreklabaj** [comment]
Witam wiem ze nie na temat ale mam prosbe o sprawdzenie logow.z góry dzięki za okazana pomoc chodzi o cda Prime Video i playera tvn

https://paste.kodi.tv/aharilipuw

**Comment by Piotreklabaj** [comment]
Dziś działała normalnie wtyczka canal plus.A teraz wchodzę i błąd odtwarzania.Zostawiam logi pozdrawiam 

https://paste.kodi.tv/ilomumunuk

**Comment by praspp** [comment]
> Sprawdźcie czy ta wersja Wam działa [plugin.video.canalplusvod.zip](https://github.com/mbebe/blomqvist/files/10056413/plugin.video.canalplusvod.zip)

@hevet  Możesz wskazać jakie zmiany wprowadziłeś w tej wersji poprawiając logowanie w 1.7.5.8 od mbebe?

**Comment by hevet** [comment]
@praspp 
[plugin.video.canalplusvod_1.5.6_debug.zip](https://github.com/mbebe/blomqvist/files/10146141/plugin.video.canalplusvod_1.5.6_debug.zip)

**Comment by praspp** [comment]
@hevet dzięki.

**Comment by BGT00** [comment]
błąd logowania nadal jest?
u mnie wtyczka od @hevet niestety wyrzuca albo błąd logowania lub brak danych(przy czym tutaj takjakby zalogowało sie ale kanałów dalej mam 5)
Jest jakaś solucja?
