### ISSUE TITLE
Polsat Box Go - nie można odtworzyć kanału telewizyjnego

### ISSUE THREAD

**Issue by the4anoni** [mbebe/blomqvist#860]
Cześć :)
Jak w temacie - zalogowałem się do wtyczki przez konto ICOK, wtyczka twierdzi że konto poprawne.
Jednak mimo wszystko nie mogę otworzyć kanału telewizyjnego, jest jakieś rozwiązanie?

Raspberry Pi 4B
LibreElec Stable Kodi 19.4

```
2022-10-24 17:49:37.457 T:2480    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: unexpected EOF while parsing (<string>, line 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.pgobox/main.py", line 1293, in <module>
                                                       ListTVS()
                                                     File "/storage/.kodi/addons/plugin.video.pgobox/main.py", line 297, in ListTVS
                                                       dups=IPLA().getEpgs()
                                                     File "/storage/.kodi/addons/plugin.video.pgobox/main.py", line 1026, in getEpgs
                                                       kanaly=eval(kanaly)
                                                     File "<string>", line 0
                                                       
                                                       ^
                                                   SyntaxError: unexpected EOF while parsing
                                                   -->End of Python script error report<--
                                                   
2022-10-24 17:49:37.800 T:2480     INFO <general>: Python interpreter stopped
2022-10-24 17:49:37.808 T:2479    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.pgobox/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.pgobox%2f%2fresources%2f..%2ficon.png&mode=listTVS&movie=True&moviescount=0&name=Kana%c5%82y%20TV&page=0&url
2022-10-24 17:49:37.834 T:972     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pgobox/?image=%2fstorage%2f.kodi%2faddons%2fplugin.video.pgobox%2f%2fresources%2f..%2ficon.png&mode=listTVS&movie=True&moviescount=0&name=Kana%c5%82y%20TV&page=0&url) failed
```

**Comment by mtr81** [comment]
Która wersja? Sprawdzałeś tą https://github.com/mbebe/blomqvist/issues/855#issuecomment-1286575256

**Comment by Cinek77** [comment]
A na stronie może sprawdzić konto ? Wtyczka bez loginu pokazuje że zalogowało.

**Comment by the4anoni** [comment]
> Która wersja? Sprawdzałeś tą [#855 (comment)](https://github.com/mbebe/blomqvist/issues/855#issuecomment-1286575256)

Ta wersja działa poprawnie. Wcześniej testowałem na najnowszej wersji z repo mbebe.
