### ISSUE TITLE
Player PL nie dziala

### ISSUE THREAD

**Issue by Spike7712** [mbebe/blomqvist#863]
Witam, 
Od wczoraj nie moge wejssc na wtyczke player pl w kodi. Pokazuje sie blad, czy ktos rowniez ma taki sam problem? Polsat box tez taki sam problem.

**Comment by hevet** [comment]
U mnie normalnie działa Player jak i Polsat Box.
A co to za błąd, jaka wersja Kodi i system?

**Comment by Spike7712** [comment]
2022-10-29 14:04:09.918 T:3492  WARNING <general>: PLAYER.PL: ENTER: mode=None, name=None, exlink=None
2022-10-29 14:04:10.630 T:3492    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: [Errno Expecting value] <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
                                                   <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
                                                   <TITLE>ERROR: The request could not be satisfied</TITLE>
                                                   </HEAD><BODY>
                                                   <H1>403 ERROR</H1>
                                                   <H2>The request could not be satisfied.</H2>
                                                   <HR noshade size="1px">
                                                   Request blocked.
                                                   We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
                                                   <BR clear="all">
                                                   If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
                                                   <BR clear="all">
                                                   <HR noshade size="1px">
                                                   <PRE>
                                                   Generated by cloudfront (CloudFront)
                                                   Request ID: 7Z5XOE7ujoeUmYC6c7UV41xQLWIpiqjW_nD5d3cnNswbwVZXI1lk2w==
                                                   </PRE>
                                                   <ADDRESS>
                                                   </ADDRESS>
                                                   </BODY></HTML>: 0
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 1717, in <module>
                                                       home()
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 323, in home
                                                       playerpl.sprawdzenie2()
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 886, in sprawdzenie2
                                                       data = getRequests(self.SUBSCRIBER, data = POST_DATA, headers=self.HEADERS2,params=PARAMS)
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 404, in getRequests
                                                       return _getRequests(url, data=data, headers=headers, params=params)
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\plugin.video.playermb\main.py", line 374, in _getRequests
                                                       return content.json()
                                                     File "C:\Users\Patryk\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 917, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
                                                   <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
                                                   <TITLE>ERROR: The request could not be satisfied</TITLE>
                                                   </HEAD><BODY>
                                                   <H1>403 ERROR</H1>
                                                   <H2>The request could not be satisfied.</H2>
                                                   <HR noshade size="1px">
                                                   Request blocked.
                                                   We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
                                                   <BR clear="all">
                                                   If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
                                                   <BR clear="all">
                                                   <HR noshade size="1px">
                                                   <PRE>
                                                   Generated by cloudfront (CloudFront)
                                                   Request ID: 7Z5XOE7ujoeUmYC6c7UV41xQLWIpiqjW_nD5d3cnNswbwVZXI1lk2w==
                                                   </PRE>
                                                   <ADDRESS>
                                                   </ADDRESS>
                                                   </BODY></HTML>: 0
                                                   -->End of Python script error report<--
                                                   
2022-10-29 14:04:10.655 T:3492     INFO <general>: Python interpreter stopped
2022-10-29 14:04:10.665 T:848     ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.playermb/
2022-10-29 14:04:10.671 T:6384    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.playermb/) failed

**Comment by Spike7712** [comment]
[kodi.log](https://github.com/mbebe/blomqvist/files/9894433/kodi.log)

**Comment by Spike7712** [comment]
Nie moge wogole otworzyc aplikacji. Kodi wersja na Windows 19.4 Matrix

**Comment by Spike7712** [comment]
Wtyczki mialem na mysli*

**Comment by mywildsoul** [comment]
Witam, na urzadzeniu z googleTV/androidTV od wczoraj jest błąd obrazu. Słychać tylko dźwięk, ale tylko przez około minutę, później buforuje i juz dalej nie uruchamia się. Co dziwne na telefonie z android wszystko działa bez problemu

**Comment by hevet** [comment]
U mnie jest to samo.

**Comment by mywildsoul** [comment]
Pomógł downgrade InputStream adaptive do 20.3.16, jednak myślę że jest to tymczasowe rozwiązanie. Może autor wtyczki cos zaradzi?

**Comment by hevet** [comment]
Problem jest już zgłoszony przez mtr81 do twórców inputstream adaptive.
