### ISSUE TITLE
Issue: The category "WatchProWrestling.live" does not open

### ISSUE THREAD

**Issue by TitanME** [mbebe/blomqvist#865]
- **Addon**: Wrestlingwatch_cam version 0.4
- **Kodi**: 19.4 Matrix
- **Issue**: The category "WatchProWrestling.live" does not open

2022-11-06 11:00:45.291 T:5164    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'fanartFANART' is not defined
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.wrestlingwatch\main.py", line 204, in Menu2
                                                       result = parseDOM(html,'ul', attrs={'id':"main-menu"})[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.wrestlingwatch\main.py", line 443, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.wrestlingwatch\main.py", line 419, in router
                                                       Menu2()
                                                     File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.wrestlingwatch\main.py", line 212, in Menu2
                                                       add_item('', '[COLOR pink][B]>=>=>=>=>=>=> error occured <=<=<=<=<=<=<[/B][/COLOR]', ikona, "err",fanartFANART, folder=False, IsPlayable=False)
                                                   NameError: name 'fanartFANART' is not defined
                                                   -->End of Python script error report<--

**Comment by crak3rjack** [comment]
@mbebe They changed some of the website structure and domain here's the new one!
https://watchprowrestling.org/

**Comment by TitanME** [comment]
@mbebe ...thx :thumbsup: :wink:
