### ISSUE TITLE
polsat box go problem logowanie

### ISSUE THREAD

**Issue by markus7227** [mbebe/blomqvist#921]
Jak w tytule postu. Zainstalowalem Na nowo kodi 20 (android tv 10),wtyczke mbebe dodatek polsat box go. po wpisaniu ptawidlowych danych logowania wywala blad logowania. Wiem, ze polsat wprowadzil nowy sposob logowania, trzeba na ich stronie wprowadzic kod wyswietlony na telewizorze. Da sie to jakos naprawic ??

**Comment by mtr81** [comment]
Logowanie przez ICOK zastąpiono SSO. Trzeba zmienić POST data we wtyczce. Inna rzecz, że aby logowanie przebiegło poprawnie trzeba autoryzować dostęp na iPolsat Box

**Comment by zalinek** [comment]
Mam taki sam problem. Wcześniej u rodziców: Kodi v.20 na Raspberry Pi 3 i wtyczka Polsat Box Go loguje do tej pory i działa bez problemu. Parę dni temu wykupiłem Polsat dla siebie i chciałem uruchomić Polsat Box Go na swoich urządzeniach tak, jak wcześniej u rodziców i napotkałem na problemy. O ile na urządzeniach - smartfonach z systemem Android dedykowana apka Polsatu "Polsat Box Go" loguje i działa poprawnie a także na komp. PC z windows-em poprzez przeglądarki www serwis "Polsat Box Go" loguję się i kanały TV działają OK. o tyle już na moim RPI 3B z XBian: Kodi v.20.1 z najnowszą wtyczką "Polsat Box Go" z repo od mbebe a także na Android TV (Android v.10.0) z Kodi v.20.1 najnowsza wtyczka "Polsat Box Go" nie loguje się - błąd logowania, niepoprawne dane logowania itp. Przełącznik rodzaju konta w opcjach wtyczki nic nie zmienia. Już parę dni walczę z tym problemem i nie mogę sobie poradzić - nie rozumiem np. tego:
"Trzeba zmienić POST data we wtyczce..."
 oraz
 "trzeba autoryzować dostęp na iPolsat Box (operacja jednorazowa, nie związana z wtyczką)
Bardzo proszę o jakąś krótką instrukcję jak krok po kroku poradzić sobie z tym problemem. Z góry dziękuję za pomoc, będę bardzo wdzięczny.

**Comment by mtr81** [comment]
Logujesz się za danymi konta na PBG czy innymi danymi? Czy na tej wgranej wersji wtyczki (i tym samym urządzeniu) jesteś w stanie się zalogować na konto rodziców?
Wypróbuj tą wersję [plugin.video.pgobox.zip](https://github.com/mbebe/blomqvist/files/11131990/plugin.video.pgobox.zip) - uaktualniłem w niej dane, które mają wędrować na serwer podczas logowania metodą konta PBG. Jeśli się nie uda, to włącz we kodi tryb debuglog i odczytaj mi z loga treść komunikatu, który pojawi się w odpowiedzi serwera, którą znajdziesz po frazie 'login_response'

**Comment by zalinek** [comment]
Tak - loguję się moimi danymi, mojego nowo utworzonego konta Polsat Box Go (kiedyś ICOK) i loguje mnie do PBG - ICOK, do apki PBG na smartfonie z androidem i na PBG przez przeglądarki www na PC z win - pod KODI natomiast już nie loguje. 
Tak -  na stare konto PBG rodziców, na tym samym urządzeniu, systemie, wtyczce (pod KODI) loguję się właśnie bez najmniejszego problemu (tylko tym moim nowo - utworzonym kontem nie mogę się zalogować w KODI).
Dziękuję - zainstaluję jeszcze dzisiaj w wolnej chwili podesłaną wtyczkę i odpiszę czy zadziałało. A jak nie zadziała to spróbuję włączyć tego debuglog-a i wtedy zaczytam loga z KODI itd. wg. instrukcji. Bardzo dziękuję za zajęcie się moim problemem.

**Comment by zalinek** [comment]
Oto druga część mojego zadania:
- zainstalowałem manualnie uaktualnioną wtyczkę z linku powyżej - plugin.video.pgobox.zip, ale niestety bez względu na to 
  jakie dane logowania kąta wpisuję w opcjach wtyczki (rodziców czy moje) wtyczka zaraz po próbie uruchomienia zwraca błąd: 
  "Błąd Polsat Box Go więcej informacji na ten temat znajdziesz w pliku dziennika zdarzeń..." lub coś podobnego,
- następnie włączyłem w KODI tryb debugowania,
- wyczyściłem dodatkowo plik logów - kodi.log, żeby w pliku znalazło się tylko to co niezbędne, związane z moim problemem,
- uruchomiłem ponownie wtyczkę PBG,
- a oto treść, jaka pojawiła się w odpowiedzi serwera po frazie 'login_response':

2023-04-03 00:27:54.108 T:9754    debug <general>: login_response
2023-04-03 00:27:54.108 T:9754    debug <general>: 

2023-04-03 00:27:54.115 T:9754    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'dict' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/xbian/.kodi/addons/plugin.video.pgobox/main.py", line 1337, in <module>
    home()
  File "/home/xbian/.kodi/addons/plugin.video.pgobox/main.py", line 155, in home
    IPLA().logowanie()
  File "/home/xbian/.kodi/addons/plugin.video.pgobox/main.py", line 491, in logowanie
    print(data.text)
AttributeError: 'dict' object has no attribute 'text'
-->End of Python script error report<--

- dodatkowo może dla lepszej czytelności załączam całego mojego loga z tego błędu - loga zuploadowałem pod linkiem:
   https://paste.kodi.tv/hokolavuxi
Dziękuję bardzo za pomoc i czekam na dalsze ewentualne instrukcje.

**Comment by mtr81** [comment]
Ok. Tym razem to ja wywołałem błąd (zła struktura tego co miało trafić do logu). Przesyłam poprawioną wtyczkę z prośbą o powtórzenie tego samego.
[plugin.video.pgobox.zip](https://github.com/mbebe/blomqvist/files/11133638/plugin.video.pgobox.zip)

**Comment by zalinek** [comment]
PANOWIE JESTEŚCIE WIEEEEEEELCY!!! Moja radość jest nie do opisania! Jestem pełen podziwu dla Waszej wiedzy, ogromnej pasji, zaangażowania, poświęcenia i bezinteresowności z jaką to wszystko dla nas robicie - pomagacie. Oczywiście z tą wtyczką wszystko działa, moje nowe konto wreszcie się loguje i kanały TV działają jak należy! Mam jeszcze tylko takie skromne pytanie a mianowicie czy te poprawki można umieścić w liniowej wtyczce PBG w REPO, żeby wszystko się automatycznie aktualizowało? Mam jeszcze TV Android z KODI i wtedy bym sobie w łatwy sposób wtyczkę PBG zaktualizował bez konieczności ręcznej instalacji. Jeszcze raz BARDZO DZIĘKUJĘ I POZDRAWIAM!!!

**Comment by HF8FRN** [comment]
jak to pobrać jako wtyczka podczasz instalacji z zipu zamiast wyświetlić się ok to pokazuję foldery wtyczki jak to pobrać?

**Comment by jacek00** [comment]
@mtr81 niestety wtyczka chyba ponownie nie działa :( Dałbyś radę to naprawić? :)
