### ISSUE TITLE
Orange TV

### ISSUE THREAD

**Issue by pbaloo** [mbebe/blomqvist#947]
Orange TV  nie działa KODI w wersji 20.1 wtyczka wersja 0.5, fragment logu poniżej:

023-05-16 17:06:36.777 T:62      error <general>: .var/app/tv.kodi.Kodi/data/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tvgo.orange.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2023-05-16 17:06:37.406 T:62       info <general>: Skipped 1 duplicate messages..
2023-05-16 17:06:37.406 T:62    warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-05-16 17:06:40.317 T:65      error <general>: .var/app/tv.kodi.Kodi/data/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tvgo.orange.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2023-05-16 17:06:40.800 T:65       info <general>: Skipped 1 duplicate messages..
2023-05-16 17:06:40.800 T:65    warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-05-16 17:06:53.018 T:67       info <general>: Skipped 107 duplicate messages..
2023-05-16 17:06:53.018 T:67      error <general>: .var/app/tv.kodi.Kodi/data/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tvgo.orange.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2023-05-16 17:06:53.882 T:52       info <general>: Skipped 1 duplicate messages..
2023-05-16 17:06:53.882 T:52       info <general>: PVR Manager: Starting cleanup of cached images.
2023-05-16 17:06:53.952 T:51       info <general>: PVR Manager: Starting cleanup of cached images.
2023-05-16 17:06:54.058 T:52       info <general>: PVR Manager: Cleaned up 0 cached images.
2023-05-16 17:06:54.117 T:51       info <general>: PVR Manager: Cleaned up 0 cached images.
2023-05-16 17:06:56.292 T:67      error <general>: .var/app/tv.kodi.Kodi/data/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tvgo.orange.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2023-05-16 17:06:56.405 T:67       info <general>: Skipped 1 duplicate messages..
2023-05-16 17:06:56.405 T:67      error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File ".var/app/tv.kodi.Kodi/data/addons/plugin.video.orangetvgo/main.py", line 6, in <module>
                                                       OrangeGo()
                                                     File ".var/app/tv.kodi.Kodi/data/addons/plugin.video.orangetvgo/resources/lib/orange.py", line 707, in __init__
                                                       plugin.run()
                                                     File ".var/app/tv.kodi.Kodi/data/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File ".var/app/tv.kodi.Kodi/data/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File ".var/app/tv.kodi.Kodi/data/addons/plugin.video.orangetvgo/resources/lib/orange.py", line 360, in playtv
                                                       casToken = jsdata.get('casToken',None)
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-05-16 17:06:56.480 T:7       error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.orangetvgo/playtv/14135]

**Comment by jon10220** [comment]
U mnie to samo niestety na RPI4b w libreelec oraz na windowssie 10 wtyczka padła na amen

**Comment by shafau** [comment]
Wtyczka padła, ponieważ zmienił się wygląd strony. Aktualizacja wtyczki rozwiązałaby problem.

**Comment by mtr81** [comment]
[plugin.video.orangetvgo-0.6.zip](https://github.com/mbebe/blomqvist/files/11734267/plugin.video.orangetvgo-0.6.zip)

**Comment by jon10220** [comment]
Serdeczne dzięki za naprawę wtyczki, TV znowu działa OK
testowane na RPI4b Libreelec kodi 20.1

**Comment by pbaloo** [comment]
Na Win 11, Linux i android również działa. Dzięki wielkie.

**Comment by shafau** [comment]
@mtr81 Wielkie dzięki, wtyczka ponownie działa.
Dołączam listę .m3u pełnej oferty Orange TV GO. https://pastebin.com/jrmWJp6b

P.S. Wtyczka dość wolno wczytuje i odtwarza kanały (zdecydowanie wolniej niż np. Player). Można to w jakiś sposób zoptymalizować za pomocą ustawień, albo odchudzenia wtyczki?

**Comment by spliner21** [comment]
Hej,

Mam od niedawna nowe konto w Orange TV Go (zmiana oferty). Nowym użytkownikom wprowadzono szyfrowanie pinu. Poświęciłem wczoraj chwilę i przeportowałem to szyfrowanie (można je było wyjąć z kodu TypeScript strony Orange TV Go). Nie jestem pewien jaki jest warunek tego, czy PIN ma być szyfrowany, czy nie. Wstępnie dodałem regułę, że jeśli numer konta zaczyna się od litery (^[A-Z]), to wtedy pin ma być zaszyfrowany, w przeciwnym przypadku leci plain text.
Trzeba by to jeszcze zweryfikować. Mój numer konta zaczyna się od litery "M".

Wrzucam wtyczkę po moich poprawkach (bazowałem na wersji 0.6 z kilku komentarzy wyżej). U mnie po tych zmianach działa.
[plugin.video.orangetvgo-0.7.zip](https://github.com/mbebe/blomqvist/files/12270307/plugin.video.orangetvgo-0.7.zip)

**Comment by mayones2** [comment]
Czy nadal działa ci ta wtyczka? Dzisiaj dostałem dane do konta OrangeTV, ustawiłem PIN, ale nie mogę się zalogować w Kodi.

taki blad w logu
`InsecureRequestWarning: Unverified HTTPS request is being made to host 'tvgo.orange.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings                                                  warnings.warn(`

**Comment by mtr81** [comment]
To co wkleiłeś to nie jest błąd tylko ostrzeżenie - musisz szukać innej przyczyny.

**Comment by mayones2** [comment]
aaaa... ale dzisiaj już DZIAŁA :D

**Comment by shafau** [comment]
Macie może jakiś pomysł na uruchomienie kanałów, które są dostępne tylko na dekoderach/aplikacji na Android TV? Zmieniając deviceCat z otg na stb, lub conTv wtyczka pobiera kanały niedostępne w usłudze GO, jednak próba odtworzenia kończy się błędem "No channel sources matches the device type."
![kodi](https://github.com/mbebe/blomqvist/assets/38146828/470d0679-dee9-4d44-a212-7069f0309aab)

**Comment by mtr81** [comment]
Piszesz o apce na Android TV... Chodzi o tą aplikację? -> https://play.google.com/store/apps/details?id=com.orange.pl.orangetvgo&hl=pl&gl=US

**Comment by shafau** [comment]
@mtr81 nie, chodzi o tą -> https://play.google.com/store/apps/details?id=pl.orange.orangetv (apka dostępna tylko na ich dekodery DV8555, ale jest link do pobrania https://apkcombo.com/downloader/#package=pl.orange.orangetv&device=tv)
Orange wypuścił dekoder "4K Stream" na Androidzie ze swoją aplikacją do oglądania telewizji, która korzysta z tych samych zasobów co Orange TV GO, z taką różnicą że są dostępne wszystkie kanały. Tutaj wątek z forum Orange gdzie to rozpracowywali: https://nasz.orange.pl/t5/Dekodery-i-inne/Tranmisja-IP-TV-do-dekodera-Stream-4k/m-p/351494#M8964

**Comment by mayones2** [comment]
znowu jakieś problemy z zalogowanie we wtyczce, w ich apce wszystko działa

**Comment by mayones2** [comment]
https://github.com/mbebe/blomqvist/issues/1017#issuecomment-1847558862

**Comment by pbaloo** [comment]
Witam, ponownie wtyczka przestała działać. Orange wprowadził jakieś zmiany? Poniżej fragment logu.

2024-03-31 22:15:07.981 T:13300   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 971, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\plugin.video.orangetvgo\main.py", line 6, in <module>
                                                       OrangeGo()
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\plugin.video.orangetvgo\resources\lib\orange.py", line 721, in __init__
                                                       plugin.run()
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\plugin.video.orangetvgo\resources\lib\orange.py", line 31, in root
                                                       dod, logged = loguj()
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\plugin.video.orangetvgo\resources\lib\orange.py", line 674, in loguj
                                                       jsdata = helper.request_sess(helper.subscrlogin, 'post', headers=helper.headers, data= data, json=True, json_data = True)
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\plugin.video.orangetvgo\resources\lib\helper.py", line 225, in request_sess
                                                       return resp.json() if json else resp_text(resp)
                                                     File "C:\Users\ddn\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 975, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

**Comment by mtr81** [comment]
Której wersji wtyczki używasz?

**Comment by pbaloo** [comment]
Wtyczka: plugin.video.orangetvgo-0.9, KODI wersja 20.5.0.0, nie działa na Windows i na Androidzie

**Comment by mtr81** [comment]
Staroć... Tu masz aktualną wersję -> https://github.com/mbebe/blomqvist/issues/1017#issuecomment-1965776139

**Comment by pbaloo** [comment]
Dzięki, działa aż miło.
