### ISSUE TITLE
fmovies broken again

### ISSUE THREAD

**Issue by amerr97** [mbebe/blomqvist#972]
Hi,
It seems that fmovies again updated their site ?  
I get an error every time when I need to pick a movie from a list, or a tv series. 
Regards,

**Comment by pitsi** [comment]
And the log no one asked for
```
2023-08-02 18:00:55.320 T:140425658574592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1402, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1257, in router
                                                getLinks(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 473, in getLinks
                                                verid = getVerid(idx[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2023-08-02 18:00:55.491 T:140426765920000   ERROR: GetDirectory - Error getting plugin://plugin.video.fmoviesto/?image=https%3a%2f%2fstatic.bunnycdn.ru%2fi%2fcache%2fimages%2f4%2f42%2f424c393b03bc26298ec9001f702f4b8f.jpg&mode=getLinks&movie=True&moviescount=0&page=1&title=The%20Flash&url=https%3a%2f%2ffmovies.to%2fmovie%2fthe-flash2-mjkwv%7cmjkwv
2023-08-02 18:00:55.500 T:140427076429952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fmoviesto/?image=https%3a%2f%2fstatic.bunnycdn.ru%2fi%2fcache%2fimages%2f4%2f42%2f424c393b03bc26298ec9001f702f4b8f.jpg&mode=getLinks&movie=True&moviescount=0&page=1&title=The%20Flash&url=https%3a%2f%2ffmovies.to%2fmovie%2fthe-flash2-mjkwv%7cmjkwv) failed
```
It's from kodi 18.9, running on libreelec 9.2.6 x64 though. I hope the error is the same on newer versions with python3.

**Comment by freeeeurope** [comment]
Hello. I have the same problem on my android box with Kodi version 19.5. The FMovies addon really stopped working. I would like to request a fix for the FMovies add-on. Thank you in advance.

**Comment by mbebe** [comment]
Fixed.
New ver in repo.
All stream links fixed.

**Comment by freeeeurope** [comment]
Excellent.... Very thanks 👍👍👍🙋‍♂️
